# ============================================================
# 转场语法知识库 — 镜头衔接的语言学
# 来源：IMDB Top 250剪辑分析 + 蒙太奇理论 + 短视频转场趋势
# ============================================================

TRANSITION_GRAMMAR = {
    "cut_types": {
        # ─── 深度决策: 每种剪辑 = 触发→原理→量化执行→失败模式→验收→替代→交叉 ───
        "hard_cut": {
            "cn": "硬切",
            "trigger": "常规对话正反打/连续动作/标准叙事/能量连贯推进",
            "rationale": "硬切=最中性的剪辑, 不引人注意。切在动作完成点或视线转移点=观众潜意识接受。",
            "execution": {
                "cut_point": "切在动作完成点/视线转移点/台词句读处",
                "rhythm": "对话每句一镜, 动作按动作节拍切",
                "continuity": "须守180度轴线+30度规则",
            },
            "failure_modes": ["切点不准=跳, 须在动作/视线/句读处", "越轴=空间感崩", "30度规则违反(相邻镜角度差<30)=像跳切错误"],
            "measurement": "观众不察觉剪辑=沉浸, 叙事能量连贯",
            "alternatives": ["j_cut(更流畅声音先行)", "l_cut(更延续情绪)"],
            "cross_refs": {"continuity": "硬切须守轴线+30度", "pacing": "硬切是节奏基准", "dialogue": "正反打标配"},
            "masters": "好莱坞通用剪辑",
        },
        "match_cut": {
            "cn": "匹配剪辑",
            "trigger": "时空跳跃/主题关联/联想/无缝场景转换/诗意连接",
            "rationale": "相似形状/动作/颜色/声音的两个画面衔接=潜意识联想, 跳跃时空但流畅。是最高级的剪辑技法。",
            "execution": {
                "type": "graphic(形状)/movement(运动)/color(颜色)/sound(声音)四类匹配",
                "precision": "匹配元素须占画面显著位置, 否则失匹配",
                "timing": "匹配点须在动作/构图的顶点",
            },
            "failure_modes": ["匹配不精确=失联想, 须占画面显著位置", "匹配滥用=炫技", "匹配无主题关联=为匹配而匹配"],
            "measurement": "观众应感到时空跳跃但流畅+主题关联",
            "alternatives": ["invisible_cut(更隐形但失联想)", "dissolve(更柔和但失冲击)"],
            "cross_refs": {"narrative": "时空跳跃的核心工具", "vertical": "短视频创意转场标配", "subtypes": "graphic形状/movement运动/color颜色/sound声音四类匹配"},
            "masters": "《2001太空漫游》骨头→卫星, 《阿拉伯的劳伦斯》火柴→日出",
        },
        "jump_cut": {
            "cn": "跳切",
            "trigger": "时间压缩/焦虑/现代感/不安/省略过程/角色心理断裂",
            "rationale": "同主体同角度时间跳跃=打破连续, 制造焦虑与现代感。是戈达尔开创的现代剪辑。",
            "execution": {
                "skip": "至少跳过30%动作才不显像错误",
                "angle": "同角度跳切=时间压缩; 微角度变化=焦虑",
                "use": "短视频标准手法:同角度不同时间/表情",
            },
            "failure_modes": ["跳过<30%=像剪辑错误, 须跳够", "跳切无现代/焦虑理由=失误感", "跳切滥用=观众晕"],
            "measurement": "观众应读出'时间压缩/焦虑/现代', 而非剪辑错误",
            "alternatives": ["hard_cut(更连贯)", "match_cut(更流畅跳跃)"],
            "cross_refs": {"genre": "现代/文艺/短视频标配", "narrative": "时间压缩工具", "pacing": "跳切加速节奏"},
            "masters": "《精疲力尽》戈达尔开创, 短视频标准",
        },
        "j_cut": {
            "cn": "J型切(声音先行)",
            "trigger": "预示即将到来的场景/引导注意力/流畅过渡/期待感",
            "rationale": "下一镜的声音提前进入当前画面=引导观众注意力, 制造期待与流畅。是高级剪辑的标志。",
            "execution": {
                "lead": "声音提前0.5-2秒进入",
                "use": "对话进入前先听到声音; 场景切换前先听到环境音",
                "timing": "须卡在当前画面情绪顶点转入",
            },
            "failure_modes": ["声音提前过长=突兀", "J切无预示理由=炫技", "J切破坏连戏声场=须注意"],
            "measurement": "观众应感到流畅过渡+期待即将场景",
            "alternatives": ["l_cut(相反,声音延续)", "hard_cut(更中性)"],
            "cross_refs": {"narrative": "场景转换预示工具", "sound": "J切是声画关系技法", "pacing": "J切制造期待"},
            "masters": "《教父》洗礼J切, 现代剪辑通用",
        },
        "l_cut": {
            "cn": "L型切(画面先行)",
            "trigger": "情绪延续/余韵/画面切了情感没切/反应镜延续台词",
            "rationale": "当前镜声音延续到下一画面=情绪延续, 让画面切但情感不切。是余韵工具。",
            "execution": {
                "extend": "声音延续0.5-3秒到下一画面",
                "use": "角色说完话切到对方反应, 但声音(台词/呼吸)延续",
                "reaction": "L切常配反应镜, 让台词在反应画面上延续",
            },
            "failure_modes": ["声音延续过长=脱节", "L切无情绪理由=炫技", "L切破坏对白清晰=须注意"],
            "measurement": "观众应感到情绪延续+余韵",
            "alternatives": ["j_cut(相反,声音先行)", "hard_cut(更干脆)"],
            "cross_refs": {"reaction": "反应镜常配L切", "emotion": "L切是情绪余韵工具", "pacing": "L切制造余韵"},
            "masters": "对话戏通用, 《社交网络》",
        },
        "smash_cut": {
            "cn": "猛切/对比切",
            "trigger": "震惊/讽刺/荒诞/喜剧/美梦惊醒/'说不会出事'立刻出事",
            "rationale": "极端反差两镜直接碰撞=震惊与荒诞。是喜剧与讽刺的核心工具。",
            "execution": {
                "contrast": "静vs响/美vs丑/承诺vs打脸, 反差越大越有力",
                "timing": "须卡在反差顶点, 突兀切换",
                "sound": "常配音效骤变(安静→爆响)",
            },
            "failure_modes": ["反差不够=失冲击", "smash cut滥用=疲劳", "无讽刺/喜剧理由=突兀"],
            "measurement": "观众应被反差碰撞震惊/逗笑",
            "alternatives": ["hard_cut(更中性)", "match_cut(更流畅相反)"],
            "cross_refs": {"genre": "喜剧/讽刺标配", "narrative": "'说不会出事→出事'是经典讽刺", "sound": "常配音效骤变"},
            "masters": "《低俗小说》猛切, 喜剧通用",
        },
        "invisible_cut": {
            "cn": "隐形剪辑",
            "trigger": "长镜头错觉/沉浸/伪一镜到底/《1917》全片伪长镜头",
            "rationale": "利用遮挡/黑场/快速移动隐藏剪辑点=观众不察觉剪辑, 制造长镜头错觉。",
            "execution": {
                "hide": "过黑物/柱子/运动模糊时切, 观众不察觉",
                "match": "切换前后构图/运动须匹配, 否则穿帮",
                "combine": "可配match cut强化隐形",
            },
            "failure_modes": ["切换前后不匹配=穿帮", "隐形剪辑无长镜头理由=炫技", "伪一镜到底过长=拖沓"],
            "measurement": "观众不察觉剪辑=沉浸, 长镜头错觉达成",
            "alternatives": ["oner(真长镜头但更难)", "match_cut(更可见但流畅)"],
            "cross_refs": {"narrative": "伪一镜到底核心", "steadicam": "常配steadicam长镜头", "continuity": "隐形切须守连戏"},
            "masters": "《1917》全片隐形剪辑, 《鸟人》伪一镜到底",
        },
        "cutaway": {
            "cn": "切出/插入镜头",
            "trigger": "强调细节/暗示隐喻/信息补充/角色反应/呼吸节奏",
            "rationale": "短暂切到相关但非主线画面=强调细节/埋伏笔/补充信息/给观众呼吸。是叙事的标点。",
            "execution": {
                "duration": "1-3秒短切",
                "type": "特写手中物/环境细节/角色反应/象征物",
                "return": "切出后须切回主线, 不可悬置",
            },
            "failure_modes": ["切出无意义=打断节奏", "切出不回主线=悬置", "切出过多=主线被打断"],
            "measurement": "切出应强调细节/埋伏笔/补充信息, 不可无意义",
            "alternatives": ["insert(更直接强调)", "reaction_shot(更聚焦反应)"],
            "cross_refs": {"foreshadow": "切出可埋伏笔", "pacing": "切出是节奏呼吸", "metaphor": "切出象征物=视觉隐喻"},
            "masters": "《教父》打字机切出, 通用剪辑",
        },
    },

    "optical_transitions": {
        "dissolve": {
            "cn": "叠化/溶解",
            "trigger": "时间流逝/梦境进入/记忆段落/温柔过渡/场景柔和切换",
            "rationale": "前一画面渐出+后一画面渐入=柔和过渡, 暗示时间或意识流的连续。是抒情与回忆的工具。",
            "execution": {
                "duration": "0.5-2秒(短=场景过渡, 长=时间流逝/梦境)",
                "overlap": "两画面交叠0.5-2秒",
                "use": "时间跳跃/回忆段/梦境进入",
            },
            "failure_modes": ["叠化过长=拖沓, 须控时长", "叠化无时间/回忆理由=炫技", "叠化滥用=失现代感(偏复古)"],
            "measurement": "观众应读出'时间流逝/梦境/记忆', 而非场景切换",
            "alternatives": ["fade_to_black(更重结束)", "hard_cut(更快但失柔和)"],
            "cross_refs": {"narrative": "回忆段标配", "time": "时间流逝视觉化", "genre": "文艺/复古标配"},
            "masters": "《公民凯恩》叠化, 回忆段通用",
        },
        "fade_to_black": {
            "cn": "淡入黑场",
            "trigger": "段落结束/角色失去意识/死亡/章节结束/重大情绪节点",
            "rationale": "画面渐暗至全黑=意识消失/结束。是叙事段落的最重收束。",
            "execution": {
                "duration": "1-3秒(短=段落, 长=死亡/终结)",
                "use": "段落结束/失去意识/死亡",
                "after": "常接fade_from_black开始新段",
            },
            "failure_modes": ["淡黑过长=拖沓", "淡黑无结束理由=炫技", "短剧用淡黑=完播率崩, 须慎用"],
            "measurement": "观众应读出'结束/消失/死亡', 是最重收束",
            "alternatives": ["dissolve(更柔和)", "fade_to_white(更顿悟)"],
            "cross_refs": {"narrative": "段落结束/死亡标配", "pacing": "淡黑是最重收束", "vertical": "短剧慎用"},
            "masters": "段落结束通用, 《教父》结尾淡黑",
        },
        "fade_from_black": {
            "cn": "从黑场淡入",
            "trigger": "新的开始/苏醒/新章节/从黑暗中浮现",
            "rationale": "全黑渐亮至画面=新的开始。常与fade_to_black配对, 标记章节转换。",
            "execution": {
                "duration": "1-3秒",
                "use": "新章节开始/角色苏醒/故事从虚无浮现",
                "pair": "常配fade_to_black形成章节",
            },
            "failure_modes": ["淡入过长=开场拖沓", "无新章节理由=炫技"],
            "measurement": "观众应读出'新的开始/苏醒'",
            "alternatives": ["fade_to_white(更顿悟)", "dissolve(更柔和)"],
            "cross_refs": {"narrative": "新章节/开场标配", "pacing": "淡入是章节起点"},
            "masters": "开场/章节转换通用",
        },
        "fade_to_white": {
            "cn": "白闪/白场过渡",
            "trigger": "顿悟/死亡(东方文化)/极端情绪爆发/超自然/修真突破/回忆闪回起点",
            "rationale": "画面过曝至全白=超越性的瞬间。东方白=死亡, 西方白=顿悟/超自然。",
            "execution": {
                "duration": "0.3-1秒(短闪=冲击, 长白=顿悟)",
                "use": "爆炸瞬间/修真突破/回忆闪回起点/顿悟",
                "cultural": "东方白=死亡, 西方白=顿悟",
            },
            "failure_modes": ["白闪滥用=廉价(特效感)", "无顿悟/死亡/超自然理由=炫技", "白闪过频=刺眼"],
            "measurement": "观众应读出'顿悟/死亡/超自然', 须慎用",
            "alternatives": ["fade_to_black(更重结束)", "match_cut(更流畅但失超自然)"],
            "cross_refs": {"narrative": "修真突破/闪回起点", "cultural": "东西方白色含义不同", "genre": "科幻/玄幻标配"},
            "masters": "《2001太空漫游》星际之门白闪, 修真突破",
        },
        "wipe": {
            "cn": "擦除/划变",
            "trigger": "平行时间/复古/漫画感/《星球大战》式章节转换",
            "rationale": "新画面以某方向推走旧画面=明确的段落转换, 带复古漫画感。是风格化工具。",
            "execution": {
                "direction": "横向/对角/圆形推走",
                "use": "平行时间段落转换/复古风格",
                "style": "偏复古/漫画/类型片",
            },
            "failure_modes": ["wipe滥用=廉价复古", "wipe无风格理由=失现代感", "wipe方向混乱=失章法"],
            "measurement": "观众应读出'段落转换+复古/风格化'",
            "alternatives": ["dissolve(更柔和)", "fade(更重)"],
            "cross_refs": {"genre": "复古/漫画/类型片标配", "narrative": "平行时间段落转换", "style": "偏风格化"},
            "masters": "《星球大战》经典横向划变",
        },
        "iris": {
            "cn": "光圈开合",
            "trigger": "聚焦注意力/复古默片感/童话感/早期电影致敬",
            "rationale": "圆形开合聚焦/展开=默片传统, 带童话与复古感。是特殊风格化工具。",
            "execution": {
                "type": "iris_out(开=展开)/iris_in(合=聚焦)",
                "use": "早期电影致敬/童话段落/特殊风格化",
                "style": "偏默片/童话",
            },
            "failure_modes": ["iris无复古/童话理由=突兀", "iris滥用=失风格"],
            "measurement": "观众应读出'复古默片/童话'风格化",
            "alternatives": ["wipe(更段落)", "dissolve(更柔和)"],
            "cross_refs": {"genre": "默片致敬/童话标配", "style": "特殊风格化", "narrative": "段落聚焦/展开"},
            "masters": "默片传统, 《布达佩斯》风格化",
        },
    },

    "montage_types": {
        # ─── 深度决策: 每种蒙太奇 = 触发→原理→量化执行→失败模式→验收→替代→交叉 ───
        "metric": {
            "cn": "度量蒙太奇",
            "trigger": "训练段落/时间流逝/音乐节拍匹配/机械感紧迫",
            "rationale": "按固定时长切换不顾内容=纯节奏驱动, 制造机械感与紧迫。是节拍器式剪辑。",
            "execution": {
                "interval": "固定时长(如每0.5秒/1秒一镜)",
                "music_sync": "切在音乐节拍点=律动",
                "ignore_content": "不顾画面内容, 只按时长",
            },
            "failure_modes": ["无音乐节拍支撑=机械但不流畅", "度量过快=眩晕", "无时间流逝/训练理由=炫技"],
            "measurement": "观众应感到节奏/机械/紧迫, 须有音乐或时间流逝支撑",
            "alternatives": ["rhythmic(更音乐性)", "tonal(更情绪)"],
            "cross_refs": {"genre": "训练段/MV标配", "music": "节拍器剪辑", "pacing": "度量=纯节奏"},
            "examples": "《洛奇》训练蒙太奇, MV通用",
        },
        "rhythmic": {
            "cn": "节奏蒙太奇",
            "trigger": "追逐戏/舞蹈/武术/动作高潮/音乐性段落",
            "rationale": "按画面内部运动节奏剪辑=流畅音乐性。动的画面短切, 静的画面长留, 画面自身能量决定时长。",
            "execution": {
                "energy": "动的画面短切(0.5-2s), 静的画面长留(3-6s)",
                "parallel": "两线交替加速=追逐戏张力递增",
                "music_sync": "切在运动/音乐节拍点",
            },
            "failure_modes": ["节奏与画面运动不匹配=失流畅", "两线交替不加速=失张力递增", "无音乐性段落=失音乐感"],
            "measurement": "观众应感到流畅音乐性+张力递增",
            "alternatives": ["metric(更机械)", "parallel(更多线)"],
            "cross_refs": {"genre": "动作/舞蹈标配", "pacing": "画面能量决定时长", "music": "节奏与音乐同步"},
            "examples": "追逐戏两线交替加速, 舞蹈/武术段落",
        },
        "tonal": {
            "cn": "调性蒙太奇",
            "trigger": "自然风光段落/情绪过渡/诗性/抒情/氛围营造",
            "rationale": "按情感调性(光影/色彩/构图)衔接=情绪渐变与诗意。是抒情段核心。",
            "execution": {
                "tone": "按光影/色彩/构图调性衔接",
                "gradient": "情绪渐变, 非突变",
                "use": "自然风光段/情绪过渡/主题升华",
            },
            "failure_modes": ["调性无渐变=失诗意", "调性突变=失流畅", "无抒情段落=炫技"],
            "measurement": "观众应感到情绪渐变与诗意",
            "alternatives": ["associative(更联想)", "rhythmic(更节奏)"],
            "cross_refs": {"genre": "文艺/诗电影标配", "director": "Malick/塔可夫斯基偏好", "pacing": "调性渐变"},
            "examples": "Malick自然段, 塔可夫斯基诗电影",
        },
        "intellectual": {
            "cn": "理性蒙太奇(隐喻)",
            "trigger": "隐喻/讽刺/观点表达/1+1=3的并置/主题深化",
            "rationale": "无关画面并列产生新含义=1+1=3。两个画面的碰撞产生第三个概念(隐喻/讽刺)。",
            "execution": {
                "juxtaposition": "两个无关画面并置",
                "meaning": "碰撞产生第三义(隐喻/讽刺/观点)",
                "timing": "并置须有逻辑关联, 非随机",
            },
            "failure_modes": ["并置无逻辑关联=随机无义", "隐喻过隐=观众不懂", "讽刺过直=说教"],
            "measurement": "观众应读出并置产生的第三义(隐喻/讽刺)",
            "alternatives": ["associative(更联想)", "tonal(更调性)"],
            "cross_refs": {"genre": "艺术/讽刺标配", "eisenstein": "爱森斯坦首创", "narrative": "观点表达工具"},
            "examples": "爱森斯坦:屠宰场+罢工镇压=对工人如牲畜, 《教父》洗礼+刺杀=神圣与暴力",
        },
        "parallel": {
            "cn": "平行蒙太奇",
            "trigger": "两条时间线交替/同时性/命运交织/对比因果/《教父》洗礼+刺杀",
            "rationale": "两条(或多条)时间线交替=对比/因果/同时性/命运交织。是史诗与多线叙事核心。",
            "execution": {
                "lines": "两条或多条线交替",
                "accelerate": "交替加速=同时性逼近, 张力递增",
                "converge": "各线最终交汇=命运碰撞",
            },
            "failure_modes": ["线索无关联=失交汇价值", "交替不加速=失张力", "线索过多=观众迷失"],
            "measurement": "各线有微妙联系, 交替加速, 最终交汇碰撞",
            "alternatives": ["nonlinear(更碎片)", "rhythmic(更节奏)"],
            "cross_refs": {"genre": "史诗/多线叙事标配", "structure": "parallel_convergence", "pacing": "交替加速→交汇"},
            "examples": "《教父》洗礼+屠杀, 《盗梦空间》多层梦境, 《敦刻尔克》海陆空三线",
        },
        "associative": {
            "cn": "联想蒙太奇",
            "trigger": "MV式剪辑/抒情段落/主题升华/超越时空联系/诗意",
            "rationale": "通过视觉/概念相似性串联不同时空=诗意与隐喻。超越时空的联系。",
            "execution": {
                "similarity": "视觉/概念相似性串联",
                "cross_time": "不同时空通过相似性连接",
                "use": "MV/抒情段/主题升华",
            },
            "failure_modes": ["相似性过牵强=失联想", "串联无主题=随机", "联想过隐=观众不懂"],
            "measurement": "观众应感到超越时空的诗意联系",
            "alternatives": ["match_cut(更精确匹配)", "tonal(更调性)"],
            "cross_refs": {"genre": "MV/抒情标配", "match_cut": "联想是匹配剪辑的广义版", "pacing": "诗意串联"},
            "examples": "MV式剪辑, 抒情段落",
        },
    },

    "short_video_transitions": {
        # ─── 深度决策: 短视频转场4大类(每类含techniques+决策字段) ───
        "movement_based": {
            "cn": "运动转场",
            "trigger": "短视频场景切换/动感过渡/利用物理运动隐藏剪辑点",
            "rationale": "利用相机/身体/物体的物理运动模糊瞬间隐藏剪辑=隐形转场, 动感且流畅。",
            "techniques": [
                "甩手机/相机(急速模糊→新画面清晰)",
                "转身/回头(转到一半切新场景)",
                "物体遮挡(手/纸/门经过镜头时切)",
                "跳起/蹲下(利用垂直运动切)",
                "推向镜头/拉离镜头(接近至黑/远离至黑)",
            ],
            "failure_modes": ["运动模糊不够=剪辑点可见", "运动方向不匹配=穿帮", "运动转场滥用=眩晕"],
            "measurement": "剪辑点隐藏在运动模糊中, 观众不察觉切换",
            "alternatives": ["match_action(更动作匹配)", "creative_transitions(更创意)"],
            "cross_refs": {"vertical": "竖屏运动转场适配(纵向运动)", "pacing": "运动转场加速节奏", "invisible_cut": "运动转场是隐形剪辑的短视频版"},
        },
        "match_action": {
            "cn": "动作匹配转场",
            "trigger": "短视频无缝场景跳转/同一动作跨场景/物品传递跨时空",
            "rationale": "同一动作跨场景延续=动作匹配, 观众潜意识接受场景切换, 流畅无感。",
            "techniques": [
                "同一动作不同场景(场景A推门→场景B推开)",
                "物品传递(A扔出→B接住,中间切场景)",
                "身体动作延续(A伸手→B世界接住)",
            ],
            "failure_modes": ["动作不匹配=穿帮(推门方向/速度不一致)", "匹配过牵强=失流畅", "无场景跳转理由=炫技"],
            "measurement": "动作跨场景无缝延续, 观众不察觉切换",
            "alternatives": ["movement_based(更运动)", "creative_transitions(更创意)"],
            "cross_refs": {"match_cut": "动作匹配是match_cut的短视频版", "vertical": "竖屏友好", "pacing": "动作匹配加速节奏"},
        },
        "creative_transitions": {
            "cn": "创意转场(短视频热门)",
            "trigger": "短视频爆款转场/变装/分屏/时间冻结/速度变化/镜面/画中画",
            "rationale": "创意转场=用特效/技巧制造不可能的切换, 是短视频的视觉糖衣, 制造惊喜与分享欲。",
            "techniques": [
                "变装转场(遮挡瞬间换装换景)",
                "分屏对比(同一动作/不同人/不同时间)",
                "时间冻结(所有人定格,主体移动)",
                "速度变化(常速→极慢→极快→新场景)",
                "光影切换(进入/走出阴影时切)",
                "镜面/反射(镜中世界是另一时空)",
                "画中画递进(手机屏幕中→放大进入)",
            ],
            "failure_modes": ["创意转场无叙事=炫技", "特效廉价=失质感", "创意转场滥用=疲劳"],
            "measurement": "转场制造惊喜+分享欲, 须有叙事或创意理由",
            "alternatives": ["movement_based(更自然)", "match_action(更匹配)"],
            "cross_refs": {"viral": "创意转场是爆款短视频核心", "vfx": "常配特效", "shareability": "创意转场提升分享率"},
        },
        "emotional_transitions": {
            "cn": "情绪转场",
            "trigger": "短视频情绪流过渡/表情匹配/声音桥/色彩渐变/呼吸同步",
            "rationale": "用情绪(表情/声音/色彩/节奏/呼吸)连接两个画面=情绪流过渡, 不靠物理而靠情感连接。",
            "techniques": [
                "表情匹配(A的笑→B的笑,不同时空相同情感)",
                "声音桥(A的尾声成为B的开场音)",
                "色彩渐变(暖→冷对应情绪转变)",
                "节奏呼应(前一镜最后一拍=后一镜第一拍)",
                "呼吸同步(角色呼吸节奏连接两个画面)",
            ],
            "failure_modes": ["情绪不匹配=失连接", "声音桥过突兀=穿帮", "色彩渐变无情绪逻辑=炫技"],
            "measurement": "观众应感到情绪流过渡, 不靠物理连接",
            "alternatives": ["match_action(更动作)", "movement_based(更运动)"],
            "cross_refs": {"emotion": "情绪转场靠情感连接", "sound": "声音桥是核心", "color": "色彩渐变对应情绪"},
        },
    },

    "transition_rules": {
        "continuity": {
            "30_degree_rule": "相邻镜头角度变化至少30度,否则像跳切错误",
            "180_degree_rule": "保持轴线,不跨越180度线(除非有意打破)",
            "eyeline_match": "角色看向画面右→下一镜从画面左进入",
            "screen_direction": "保持运动方向一致(向右走在所有镜头中都向右)",
        },
        "rhythm_matching": {
            "rule": "转场的速度/风格必须与当前情绪节奏匹配",
            "fast_pacing": "硬切/跳切/甩镜→紧张/动作/混乱",
            "slow_pacing": "叠化/缓推→抒情/回忆/沉思",
            "mixed": "硬切为主+关键时刻叠化→对比强化情绪拐点",
        },
        "narrative_logic": {
            "time_skip": "叠化/淡黑/白闪+时间标记文字",
            "same_time_diff_place": "硬切+音效桥/对白桥",
            "flashback": "白闪/叠化进+色调变化(暖/去饱和)+缓推镜",
            "dream_entry": "缓叠化+焦距变化+音效变化(回声/低频)",
            "revelation": "快速推镜/zoom+音效骤停+特写",
        },
    },

    # ========================================================
    # 扩充: 高级蒙太奇手法
    # ========================================================
    "advanced_montage": {
        # ─── 深度决策: 高级蒙太奇 ───
        "intellectual_montage": {
            "cn": "理性蒙太奇进阶(辩证综合)",
            "trigger": "主题辩证/正题-反题-合题/观众主动生产意义/深层观点表达",
            "rationale": "进阶版≠基础并置。爱森斯坦辩证法: 两个镜头(正题+反题)碰撞, 观众脑中'生产'第三义(合题)。意义不在画面里而在观众主动综合中, 是最高级的意义生产。",
            "execution": {
                "dialectic": "正题(A)→反题(B)→合题(观众生产)≠A+B简单相加",
                "logic": "并置须有内在张力(冲突/对照), 非任意",
                "timing": "辩证高潮在主题顶点, 非情绪点",
                "spectator_work": "意义靠观众完成, 须留思考空间",
            },
            "failure_modes": ["并置无内在张力=随机无义", "合题过显=剥夺观众生产(变说教)", "合题过隐=观众无法综合", "与montage_types.intellectual重复=失进阶价值(须辩证深化非基础并置)"],
            "measurement": "观众主动生产出合题意义(非被动接收), 并置有内在张力",
            "alternatives": ["overtonal_montage(更累积非辩证)", "montage_types.intellectual(基础并置非辩证)"],
            "cross_refs": {"genre": "艺术/先锋标配", "eisenstein": "辩证蒙太奇首创", "narrative": "观众生产意义", "advanced": "进阶版须辩证深化"},
            "examples": "爱森斯坦《罢工》:屠宰场(正题:牲畜)×罢工镇压(反题:工人)→合题:工人被当牲畜(观众生产)",
        },
        "overtonal_montage": {
            "cn": "调性蒙太奇进阶(泛音累积)",
            "trigger": "主题泛音/多 motif 交织累积/非因果情感升华/诗性主题回响",
            "rationale": "进阶版≠基础调性匹配。泛音=多 motif(视觉/色彩/情绪/音)交织, 累积成主题'回声', 观众感受主题泛音而非单个 motif。是主题升华最高形式。",
            "execution": {
                "multi_motif": "多 motif 交织(非单一 motif 重复)",
                "accumulation": "累积成主题泛音, 非因果",
                "use": "主题升华/诗性结尾/非叙事段落",
                "resonance": "motif 间产生共鸣, 非线性叠加",
            },
            "failure_modes": ["单 motif 重复=降为基础 tonal", "多 motif 无共鸣=杂乱", "泛音过隐=观众无感", "与montage_types.tonal重复=失进阶价值(须多 motif 泛音非单 motif 调性)"],
            "measurement": "多 motif 交织产生主题泛音回声, 观众感受主题升华",
            "alternatives": ["intellectual_montage(更辩证)", "montage_types.tonal(基础调性非泛音)"],
            "cross_refs": {"genre": "诗电影/艺术标配", "director": "Malick/塔可夫斯基", "advanced": "进阶版须多 motif 泛音非单 motif"},
            "examples": "Malick《生命之树》:光/草/水/天空多 motif 交织→生命泛音",
        },
        "metric_montage_precise": {
            "cn": "节拍蒙太奇(精确)",
            "trigger": "歌舞片/预告片/MV/动作高潮/音乐节拍精确切换",
            "rationale": "按音乐节拍精确切换=画面节奏=音乐节奏。是律动感最强的蒙太奇。",
            "execution": {
                "beat_sync": "切在音乐节拍点(每拍/每半拍)",
                "precision": "精确到帧, 差一帧失律动",
                "use": "歌舞/预告/MV/动作高潮",
            },
            "failure_modes": ["不卡节拍=失律动", "节拍过密=眩晕", "无音乐支撑=失意义"],
            "measurement": "画面切换精确卡音乐节拍, 律动感强",
            "alternatives": ["rhythmic_montage_advanced(更画面运动)", "metric(更机械)"],
            "cross_refs": {"genre": "歌舞/MV/预告标配", "music": "节拍器剪辑", "pacing": "节拍精确"},
        },
        "rhythmic_montage_advanced": {
            "cn": "节奏蒙太奇进阶",
            "trigger": "追逐戏/舞蹈/武术/动作高潮/画面内部运动节奏剪辑",
            "rationale": "根据画面内部运动节奏剪辑, 而非外部时长。动的画面短切, 静的画面长留——画面自身能量决定时长。",
            "execution": {
                "energy_driven": "动的画面短切(0.5-2s), 静的画面长留(3-6s)",
                "internal_rhythm": "按画面内部运动节奏, 非外部节拍",
                "parallel_accelerate": "两线交替加速=张力递增",
            },
            "failure_modes": ["节奏与画面运动不匹配=失流畅", "两线不加速=失张力", "无音乐性段落=失特色"],
            "measurement": "画面能量决定时长, 流畅音乐性, 张力递增",
            "alternatives": ["metric_montage_precise(更节拍)", "rhythmic(基础)"],
            "cross_refs": {"genre": "动作/舞蹈标配", "pacing": "画面能量决定时长", "music": "与音乐同步"},
        },
    },

    # ========================================================
    # 扩充: 转场选择速查表(字符串速查, 非条目型)
    # ========================================================
    "transition_quickmap": {
        "by_emotion": {
            "愤怒爆发": "猛切+音效强化+急推",
            "温柔渐生": "缓叠化+暖色渐变+长留",
            "恐惧加剧": "跳切(不安)+暗部扩大+手持晃动",
            "希望初现": "L切(情绪延续)+渐亮+缓推",
            "绝望下沉": "淡出黑场(长)+沉默+空镜",
            "顿悟瞬间": "白闪/骤停音效+特写+缓拉揭示",
        },
        "by_narrative": {
            "新场景进入": "建立镜硬切+音效桥",
            "时间流逝": "叠化+季节变化或物件变化",
            "回忆进入": "白闪/叠化+暖调+缓推",
            "梦境进入": "缓叠化+焦距变化+回声音效",
            "平行叙事": "交叉剪辑+音效/对白桥连接",
            "高潮推进": "跳切加速+音乐渐强",
        },
        "by_pacing": {
            "极快节奏(动作/紧张)": "硬切/跳切/甩镜为主",
            "中速叙事": "硬切为主+关键节点叠化",
            "慢节奏(抒情/记忆)": "叠化/缓推/长留为主",
            "混乱失控": "随机短切+不规则节奏",
        },
    },

    # ========================================================
    # 扩充: 短视频爆款转场全集(7维深度决策)
    # ========================================================
    "viral_transition_full": {
        "magic_edit": {
            "cn": "魔法剪辑",
            "trigger": "短视频魔术/分身瞬移变小穿墙/无缝剪辑制造不可能",
            "rationale": "匹配剪辑制造魔法错觉, 观众反复观看找剪辑点=重复观看率。",
            "execution": {"technique": "匹配剪辑(形状/动作/位置)", "precision": "精确到帧", "no_cg": "无CG错觉"},
            "failure_modes": ["匹配不精确=穿帮", "魔法无创意=失趣", "CG过度=失错觉"],
            "measurement": "魔法错觉达成, 观众反复观看找剪辑点",
            "alternatives": ["match_shape(更形状)", "wardrobe_swap(更换装)"],
            "cross_refs": {"viral": "重复观看率核心", "match_cut": "魔法剪辑基础"},
        },
        "wardrobe_swap": {
            "cn": "变装转场",
            "trigger": "短视频变装/遮挡瞬间换装换景/before-after对比",
            "rationale": "遮挡瞬间换装换景=反差冲击, 是变装类爆款核心。",
            "execution": {"technique": "遮挡(手/物体/转身)瞬间切", "contrast": "换装反差越大越有效", "speed": "瞬间切换"},
            "failure_modes": ["遮挡不严=穿帮", "反差不够=失冲击", "变装无主题=炫技"],
            "measurement": "遮挡瞬间换装, 反差冲击达成",
            "alternatives": ["magic_edit(更魔法)", "object_wipe(更物件)"],
            "cross_refs": {"viral": "变装类爆款", "pacing": "瞬间切换加速"},
        },
        "speed_ramp": {
            "cn": "速度斜坡转场",
            "trigger": "短视频速度变化转场/常速→极慢→极快→新场景",
            "rationale": "速度变化(常速→慢→快→新场景)=用速度曲线制造转场, 是动感转场核心。",
            "execution": {"curve": "常速→升格(慢)→降格(快)→新场景", "sync": "速度与音乐同步", "timing": "卡节拍"},
            "failure_modes": ["速度变化无逻辑=眩晕", "不卡节拍=失律动", "无新场景=失转场"],
            "measurement": "速度曲线转场, 律动感+新场景达成",
            "alternatives": ["freeze_motion(更冻结)", "lens_whip(更甩镜)"],
            "cross_refs": {"viral": "速度变化爆款", "music": "与音乐同步", "pacing": "速度曲线"},
        },
        "freeze_motion": {
            "cn": "时间冻结转场",
            "trigger": "短视频时间冻结/所有人定格主体移动/超现实段落",
            "rationale": "所有人定格主体移动=时间冻结, 是超现实转场, 制造不可能感。",
            "execution": {"technique": "定格(所有人静止)主体移动", "vfx": "常需特效或多次拍摄合成", "subject": "主体在定格中移动"},
            "failure_modes": ["定格不严=穿帮", "主体移动无目的=失叙事", "特效廉价=失质感"],
            "measurement": "时间冻结达成, 主体移动有叙事",
            "alternatives": ["speed_ramp(更速度)", "shadow_pass(更光影)"],
            "cross_refs": {"viral": "超现实爆款", "vfx": "常需特效合成"},
        },
        "lens_whip": {
            "cn": "甩镜转场",
            "trigger": "短视频甩镜转场/急速甩镜模糊→新画面清晰",
            "rationale": "急速甩镜模糊瞬间隐藏剪辑点=隐形转场, 动感且流畅。",
            "execution": {"technique": "急速甩镜(>360度/秒)", "blur": "模糊瞬间隐藏剪辑", "timing": "卡动作节拍"},
            "failure_modes": ["甩镜不快=穿帮", "不卡节拍=突兀", "甩镜过频=眩晕"],
            "measurement": "甩镜隐藏剪辑点, 观众不察觉切换",
            "alternatives": ["object_wipe(更物件)", "speed_ramp(更速度)"],
            "cross_refs": {"viral": "动感转场", "invisible_cut": "甩镜是隐形剪辑"},
        },
        "object_wipe": {
            "cn": "物件擦除转场",
            "trigger": "短视频物件遮挡转场/手/纸/门/杯经过镜头时切",
            "rationale": "物体经过镜头遮挡瞬间切=隐形转场, 简单且流畅。",
            "execution": {"objects": "手/纸/门/杯/布料经过镜头", "timing": "遮挡满屏瞬间切", "match": "切换前后构图匹配"},
            "failure_modes": ["遮挡不满屏=穿帮", "切换前后不匹配=失流畅", "物件无理由=失叙事"],
            "measurement": "物件遮挡隐藏剪辑, 切换前后匹配",
            "alternatives": ["lens_whip(更甩镜)", "wardrobe_swap(更换装)"],
            "cross_refs": {"viral": "简单隐形转场", "invisible_cut": "物件遮挡是隐形剪辑"},
        },
        "shadow_pass": {
            "cn": "阴影穿越转场",
            "trigger": "短视频光影转场/走入走出阴影时切场景",
            "rationale": "走入/走出阴影瞬间切=用光影变化隐藏剪辑, 是氛围转场。",
            "execution": {"technique": "进入/走出阴影(柱子/墙/暗处)时切", "lighting": "光影变化隐藏剪辑", "mood": "氛围转场"},
            "failure_modes": ["阴影无变化=穿帮", "切换前后光影不匹配=失流畅", "无氛围理由=炫技"],
            "measurement": "光影变化隐藏剪辑, 氛围转场达成",
            "alternatives": ["object_wipe(更物件)", "screen_zoom(更画中画)"],
            "cross_refs": {"viral": "氛围转场", "lighting": "光影变化核心"},
        },
        "screen_zoom": {
            "cn": "画中画递进转场",
            "trigger": "短视频画中画转场/推近屏幕→放大进入新场景",
            "rationale": "推近屏幕→放大进入=层级递进, 是'进入'式转场, 制造深入感。",
            "execution": {"technique": "推近屏幕(手机/电视/镜)→放大进入", "layers": "画中画层级递进", "match": "放大匹配新场景"},
            "failure_modes": ["放大不匹配=穿帮", "层级无递进=失深入", "无叙事理由=炫技"],
            "measurement": "画中画层级递进, 放大进入新场景",
            "alternatives": ["shadow_pass(更光影)", "match_shape(更形状)"],
            "cross_refs": {"viral": "画中画爆款", "narrative": "进入式转场"},
        },
        "match_shape": {
            "cn": "形状匹配转场",
            "trigger": "短视频形状匹配转场/相似形状跨场景(圆→圆/三角→山峰)",
            "rationale": "相似形状跨场景匹配=联想转场, 是match_cut的短视频创意版。",
            "execution": {"technique": "相似形状(圆/三角/方)跨场景匹配", "precision": "形状须占画面显著位置", "creativity": "形状联想越巧妙越有效"},
            "failure_modes": ["形状不相似=失匹配", "形状过小=失联想", "联想牵强=失流畅"],
            "measurement": "形状跨场景匹配, 联想流畅",
            "alternatives": ["match_color(更颜色)", "magic_edit(更魔法)"],
            "cross_refs": {"viral": "创意转场", "match_cut": "形状匹配基础"},
        },
        "match_color": {
            "cn": "颜色匹配转场",
            "trigger": "短视频颜色匹配转场/相同颜色跨场景(红花→红裙)",
            "rationale": "相同颜色跨场景匹配=色彩联想转场, 是色彩驱动的流畅切换。",
            "execution": {"technique": "相同颜色跨场景匹配", "precision": "颜色须占画面显著位置", "transition": "色彩桥接"},
            "failure_modes": ["颜色不匹配=失联想", "颜色过小=失桥接", "色彩冲突=失流畅"],
            "measurement": "颜色跨场景匹配, 色彩桥接流畅",
            "alternatives": ["match_shape(更形状)", "shadow_pass(更光影)"],
            "cross_refs": {"viral": "色彩转场", "color": "色彩联想核心"},
        },
    },
}
