# -*- coding: utf-8 -*-
"""
SCENE_LIBRARY_120 - 影视场景库
================================================
Phase 28 P0 - 联网研究 100+ 场景库

数据源:
- 环球青藤 / 知乎 / 百度文库 影视场景分类 (6 大类)
- 杨远婴《电影概论》 画面基本元素
- 知乎《电影 75 种常见场景类型》(75 种故事场景)
- 实地考察 + 真实电影场景 (上海老影院/横店影视城/重庆森林/花样年华/盗梦空间/银翼杀手)

覆盖 6 大基础场景类型 + 真实场景 120+:
- 摄影棚内景 (STUDIO_INTERIOR)
- 自然外景 (NATURE_EXTERIOR)
- 实景外景 (URBAN_EXTERIOR)
- 实景内景 (URBAN_INTERIOR)
- 影片拍摄外景 (PERIOD_FILM_LOCATION)
- 虚拟场景 (VIRTUAL_SCENE)
- 心理空间 (PSYCHE_SPACE) - 扩展
- 梦境/记忆 (DREAM_MEMORY) - 扩展

每个场景 = 基础描述 + 灯光建议 + 声音建议 + 色彩调性 + 镜头建议 + 导演参考
"""
from __future__ import annotations

# ============================================================
# 6 大基础类型常量
# ============================================================
SCENE_TYPES_6 = {
    "STUDIO_INTERIOR": "摄影棚内景",
    "NATURE_EXTERIOR": "自然外景",
    "URBAN_EXTERIOR": "实景外景",
    "URBAN_INTERIOR": "实景内景",
    "PERIOD_FILM_LOCATION": "影片拍摄外景",
    "VIRTUAL_SCENE": "虚拟场景",
    "PSYCHE_SPACE": "心理空间(扩展)",
    "DREAM_MEMORY": "梦境/记忆(扩展)",
}

# ============================================================
# 场景库主体 (120+ 场景)
# 每个场景字段:
#   type: 大类
#   sub: 子类标签
#   desc: 文字描述 (用于 prompt)
#   light: 默认灯光建议
#   color: 默认色彩调性
#   lens: 镜头建议
#   sound: 声音建议
#   ref: 真实电影参考 (导演 + 作品)
#   mood: 适配情绪 (8 基础情感)
# ============================================================

SCENES = [
    # ============================================================
    # 类别 1: 摄影棚内景 (STUDIO_INTERIOR) - 15 个
    # ============================================================
    {
        "id": "studio_classic_apartment",
        "name": "经典棚内公寓 (现代/民国/60-80 年代)",
        "type": "STUDIO_INTERIOR",
        "sub": "apartment",
        "desc": "棚内搭建的公寓楼内景, 一室一厅或两室一厅, 桌椅家具齐全, 厨房半开放, 卧室可分",
        "light": "顶光主光 + 窗户侧光 + 钨丝灯台灯, 暖色 3000K, 营造家庭感",
        "color": "暖米黄/木质/浅咖, 偶尔用墨绿/酒红点缀情绪",
        "lens": "中景(MS) / 中近景(MCU) / 特写(CU) 为主, 35-50mm",
        "sound": "墙壁钟声 / 冰箱嗡鸣 / 走廊邻居脚步 / 远处电视 / 厨房油锅",
        "ref": "王家卫《花样年华》/侯孝贤《咖啡时光》/是枝裕和《步履不停》",
        "mood": "warm_regret,tenderness,longing",
    },
    {
        "id": "studio_office_modern",
        "name": "现代办公室 (落地玻璃/隔间/工位)",
        "type": "STUDIO_INTERIOR",
        "sub": "office",
        "desc": "现代企业办公区, 玻璃隔断, 电脑工位, 会议室, 走廊光带",
        "light": "冷白 LED 主光 5500K, 顶光均匀, 局部射灯突出人物",
        "color": "冷白/银灰/玻璃蓝, 偶尔一抹品牌色",
        "lens": "广角(WS) 全景展示规模 / 中景(MS) 对话",
        "sound": "键盘声 / 电话铃 / 复印机 / 中央空调 / 走廊高跟鞋",
        "ref": "诺兰《盗梦空间》/大卫·芬奇《社交网络》/丹尼斯·维伦纽瓦《银翼杀手2049》",
        "mood": "anticipation,trust,anticipation",
    },
    {
        "id": "studio_hospital_ward",
        "name": "医院病房/手术室",
        "type": "STUDIO_INTERIOR",
        "sub": "hospital",
        "desc": "医院内景, 病床/监护仪/吊瓶/手术台/无影灯",
        "light": "冷白主光 + 监护仪/吊瓶的局部绿红光, 营造生命感",
        "color": "冷白/淡蓝/手术绿, 偶尔血迹/药水颜色对比",
        "lens": "中近景(MCU) 表情 / 特写(CU) 心电监护仪",
        "sound": "心电监护仪 beep / 呼吸机 / 推车 / 护士脚步 / 远处广播",
        "ref": "诺兰《黑暗骑士》/奉俊昊《母亲》/陈凯歌《妖猫传》",
        "mood": "fear,sadness,tenderness",
    },
    {
        "id": "studio_classroom",
        "name": "教室/学堂 (黑板/课桌/讲台)",
        "type": "STUDIO_INTERIOR",
        "sub": "classroom",
        "desc": "传统教室, 排排课桌, 黑板粉笔, 讲台, 窗户自然光",
        "light": "侧窗自然光 4000K 主光 + 顶灯补光, 黑板微反光",
        "color": "木质/淡黄/书页白, 黑板墨绿, 偶尔彩色粉笔",
        "lens": "全景(FS) 教室全貌 / 中近景(MCU) 学生表情",
        "sound": "粉笔吱嘎 / 翻书 / 远处铃声 / 窗外操场",
        "ref": "是枝裕和《无人知晓》/岩井俊二《关于莉莉周的一切》/周星驰《功夫》",
        "mood": "trust,anticipation,nostalgia",
    },
    {
        "id": "studio_courtroom",
        "name": "法庭 (法官席/辩护席/旁听)",
        "type": "STUDIO_INTERIOR",
        "sub": "courtroom",
        "desc": "法庭内景, 高台法官席, 律师桌, 证人席, 国徽/法律条文装饰",
        "light": "顶光 + 国徽逆光轮廓, 木质暖色 3200K, 庄重",
        "color": "深木/酒红/国徽金, 黑白法袍对比",
        "lens": "全景(WS) 法庭规模 / 中景(MS) 律师辩护 / 特写(CU) 法官敲锤",
        "sound": "法槌敲击 / 书记员打字 / 旁听低语 / 走廊警员",
        "ref": "诺兰《黑暗骑士》/奉俊昊《杀人回忆》/斯派克·李《杀死一只知更鸟》",
        "mood": "anticipation,anger,trust",
    },
    {
        "id": "studio_police_station",
        "name": "警察局/审讯室",
        "type": "STUDIO_INTERIOR",
        "sub": "police",
        "desc": "警局内景, 审讯室单灯/办公区繁忙/拘留室铁栏",
        "light": "审讯室单顶灯 (无影灯) 营造压迫感 / 办公区冷白荧光灯",
        "color": "冷灰/铁锈/警徽银, 审讯室冷蓝/暖橙对比",
        "lens": "中近景(MCU) 审讯对峙 / 广角(WS) 拘留室铁栏",
        "sound": "警用电台 / 走廊脚步 / 铁门开关 / 打字机",
        "ref": "奉俊昊《杀人回忆》/大卫·芬奇《七宗罪》/科恩兄弟《老无所依》",
        "mood": "fear,anger,anticipation",
    },
    {
        "id": "studio_jail_prison",
        "name": "监狱/牢房 (铁栏/放风场/食堂)",
        "type": "STUDIO_INTERIOR",
        "sub": "prison",
        "desc": "监狱内景, 牢房铁栏/高低铺, 放风场水泥地, 食堂长条桌",
        "light": "冷白顶灯 + 走廊尽头的强光对比, 铁栏阴影",
        "color": "水泥灰/囚服橙/锈铁, 偶尔强光下泛白",
        "lens": "大全景(EWS) 牢房空间感 / 中近景(MCU) 囚犯对话",
        "sound": "铁门关闭 / 走廊广播 / 远处电锯 / 探照灯",
        "ref": "奉俊昊《母亲》/大卫·芬奇《十二宫》/陈凯歌《霸王别姬》",
        "mood": "sadness,fear,anger",
    },
    {
        "id": "studio_brothel_red_lantern",
        "name": "古代青楼/妓院 (民国/明清)",
        "type": "STUDIO_INTERIOR",
        "sub": "brothel",
        "desc": "古代青楼内景, 雕花床/红绸/灯笼/绣帘/八仙桌",
        "light": "红灯笼主光 暖红 2200K + 蜡烛侧光, 暧昧神秘",
        "color": "大红/金/紫绸/墨绿, 强烈对比",
        "lens": "中景(MS) 人物对话 / 特写(CU) 手指/眼睛",
        "sound": "古琴/二胡/丝竹/醉笑/夜风",
        "ref": "陈凯歌《霸王别姬》/张艺谋《金陵十三钗》/王家卫《一代宗师》",
        "mood": "longing,desire,sadness",
    },
    {
        "id": "studio_throne_palace",
        "name": "古代宫殿/王座 (明清/唐汉)",
        "type": "STUDIO_INTERIOR",
        "sub": "palace",
        "desc": "宫殿内景, 龙柱/琉璃瓦/红墙/九龙壁/王座高台",
        "light": "顶光 + 蜡烛/油灯主光 2200K, 烟雾缭绕",
        "color": "朱红/金/琉璃黄/玉白, 富丽堂皇",
        "lens": "大全景(EWS) 宫殿全貌 / 中近景(MCU) 帝王表情",
        "sound": "钟鼓/朝臣低语/仪仗脚步/礼乐",
        "ref": "陈凯歌《妖猫传》/张艺谋《英雄》/贝纳尔多·贝托鲁奇《末代皇帝》",
        "mood": "trust,anticipation,anger",
    },
    {
        "id": "studio_lab_science",
        "name": "实验室/科研机构",
        "type": "STUDIO_INTERIOR",
        "sub": "lab",
        "desc": "现代实验室, 试管/烧瓶/离心机/显微镜/超净台",
        "light": "冷白荧光主光 + 仪器局部蓝/绿光",
        "color": "冷白/银灰/仪器蓝, 偶尔化学试剂彩色",
        "lens": "中近景(MCU) 操作 / 特写(CU) 试管反应",
        "sound": "仪器嗡鸣/空调/通风柜/滴管",
        "ref": "诺兰《盗梦空间》/丹尼斯·维伦纽瓦《降临》/丹尼斯·维伦纽瓦《银翼杀手2049》",
        "mood": "anticipation,trust,fear",
    },
    {
        "id": "studio_subway_train",
        "name": "地铁车厢/火车内",
        "type": "STUDIO_INTERIOR",
        "sub": "train",
        "desc": "地铁/火车内景, 座椅/扶手/车窗/广播, 拥挤人群",
        "light": "冷白顶灯 + 车窗闪过的隧道光, 时明时暗",
        "color": "冷白/银灰/车厢广告色, 偶尔暖黄老火车",
        "lens": "广角(WS) 车厢全貌 / 中近景(MCU) 人物",
        "sound": "轨道轰隆/广播报站/人群嘈杂/刹车",
        "ref": "奉俊昊《寄生虫》/王家卫《重庆森林》/是枝裕和《无人知晓》",
        "mood": "loneliness,anticipation,longing",
    },
    {
        "id": "studio_elevator",
        "name": "电梯/狭小空间",
        "type": "STUDIO_INTERIOR",
        "sub": "elevator",
        "desc": "狭小电梯内景, 镜面/按钮/楼层显示",
        "light": "顶灯冷白 + 楼层显示数字光, 静止压抑",
        "color": "银灰/镜面反光/不锈钢, 偶尔彩光",
        "lens": "中近景(MCU) 对话 / 特写(CU) 表情/按钮",
        "sound": "升降机/楼层叮/缆绳/空调",
        "ref": "诺兰《盗梦空间》/王家卫《重庆森林》/奉俊昊《寄生虫》",
        "mood": "anticipation,fear,surprise",
    },
    {
        "id": "studio_kitchen_restaurant",
        "name": "厨房/餐厅 (家中/餐厅)",
        "type": "STUDIO_INTERIOR",
        "sub": "kitchen",
        "desc": "厨房或餐厅, 灶台/餐桌/餐具/吊灯/食物",
        "light": "暖黄吊灯 3000K 主光 + 灶台火光, 烟火气",
        "color": "暖黄/木质/食物色 (红番茄/绿菜/白米)",
        "lens": "全景(FS) 全景 / 中景(MS) 做饭 / 特写(CU) 刀工/火苗",
        "sound": "切菜/油锅/碗碟/水沸/抽油烟机",
        "ref": "是枝裕和《步履不停》/王家卫《花样年华》/李安《饮食男女》",
        "mood": "warm_regret,tenderness,trust",
    },
    {
        "id": "studio_bathroom_dressing",
        "name": "浴室/化妆间 (镜子/水汽)",
        "type": "STUDIO_INTERIOR",
        "sub": "bathroom",
        "desc": "浴室或化妆间, 镜子/水汽/瓶瓶罐罐/灯光",
        "light": "镜子前侧光主光 + 顶光补光, 戏剧化",
        "color": "瓷白/水汽/玻璃反光, 偶尔暖黄",
        "lens": "中近景(MCU) 镜前 / 特写(CU) 化妆/刮胡子",
        "sound": "水流/牙刷/化妆瓶碰撞/排气扇",
        "ref": "王家卫《花样年华》/奉俊昊《寄生虫》/陈凯歌《霸王别姬》",
        "mood": "longing,sadness,surprise",
    },
    {
        "id": "studio_church_temple",
        "name": "教堂/寺庙/宗教场所",
        "type": "STUDIO_INTERIOR",
        "sub": "religious",
        "desc": "教堂/寺庙/道观, 高顶/圣像/烛光/经幡/长椅",
        "light": "顶光 + 彩色玻璃花窗光 + 烛光 2200K, 神性",
        "color": "金/深红/藏青/圣白, 彩色玻璃投色",
        "lens": "大全景(EWS) 全殿 / 中景(MS) 仪式 / 特写(CU) 圣像",
        "sound": "管风琴/钟/诵经/蜡烛燃烧/脚步回声",
        "ref": "梅尔·吉布森《耶稣受难记》/陈凯歌《妖猫传》/黑泽明《梦》",
        "mood": "trust,awe,anticipation",
    },

    # ============================================================
    # 类别 2: 自然外景 (NATURE_EXTERIOR) - 20 个
    # ============================================================
    {
        "id": "nature_mountain_snow",
        "name": "雪山/高山 (远景/全景)",
        "type": "NATURE_EXTERIOR",
        "sub": "mountain",
        "desc": "雪山顶峰/高山草甸/冰川, 远景壮观",
        "light": "自然顶光 + 雪地反光, 早晚侧光金黄",
        "color": "雪白/天蓝/岩灰, 早昏金红",
        "lens": "极端广角(EWS) 宏大 / 全景(FS) 人物渺小",
        "sound": "风声/远处雪崩/鹰叫/寂静",
        "ref": "王家卫《一代宗师》/黑泽明《梦》/库布里克《2001太空漫游》",
        "mood": "awe,loneliness,anticipation",
    },
    {
        "id": "nature_forest_deep",
        "name": "深林/原始森林",
        "type": "NATURE_EXTERIOR",
        "sub": "forest",
        "desc": "原始森林, 古树/藤蔓/雾/苔藓/斑驳光",
        "light": "树缝光斑 (god rays) + 顶光散射, 神秘",
        "color": "墨绿/苔藓/枯叶棕, 雾时泛白",
        "lens": "全景(FS) 森林深度 / 中景(MS) 人物穿越",
        "sound": "鸟鸣/树叶/远处水流/虫鸣",
        "ref": "宫崎骏《幽灵公主》/泰伦斯·马力克《新世界》/塔可夫斯基《镜子》",
        "mood": "awe,trust,fear",
    },
    {
        "id": "nature_sea_ocean",
        "name": "海洋/海面/礁石",
        "type": "NATURE_EXTERIOR",
        "sub": "sea",
        "desc": "大海/礁石/沙滩/港口/海浪",
        "light": "自然光, 黄昏/清晨最佳, 银光闪闪",
        "color": "深蓝/银白/黄昏金红/礁石灰",
        "lens": "广角(WS) 海平面 / 中景(MS) 礁石人物 / 特写(CU) 海浪",
        "sound": "海浪/海鸥/船笛/风声",
        "ref": "王家卫《春光乍泄》/陈凯歌《妖猫传》/宫崎骏《悬崖上的金鱼姬》",
        "mood": "longing,loneliness,tenderness",
    },
    {
        "id": "nature_river_stream",
        "name": "河流/溪流/小桥",
        "type": "NATURE_EXTERIOR",
        "sub": "river",
        "desc": "河流/小溪/小桥/垂柳/木船",
        "light": "晨昏侧光 + 水中倒影, 宁静",
        "color": "水绿/青蓝/垂柳绿/木船棕",
        "lens": "全景(FS) 河面 / 中景(MS) 桥上人物 / 特写(CU) 水波",
        "sound": "流水/蛙鸣/鸟叫/木桨",
        "ref": "王家卫《花样年华》/侯孝贤《悲情城市》/小津安二郎《东京物语》",
        "mood": "tenderness,nostalgia,warm_regret",
    },
    {
        "id": "nature_lake_reflection",
        "name": "湖泊/镜面水",
        "type": "NATURE_EXTERIOR",
        "sub": "lake",
        "desc": "平静湖泊/水面倒影/远山/芦苇",
        "light": "清晨侧光 + 水面镜面反射, 通透",
        "color": "湖水蓝/天蓝/芦苇黄/远山青",
        "lens": "全景(FS) 湖面 / 特写(CU) 倒影",
        "sound": "微风/水鸟/桨声/寂静",
        "ref": "塔可夫斯基《镜子》/侯孝贤《刺客聂隐娘》/王家卫《东邪西毒》",
        "mood": "loneliness,tenderness,longing",
    },
    {
        "id": "nature_field_grass",
        "name": "草原/麦田/油菜花田",
        "type": "NATURE_EXTERIOR",
        "sub": "field",
        "desc": "草原/麦田/油菜花/风车/远山",
        "light": "黄昏侧光 30 度金黄, 风吹麦浪",
        "color": "金黄/麦绿/远山蓝/天空",
        "lens": "广角(WS) 麦田 / 中景(MS) 人物穿行",
        "sound": "风声/麦浪/远处牛羊/鸟叫",
        "ref": "张艺谋《红高粱》/陈凯歌《黄土地》/侯孝贤《童年往事》",
        "mood": "warm_regret,nostalgia,trust",
    },
    {
        "id": "nature_desert_dune",
        "name": "沙漠/戈壁/荒漠",
        "type": "NATURE_EXTERIOR",
        "sub": "desert",
        "desc": "沙漠/沙丘/戈壁/驼队/海市蜃楼",
        "light": "强烈顶光 + 黄昏金红, 干燥",
        "color": "沙黄/天蓝/驼队/海市蜃楼彩",
        "lens": "广角(WS) 沙丘 / 全景(FS) 驼队 / 特写(CU) 流沙",
        "sound": "风声/驼铃/寂静/沙响",
        "ref": "王家卫《东邪西毒》/陈凯歌《妖猫传》/大卫·里恩《阿拉伯的劳伦斯》",
        "mood": "loneliness,anticipation,awe",
    },
    {
        "id": "nature_cave_underground",
        "name": "山洞/溶洞/地下",
        "type": "NATURE_EXTERIOR",
        "sub": "cave",
        "desc": "山洞/溶洞/地下墓穴/钟乳石",
        "light": "手电光/火把/洞口强光对比, 神秘",
        "color": "岩石灰/苔藓绿/钟乳白/暗处黑",
        "lens": "中景(MS) 洞内 / 特写(CU) 钟乳石",
        "sound": "水滴回声/脚步回声/远处风声",
        "ref": "陈凯歌《妖猫传》/丹尼斯·维伦纽瓦《降临》/黑泽明《梦》",
        "mood": "fear,awe,anticipation",
    },
    {
        "id": "nature_waterfall_cliff",
        "name": "瀑布/悬崖/峡谷",
        "type": "NATURE_EXTERIOR",
        "sub": "waterfall",
        "desc": "瀑布/悬崖/峡谷/水雾/彩虹",
        "light": "阳光透过水雾, 彩虹, 侧光强烈",
        "color": "水白/岩石灰/绿植/彩虹",
        "lens": "广角(WS) 瀑布 / 中景(MS) 悬崖边 / 特写(CU) 水花",
        "sound": "瀑布轰鸣/水雾/鸟叫/回声",
        "ref": "王家卫《一代宗师》/李安《卧虎藏龙》/宫崎骏《幽灵公主》",
        "mood": "awe,anticipation,trust",
    },
    {
        "id": "nature_starry_night_sky",
        "name": "星空/夜空/月夜",
        "type": "NATURE_EXTERIOR",
        "sub": "sky",
        "desc": "星空/银河/月夜/极光/流星",
        "light": "月光主光 冷蓝 7000K + 星空微光, 静谧",
        "color": "深蓝/星空银/月白/极光彩",
        "lens": "广角(WS) 星空 / 中景(MS) 月下人物",
        "sound": "虫鸣/微风/夜鸟/寂静",
        "ref": "泰伦斯·马力克《生命之树》/塔可夫斯基《镜子》/是枝裕和《步履不停》",
        "mood": "awe,loneliness,longing",
    },
    {
        "id": "nature_rain_storm",
        "name": "雨夜/暴雨/闪电",
        "type": "NATURE_EXTERIOR",
        "sub": "rain",
        "desc": "暴雨/雷电/雨夜街道/泥泞",
        "light": "闪电瞬时强光 + 雨夜暗调, 戏剧化",
        "color": "冷蓝/青灰/闪电白/偶尔暖黄路灯",
        "lens": "广角(WS) 街道 / 中近景(MCU) 雨中人物",
        "sound": "雨声/雷声/积水/伞声",
        "ref": "王家卫《重庆森林》/诺兰《黑暗骑士》/奉俊昊《杀人回忆》",
        "mood": "sadness,longing,fear",
    },
    {
        "id": "nature_snow_winter_street",
        "name": "雪夜/冬日/雪景",
        "type": "NATURE_EXTERIOR",
        "sub": "snow",
        "desc": "雪景/雪夜/雪地/枯树/脚印",
        "light": "月光反射 冷白 + 路灯暖黄, 静谧",
        "color": "雪白/天蓝/枯枝灰/路灯黄",
        "lens": "广角(WS) 雪景 / 中景(MS) 雪中人物",
        "sound": "踩雪/风雪/寂静/远处钟声",
        "ref": "王家卫《一代宗师》/陈凯歌《妖猫传》/黑泽明《梦》",
        "mood": "loneliness,longing,nostalgia",
    },
    {
        "id": "nature_autumn_leaves",
        "name": "秋日/红叶/落叶",
        "type": "NATURE_EXTERIOR",
        "sub": "autumn",
        "desc": "红叶/黄叶/落叶/秋日远山/收获",
        "light": "黄昏侧光 30 度, 暖橙 2700K",
        "color": "红/橙/黄/枯枝棕/远山蓝",
        "lens": "全景(FS) 秋林 / 中近景(MCU) 落叶下人物",
        "sound": "落叶/风/鸟鸣/远处收割",
        "ref": "王家卫《花样年华》/侯孝贤《刺客聂隐娘》/是枝裕和《步履不停》",
        "mood": "nostalgia,warm_regret,longing",
    },
    {
        "id": "nature_cherry_blossom",
        "name": "樱花/春日/花海",
        "type": "NATURE_EXTERIOR",
        "sub": "spring",
        "desc": "樱花/桃花/油菜花/春日暖阳",
        "light": "晨光 4000K 暖白 + 蓝天通透",
        "color": "粉/白/嫩绿/天蓝",
        "lens": "全景(FS) 花海 / 中近景(MCU) 花下人物",
        "sound": "花瓣/鸟鸣/远处溪流/微风",
        "ref": "岩井俊二《情书》/侯孝贤《最好的时光》/王家卫《花样年华》",
        "mood": "tenderness,nostalgia,trust",
    },
    {
        "id": "nature_volcano_lava",
        "name": "火山/熔岩/末日景观",
        "type": "NATURE_EXTERIOR",
        "sub": "volcano",
        "desc": "火山喷发/熔岩流/末日山景/火山灰",
        "light": "熔岩炽热 1800K + 火山灰散射, 末日感",
        "color": "熔岩橙红/灰黑/硫磺黄/暗处深红",
        "lens": "广角(WS) 火山 / 中景(MS) 熔岩流",
        "sound": "低频轰鸣/岩浆嘶嘶/远处雷声",
        "ref": "宫崎骏《风之谷》/丹尼斯·维伦纽瓦《降临》/库布里克《2001太空漫游》",
        "mood": "fear,awe,anticipation",
    },
    {
        "id": "nature_aurora_polar",
        "name": "极光/极地/雪原",
        "type": "NATURE_EXTERIOR",
        "sub": "polar",
        "desc": "极光/极地/雪原/冰川/极昼极夜",
        "light": "极光冷彩 8000K + 雪地反光, 神秘",
        "color": "极光绿/紫/雪白/天蓝",
        "lens": "广角(WS) 极光 / 中景(MS) 极地人物",
        "sound": "风声/远处冰川断裂/极地寂静",
        "ref": "王家卫《一代宗师》/泰伦斯·马力克《生命之树》/诺兰《星际穿越》",
        "mood": "awe,loneliness,trust",
    },
    {
        "id": "nature_volcanic_island",
        "name": "热带海岛/椰林/沙滩",
        "type": "NATURE_EXTERIOR",
        "sub": "island",
        "desc": "热带海岛/椰林/白沙/碧海/小木屋",
        "light": "强烈顶光 + 黄昏金红, 热带氛围",
        "color": "碧海蓝/椰绿/白沙/夕阳橙",
        "lens": "广角(WS) 海岛 / 中景(MS) 椰林下人物",
        "sound": "海浪/椰叶/鸟叫/远处船笛",
        "ref": "王家卫《春光乍泄》/宫崎骏《悬崖上的金鱼姬》/韦斯·安德森《水中生活》",
        "mood": "tenderness,trust,warm_regret",
    },
    {
        "id": "nature_ancient_tree",
        "name": "古树/神木/千年榕",
        "type": "NATURE_EXTERIOR",
        "sub": "ancient_tree",
        "desc": "千年古树/神木/老榕树/树洞/盘根",
        "light": "树缝光斑 + 顶光散射, 神性",
        "color": "墨绿/苔藓/树皮棕/光斑金",
        "lens": "大全景(EWS) 古树 / 中景(MS) 树下人物",
        "sound": "树叶/鸟鸣/远处风/寂静",
        "ref": "宫崎骏《幽灵公主》/陈凯歌《妖猫传》/黑泽明《梦》",
        "mood": "awe,trust,anticipation",
    },
    {
        "id": "nature_bamboo_forest",
        "name": "竹林/竹海",
        "type": "NATURE_EXTERIOR",
        "sub": "bamboo",
        "desc": "竹林/竹海/竹影/晨雾/竹叶",
        "light": "晨雾散射 + 竹影斑驳, 东方意境",
        "color": "竹绿/晨雾白/竹影灰/光斑金",
        "lens": "全景(FS) 竹林 / 中景(MS) 竹下比武",
        "sound": "竹叶沙沙/风/远处鸟/寂静",
        "ref": "王家卫《一代宗师》/李安《卧虎藏龙》/张艺谋《英雄》",
        "mood": "trust,anticipation,awe",
    },
    {
        "id": "nature_meadow_wildflower",
        "name": "野花草地/山间小道",
        "type": "NATURE_EXTERIOR",
        "sub": "meadow",
        "desc": "野花草地/山间小道/远山/蝴蝶",
        "light": "上午顶光 5000K + 草丛光斑, 清新",
        "color": "嫩绿/野花彩/远山蓝/天蓝",
        "lens": "全景(FS) 草地 / 中近景(MCU) 花下人物",
        "sound": "虫鸣/鸟叫/微风/远处溪流",
        "ref": "是枝裕和《步履不停》/泰伦斯·马力克《天堂的日子》/小津安二郎《东京物语》",
        "mood": "warm_regret,tenderness,nostalgia",
    },

    # ============================================================
    # 类别 3: 实景外景 (URBAN_EXTERIOR) - 25 个
    # ============================================================
    {
        "id": "urban_hk_neon_street",
        "name": "香港霓虹街道 (重庆大厦/庙街)",
        "type": "URBAN_EXTERIOR",
        "sub": "hk_neon",
        "desc": "香港旧街/重庆大厦/庙街/霓虹招牌/小巴",
        "light": "霓虹主光 (红/绿/蓝) 3200K + 雨夜反光, 标志王家卫",
        "color": "霓虹红/绿/蓝/招牌黄, 高饱和",
        "lens": "广角(WS) 街道 / 中景(MS) 雨中人物",
        "sound": "粤语音乐/小巴/雨声/霓虹电流",
        "ref": "王家卫《重庆森林》/王家卫《花样年华》/陈果《香港制造》",
        "mood": "loneliness,longing,anticipation",
    },
    {
        "id": "urban_sh_liaison_alley",
        "name": "上海弄堂/巷子",
        "type": "URBAN_EXTERIOR",
        "sub": "sh_alley",
        "desc": "上海弄堂/巷子/老虎窗/晾衣杆/石库门",
        "light": "黄昏暖橙 + 巷子阴影, 怀旧",
        "color": "青灰砖墙/石库门红/晾衣彩",
        "lens": "全景(FS) 弄堂 / 中景(MS) 巷中人物",
        "sound": "上海话/自行车铃/远处叫卖/弄堂回声",
        "ref": "王家卫《花样年华》/侯孝贤《海上花》/程耳《罗曼蒂克消亡史》",
        "mood": "nostalgia,longing,warm_regret",
    },
    {
        "id": "urban_tokyo_shinjuku",
        "name": "东京新宿/涉谷十字路口",
        "type": "URBAN_EXTERIOR",
        "sub": "tokyo_street",
        "desc": "东京新宿/涉谷/歌舞伎町/十字路口/居酒屋",
        "light": "霓虹招牌 + 路灯 + 雨夜反光",
        "color": "霓虹彩/柏油路/居酒屋灯笼红",
        "lens": "广角(WS) 十字路口 / 中近景(MCU) 路人",
        "sound": "日语/电车铃/居酒屋嘈杂/雨",
        "ref": "是枝裕和《无人知晓》/岩井俊二《燕尾蝶》/小津安二郎《东京物语》",
        "mood": "loneliness,anticipation,longing",
    },
    {
        "id": "urban_paris_eiffel",
        "name": "巴黎/铁塔/香榭丽舍",
        "type": "URBAN_EXTERIOR",
        "sub": "paris",
        "desc": "巴黎街头/铁塔/咖啡馆/塞纳河/香榭丽舍",
        "light": "晨光 4500K + 黄昏金红, 浪漫",
        "color": "奥斯曼米黄/铁塔深灰/塞纳蓝",
        "lens": "广角(WS) 铁塔 / 中景(MS) 咖啡馆",
        "sound": "法语/咖啡馆音乐/塞纳河/街头艺人",
        "ref": "诺兰《盗梦空间》/特吕弗《四百击》/让-皮埃尔·热内《天使爱美丽》",
        "mood": "tenderness,trust,warm_regret",
    },
    {
        "id": "urban_ny_yellow_taxi",
        "name": "纽约街头/时代广场/出租车",
        "type": "URBAN_EXTERIOR",
        "sub": "ny",
        "desc": "纽约时代广场/黄色出租车/百老汇/中央公园",
        "light": "霓虹彩光 + 路灯 + 雨夜反光",
        "color": "霓虹彩/黄色出租车/百老汇",
        "lens": "广角(WS) 时代广场 / 中景(MS) 出租车",
        "sound": "英语/出租车鸣笛/百老汇音乐",
        "ref": "伍迪·艾伦《曼哈顿》/马丁·斯科塞斯《出租车司机》/斯派克·李《为所应为》",
        "mood": "anticipation,loneliness,trust",
    },
    {
        "id": "urban_london_brick",
        "name": "伦敦/红砖/泰晤士河",
        "type": "URBAN_EXTERIOR",
        "sub": "london",
        "desc": "伦敦街头/红砖建筑/泰晤士河/大本钟/雾",
        "light": "阴天散射 5500K + 路灯, 阴郁",
        "color": "红砖/泰晤士灰/雾白",
        "lens": "广角(WS) 大本钟 / 中景(MS) 街头",
        "sound": "英语/泰晤士河/大本钟/双层巴士",
        "ref": "诺兰《黑暗骑士》/诺兰《敦刻尔克》/希区柯克《后窗》",
        "mood": "anticipation,fear,trust",
    },
    {
        "id": "urban_la_sunset_blvd",
        "name": "洛杉矶/日落大道/棕榈",
        "type": "URBAN_EXTERIOR",
        "sub": "la",
        "desc": "洛杉矶日落大道/好莱坞/棕榈/霓虹",
        "light": "日落金红 2400K + 霓虹, 浮华",
        "color": "金红日落/霓虹彩/棕榈绿",
        "lens": "广角(WS) 日落大道 / 中景(MS) 霓虹下人物",
        "sound": "英语/警笛/酒吧音乐/棕榈叶",
        "ref": "大卫·芬奇《好莱坞往事》/比利·怀德《日落大道》/昆汀《好莱坞往事》",
        "mood": "desire,anticipation,sadness",
    },
    {
        "id": "urban_berlin_cold_war",
        "name": "柏林/冷战/东西分界",
        "type": "URBAN_EXTERIOR",
        "sub": "berlin",
        "desc": "柏林街头/冷战遗迹/东西分界/勃兰登堡门",
        "light": "阴天冷蓝 + 路灯, 压抑",
        "color": "水泥灰/警车蓝/红灯",
        "lens": "广角(WS) 勃兰登堡 / 中景(MS) 街头",
        "sound": "德语/警笛/电车/远处广播",
        "ref": "汤姆·提克威《罗拉快跑》/维姆·文德斯《柏林苍穹下》/斯派克·李《柏林苍穹下》",
        "mood": "anticipation,fear,trust",
    },
    {
        "id": "urban_market_bazaar",
        "name": "中东集市/巴扎/沙漠城",
        "type": "URBAN_EXTERIOR",
        "sub": "bazaar",
        "desc": "中东集市/巴扎/香料/地毯/驼队",
        "light": "强烈顶光 + 油灯侧光, 异域",
        "color": "香料色/地毯红/沙漠黄",
        "lens": "广角(WS) 集市 / 中近景(MCU) 商贩",
        "sound": "阿拉伯语/叫卖/驼铃/祷告",
        "ref": "大卫·里恩《阿拉伯的劳伦斯》/雷德利·斯科特《阿拉伯的劳伦斯》/王家卫《一代宗师》",
        "mood": "awe,anticipation,trust",
    },
    {
        "id": "urban_venice_canals",
        "name": "威尼斯/运河/贡多拉",
        "type": "URBAN_EXTERIOR",
        "sub": "venice",
        "desc": "威尼斯运河/贡多拉/叹息桥/圣马可",
        "light": "黄昏金红 + 水面反射, 浪漫",
        "color": "运河蓝/老建筑金黄/贡多拉黑",
        "lens": "广角(WS) 运河 / 中景(MS) 贡多拉",
        "sound": "意大利语/船桨/教堂钟声/水声",
        "ref": "贝纳尔多·贝托鲁奇《小活佛》/维斯康蒂《魂断威尼斯》/诺兰《信条》",
        "mood": "tenderness,longing,awe",
    },
    {
        "id": "urban_rome_ancient",
        "name": "罗马/古斗兽场/废墟",
        "type": "URBAN_EXTERIOR",
        "sub": "rome",
        "desc": "罗马街头/斗兽场/古废墟/万神殿/喷泉",
        "light": "强烈侧光 + 黄昏金红, 历史感",
        "color": "古石米黄/赭石/蓝/喷泉",
        "lens": "广角(WS) 斗兽场 / 中景(MS) 废墟",
        "sound": "意大利语/喷泉/教堂钟声/脚步声",
        "ref": "费里尼《甜蜜的生活》/罗伯托·贝尼尼《美丽人生》/伍迪·艾伦《爱罗马》",
        "mood": "warm_regret,anticipation,awe",
    },
    {
        "id": "urban_mumbai_slum",
        "name": "孟买/贫民窟/火车",
        "type": "URBAN_EXTERIOR",
        "sub": "mumbai",
        "desc": "孟买贫民窟/达拉维/火车/市集",
        "light": "顶光 + 贫民窟阴暗, 强烈对比",
        "color": "贫民窟灰/火车红/市集彩",
        "lens": "广角(WS) 贫民窟 / 中近景(MCU) 居民",
        "sound": "印地语/火车鸣笛/市集嘈杂",
        "ref": "丹尼·博伊尔《贫民窟的百万富翁》/萨蒂亚吉特·雷伊《阿普三部曲》",
        "mood": "sadness,anticipation,trust",
    },
    {
        "id": "urban_mexico_day_of_dead",
        "name": "墨西哥城/亡灵节",
        "type": "URBAN_EXTERIOR",
        "sub": "mexico",
        "desc": "墨西哥城/亡灵节/万寿菊/骷髅彩装",
        "light": "黄昏金红 + 烛光, 奇幻",
        "color": "万寿菊橙/紫/骷髅彩",
        "lens": "广角(WS) 亡灵节游行 / 中景(MS) 化妆人",
        "sound": "西班牙语/墨西哥音乐/鞭炮",
        "ref": "吉尔莫·德尔·托罗《Coco》/阿方索·卡隆《罗马》/伊纳里图《鸟人》",
        "mood": "tenderness,nostalgia,trust",
    },
    {
        "id": "urban_chengdu_old_street",
        "name": "成都/老街/茶馆",
        "type": "URBAN_EXTERIOR",
        "sub": "chengdu",
        "desc": "成都老街/茶馆/宽窄巷子/锦里",
        "light": "黄昏暖橙 + 茶馆灯笼, 巴适",
        "color": "青砖灰/红灯笼/茶色",
        "lens": "全景(FS) 茶馆 / 中景(MS) 茶客",
        "sound": "四川话/茶馆评书/鸟叫/远处麻将",
        "ref": "张艺谋《有话好好说》/贾樟柯《三峡好人》/王家卫《重庆森林》",
        "mood": "warm_regret,tenderness,nostalgia",
    },
    {
        "id": "urban_xian_terracotta",
        "name": "西安/古城墙/兵马俑",
        "type": "URBAN_EXTERIOR",
        "sub": "xian",
        "desc": "西安古城墙/兵马俑/钟楼/回民街",
        "light": "黄昏暖橙 + 城楼灯笼, 史诗",
        "color": "古城灰/红墙/灯笼红",
        "lens": "广角(WS) 城墙 / 中景(MS) 兵马俑",
        "sound": "秦腔/叫卖/钟声/脚步",
        "ref": "陈凯歌《刺秦》/张艺谋《英雄》/贾樟柯《天注定》",
        "mood": "awe,anticipation,trust",
    },
    {
        "id": "urban_kolkata_calcutta",
        "name": "加尔各答/老印度/市集",
        "type": "URBAN_EXTERIOR",
        "sub": "kolkata",
        "desc": "加尔各答老街/有轨电车/市集/恒河",
        "light": "黄昏金红 + 市集灯笼, 印度风情",
        "color": "黄/橙/红/市集彩",
        "lens": "广角(WS) 加尔各答 / 中景(MS) 市集",
        "sound": "孟加拉语/有轨电车/市集/祈祷",
        "ref": "萨蒂亚吉特·雷伊《大都市》/丹尼·博伊尔《贫民窟的百万富翁》",
        "mood": "awe,longing,sadness",
    },
    {
        "id": "urban_taipei_night_market",
        "name": "台北/夜市/小吃",
        "type": "URBAN_EXTERIOR",
        "sub": "taipei",
        "desc": "台北夜市/宁夏夜市/小吃摊/霓虹",
        "light": "夜市霓虹 + 摊贩灯泡, 烟火",
        "color": "霓虹红/绿/食物色",
        "lens": "广角(WS) 夜市 / 中近景(MCU) 摊贩",
        "sound": "闽南语/夜市叫卖/油锅/机车",
        "ref": "侯孝贤《最好的时光》/杨德昌《一一》/魏德圣《海角七号》",
        "mood": "warm_regret,tenderness,nostalgia",
    },
    {
        "id": "urban_kyoto_geisha",
        "name": "京都/祇园/艺伎",
        "type": "URBAN_EXTERIOR",
        "sub": "kyoto",
        "desc": "京都祇园/花见小路/艺伎/古建筑",
        "light": "黄昏暖橙 + 灯笼, 古韵",
        "color": "古木棕/和服红/灯笼暖橙",
        "lens": "全景(FS) 祇园 / 中景(MS) 艺伎",
        "sound": "三味线/木屐/远处寺庙钟",
        "ref": "是枝裕和《艺伎回忆录》/岩井俊二《情书》/小津安二郎《东京物语》",
        "mood": "nostalgia,longing,tenderness",
    },
    {
        "id": "urban_marrakech",
        "name": "摩洛哥/马拉喀什/沙漠城",
        "type": "URBAN_EXTERIOR",
        "sub": "marrakech",
        "desc": "摩洛哥马拉喀什/麦地那/红墙/集市",
        "light": "强烈顶光 + 麦地那暖红",
        "color": "摩洛哥红/赭石/沙漠黄",
        "lens": "广角(WS) 麦地那 / 中景(MS) 集市",
        "sound": "阿拉伯语/宣礼/市集嘈杂",
        "ref": "大卫·里恩《阿拉伯的劳伦斯》/雷德利·斯科特《阿拉伯的劳伦斯》",
        "mood": "awe,anticipation,trust",
    },
    {
        "id": "urban_moscow_red_square",
        "name": "莫斯科/红场/冬宫",
        "type": "URBAN_EXTERIOR",
        "sub": "moscow",
        "desc": "莫斯科红场/冬宫/洋葱顶教堂",
        "light": "冬日冷白 + 教堂金顶反射",
        "color": "红场红/冬宫彩/雪白",
        "lens": "广角(WS) 红场 / 中景(MS) 教堂",
        "sound": "俄语/钟声/远处军乐",
        "ref": "亚历山大·索科洛夫《俄罗斯方舟》/塔可夫斯基《镜子》",
        "mood": "awe,anticipation,trust",
    },
    {
        "id": "urban_istanbul_bosphorus",
        "name": "伊斯坦布尔/博斯普鲁斯",
        "type": "URBAN_EXTERIOR",
        "sub": "istanbul",
        "desc": "伊斯坦布尔/蓝色清真寺/博斯普鲁斯海峡",
        "light": "黄昏金红 + 海面反射, 神秘",
        "color": "蓝色清真寺/海峡蓝/金顶",
        "lens": "广角(WS) 博斯普鲁斯 / 中景(MS) 清真寺",
        "sound": "土耳其语/宣礼/船笛",
        "ref": "诺兰《信条》/费斯·阿金《在人生的另一边》",
        "mood": "awe,anticipation,trust",
    },
    {
        "id": "urban_chongqing_mountain",
        "name": "重庆/山城/雾",
        "type": "URBAN_EXTERIOR",
        "sub": "chongqing",
        "desc": "重庆山城/雾都/轻轨穿楼/火锅",
        "light": "雾天散射 5500K + 夜晚霓虹",
        "color": "灰/雾白/霓虹彩",
        "lens": "广角(WS) 山城 / 中景(MS) 雾中",
        "sound": "重庆话/火锅/轻轨/江轮",
        "ref": "王家卫《重庆森林》/张一白《好奇害死猫》/贾樟柯《三峡好人》",
        "mood": "loneliness,anticipation,warm_regret",
    },
    {
        "id": "urban_ibiza_white_town",
        "name": "伊比萨/白色小镇/地中海",
        "type": "URBAN_EXTERIOR",
        "sub": "ibiza",
        "desc": "地中海白色小镇/伊比萨/蓝白对比",
        "light": "强烈地中海阳光 + 海面反射",
        "color": "白色/地中海蓝/橄榄绿",
        "lens": "广角(WS) 小镇 / 中景(MS) 海边人物",
        "sound": "西班牙语/海浪/吉他",
        "ref": "路易斯·布努埃尔《泯灭天使》/阿莫斯·吉塔伊《切肤》",
        "mood": "tenderness,trust,joy",
    },
    {
        "id": "urban_rio_carnival",
        "name": "里约/嘉年华/基督山",
        "type": "URBAN_EXTERIOR",
        "sub": "rio",
        "desc": "里约热内卢/嘉年华/基督像/科帕卡巴纳",
        "light": "嘉年华彩光 + 基督山俯瞰",
        "color": "嘉年华彩/基督山绿/沙滩金",
        "lens": "广角(WS) 嘉年华 / 中景(MS) 桑巴",
        "sound": "葡萄牙语/桑巴/鼓/嘉年华",
        "ref": "费尔南多·梅雷莱斯《上帝之城》/卡门·米兰达《Carmen Miranda》",
        "mood": "joy,trust,tenderness",
    },
    {
        "id": "urban_cairo_pyramid",
        "name": "开罗/金字塔/沙漠",
        "type": "URBAN_EXTERIOR",
        "sub": "cairo",
        "desc": "开罗/金字塔/狮身人面像/尼罗河",
        "light": "沙漠强烈顶光 + 黄昏金红",
        "color": "沙漠金/金字塔石灰/尼罗河蓝",
        "lens": "广角(WS) 金字塔 / 中景(MS) 沙漠",
        "sound": "阿拉伯语/宣礼/沙漠风",
        "ref": "雷德利·斯科特《埃及艳后》/斯蒂文·索德伯格《辛德勒的名单》",
        "mood": "awe,anticipation,trust",
    },

    # ============================================================
    # 类别 4: 实景内景 (URBAN_INTERIOR) - 20 个
    # ============================================================
    {
        "id": "interior_teahouse_old",
        "name": "老茶馆/老酒馆",
        "type": "URBAN_INTERIOR",
        "sub": "teahouse",
        "desc": "老茶馆/老酒馆/八仙桌/长条凳/茶壶",
        "light": "暖黄吊灯 2700K + 窗光, 烟火气",
        "color": "木桌棕/茶色/红灯笼",
        "lens": "全景(FS) 茶馆 / 中景(MS) 茶客",
        "sound": "评书/茶壶/叫卖/远处鸟笼",
        "ref": "陈凯歌《霸王别姬》/张艺谋《有话好好说》/贾樟柯《三峡好人》",
        "mood": "warm_regret,nostalgia,tenderness",
    },
    {
        "id": "interior_bathhouse_japan",
        "name": "日本澡堂/温泉",
        "type": "URBAN_INTERIOR",
        "sub": "bathhouse",
        "desc": "日本澡堂/温泉/木桶/蒸汽/纸灯笼",
        "light": "蒸汽散射 2700K 暖橙 + 灯笼",
        "color": "木/蒸汽白/灯笼红",
        "lens": "全景(FS) 澡堂 / 中近景(MCU) 蒸汽中",
        "sound": "水流/蒸汽嘶嘶/远处木屐",
        "ref": "周星驰《功夫》/是枝裕和《步履不停》/岩井俊二《关于莉莉周的一切》",
        "mood": "tenderness,nostalgia,trust",
    },
    {
        "id": "interior_old_warehouse",
        "name": "旧仓库/工厂",
        "type": "URBAN_INTERIOR",
        "sub": "warehouse",
        "desc": "旧仓库/废弃工厂/钢架/破碎窗",
        "light": "破碎窗强光 + 暗部, 工业颓废",
        "color": "锈铁/水泥灰/破碎窗光",
        "lens": "广角(WS) 仓库 / 中景(MS) 钢架间",
        "sound": "回声/滴水/远处铁门/金属",
        "ref": "大卫·芬奇《七宗罪》/诺兰《蝙蝠侠》/丹尼斯·维伦纽瓦《银翼杀手2049》",
        "mood": "fear,anticipation,sadness",
    },
    {
        "id": "interior_old_lift_elevator",
        "name": "旧楼电梯/楼道",
        "type": "URBAN_INTERIOR",
        "sub": "lift",
        "desc": "旧楼电梯/楼道/磨砂玻璃/铁栅栏",
        "light": "楼道顶灯 冷白 + 电梯按钮光",
        "color": "铁栅栏/磨砂玻璃/楼道灰",
        "lens": "中近景(MCU) 电梯 / 全景(FS) 楼道",
        "sound": "电梯升降/楼道脚步/铁门",
        "ref": "奉俊昊《寄生虫》/王家卫《花样年华》/诺兰《盗梦空间》",
        "mood": "anticipation,fear,sadness",
    },
    {
        "id": "interior_old_classroom_china",
        "name": "老教室/老学堂",
        "type": "URBAN_INTERIOR",
        "sub": "classroom",
        "desc": "80-90 年代老教室/木桌木椅/黑板",
        "light": "窗光 4500K + 黑板反光",
        "color": "木质/旧墙/黑板墨绿",
        "lens": "全景(FS) 教室 / 中近景(MCU) 学生",
        "sound": "粉笔/翻书/远处铃声/操场",
        "ref": "贾樟柯《小武》/王小帅《我11》/姜文《阳光灿烂的日子》",
        "mood": "nostalgia,warm_regret,trust",
    },
    {
        "id": "interior_old_cinema",
        "name": "老电影院/大光明",
        "type": "URBAN_INTERIOR",
        "sub": "cinema",
        "desc": "老电影院/大光明/国泰/老上海影院",
        "light": "放映厅银幕光 + 装饰灯",
        "color": "金/红/装饰艺术派",
        "lens": "广角(WS) 放映厅 / 中景(MS) 观众",
        "sound": "胶片放映/观众低语/配乐",
        "ref": "王家卫《花样年华》/程耳《罗曼蒂克消亡史》/李安《色,戒》",
        "mood": "nostalgia,tenderness,longing",
    },
    {
        "id": "interior_old_library",
        "name": "老图书馆/老书店",
        "type": "URBAN_INTERIOR",
        "sub": "library",
        "desc": "老图书馆/旧书店/木质书架/高顶",
        "light": "顶光 + 桌灯 2700K 暖黄, 沉静",
        "color": "木质/书页/铜灯",
        "lens": "全景(FS) 书架 / 中景(MS) 桌前",
        "sound": "翻书/钟/远处脚步",
        "ref": "陈凯歌《妖猫传》/岩井俊二《情书》/是枝裕和《步履不停》",
        "mood": "trust,nostalgia,tenderness",
    },
    {
        "id": "interior_old_post_office",
        "name": "老邮局/电报局",
        "type": "URBAN_INTERIOR",
        "sub": "postoffice",
        "desc": "老邮局/电报局/木质柜台/打字机",
        "light": "顶光 + 窗光 4500K, 旧时光",
        "color": "木质/打字机绿/电报纸",
        "lens": "全景(FS) 邮局 / 中近景(MCU) 柜台",
        "sound": "打字机/邮票/盖章/电话铃",
        "ref": "王家卫《花样年华》/陈凯歌《霸王别姬》/侯孝贤《咖啡时光》",
        "mood": "nostalgia,longing,trust",
    },
    {
        "id": "interior_old_barbershop",
        "name": "老理发店/老式 barber",
        "type": "URBAN_INTERIOR",
        "sub": "barber",
        "desc": "老式理发店/老 barber shop/皮椅/转灯",
        "light": "转灯红蓝白 + 顶光, 怀旧",
        "color": "皮椅棕/转灯彩/镜面",
        "lens": "中近景(MCU) 椅子 / 全景(FS) 理发店",
        "sound": "剪刀/推子/收音机/喷水",
        "ref": "侯孝贤《童年往事》/陈凯歌《霸王别姬》/贾樟柯《山河故人》",
        "mood": "nostalgia,warm_regret,tenderness",
    },
    {
        "id": "interior_old_photo_studio",
        "name": "老照相馆/暗房",
        "type": "URBAN_INTERIOR",
        "sub": "photostudio",
        "desc": "老照相馆/暗房/红灯/药水/底片",
        "light": "暗房红灯 2200K + 照相顶光",
        "color": "暗红/底片/药水",
        "lens": "中近景(MCU) 暗房 / 特写(CU) 底片",
        "sound": "放大机/药水/快门",
        "ref": "王家卫《花样年华》/陈凯歌《霸王别姬》/侯孝贤《童年往事》",
        "mood": "nostalgia,longing,tenderness",
    },
    {
        "id": "interior_old_brothel_chinese",
        "name": "旧社会青楼/堂子",
        "type": "URBAN_INTERIOR",
        "sub": "old_brothel",
        "desc": "旧社会青楼/堂子/雕花床/红绸",
        "light": "红灯笼 + 烛光 2200K, 暧昧",
        "color": "红/金/紫绸/绣帘",
        "lens": "中景(MS) 厅堂 / 特写(CU) 烛光",
        "sound": "古琴/丝竹/夜风",
        "ref": "陈凯歌《霸王别姬》/张艺谋《金陵十三钗》/程耳《罗曼蒂克消亡史》",
        "mood": "longing,desire,sadness",
    },
    {
        "id": "interior_old_school_gym",
        "name": "老学校/操场/体育馆",
        "type": "URBAN_INTERIOR",
        "sub": "gym",
        "desc": "老学校/操场/体育馆/木质地板",
        "light": "顶光 + 窗光 4500K, 青春",
        "color": "木质/跑道红/操场绿",
        "lens": "广角(WS) 操场 / 中景(MS) 体育馆",
        "sound": "哨子/跑步/篮球/远处广播",
        "ref": "姜文《阳光灿烂的日子》/王小帅《我11》/贾樟柯《站台》",
        "mood": "warm_regret,nostalgia,trust",
    },
    {
        "id": "interior_old_food_market",
        "name": "老菜市场/老集市",
        "type": "URBAN_INTERIOR",
        "sub": "market",
        "desc": "老菜市场/海鲜/蔬菜/老式摊位",
        "light": "顶灯 + 自然光, 烟火",
        "color": "菜色/摊位彩/水泥地",
        "lens": "广角(WS) 菜场 / 中近景(MCU) 摊贩",
        "sound": "叫卖/秤/砧板/喷雾",
        "ref": "是枝裕和《步履不停》/侯孝贤《童年往事》/贾樟柯《山河故人》",
        "mood": "warm_regret,tenderness,nostalgia",
    },
    {
        "id": "interior_old_chinese_yard",
        "name": "老北京四合院",
        "type": "URBAN_INTERIOR",
        "sub": "siheyuan",
        "desc": "老北京四合院/影壁/垂花门/老槐树",
        "light": "天光 + 院中老灯 2700K, 古韵",
        "color": "青砖灰/朱红/老槐绿",
        "lens": "全景(FS) 四合院 / 中景(MS) 院中",
        "sound": "鸟笼/京剧/远处叫卖/树叶",
        "ref": "陈凯歌《霸王别姬》/张艺谋《活着》/姜文《阳光灿烂的日子》",
        "mood": "nostalgia,warm_regret,trust",
    },
    {
        "id": "interior_old_brothel_taipei",
        "name": "台北老酒家/茶室",
        "type": "URBAN_INTERIOR",
        "sub": "taipei_bar",
        "desc": "台北老酒家/茶室/台式怀旧/老歌",
        "light": "暖黄霓虹 + 红灯笼 2200K, 怀旧",
        "color": "霓虹红/绿/木质",
        "lens": "中景(MS) 茶室 / 特写(CU) 老歌本",
        "sound": "闽南语老歌/麻将/叫卖",
        "ref": "侯孝贤《最好的时光》/杨德昌《牯岭街少年杀人事件》/魏德圣《海角七号》",
        "mood": "nostalgia,longing,warm_regret",
    },
    {
        "id": "interior_old_operahouse",
        "name": "老戏园子/戏台",
        "type": "URBAN_INTERIOR",
        "sub": "opera",
        "desc": "老戏园子/戏台/雕花戏台/包厢",
        "light": "舞台强光 + 观众席暗, 戏剧化",
        "color": "金/红/雕花彩",
        "lens": "广角(WS) 戏台 / 中近景(MCU) 包厢",
        "sound": "京锣/胡琴/叫好/观众低语",
        "ref": "陈凯歌《霸王别姬》/张艺谋《活着》/费穆《小城之春》",
        "mood": "awe,nostalgia,anticipation",
    },
    {
        "id": "interior_modern_coffee",
        "name": "现代咖啡馆/独立书店",
        "type": "URBAN_INTERIOR",
        "sub": "coffee",
        "desc": "现代咖啡馆/独立书店/木质/工业风",
        "light": "暖黄吊灯 2700K + 窗光 4500K, 文艺",
        "color": "木质/咖啡色/工业风金属",
        "lens": "全景(FS) 咖啡馆 / 中近景(MCU) 桌前",
        "sound": "咖啡机/爵士/低声交谈/翻书",
        "ref": "王家卫《花样年华》/是枝裕和《步履不停》/让-皮埃尔·热内《天使爱美丽》",
        "mood": "tenderness,trust,warm_regret",
    },
    {
        "id": "interior_modern_gym",
        "name": "现代健身房",
        "type": "URBAN_INTERIOR",
        "sub": "gym",
        "desc": "现代健身房/器械/镜子/汗味",
        "light": "冷白 LED 5500K + 镜面反射",
        "color": "金属银/镜面/器械黑",
        "lens": "广角(WS) 健身房 / 中近景(MCU) 健身",
        "sound": "器械/音乐/呼吸",
        "ref": "大卫·芬奇《搏击俱乐部》/丹尼·博伊尔《贫民窟的百万富翁》",
        "mood": "anticipation,anger,trust",
    },
    {
        "id": "interior_modern_subway",
        "name": "现代地铁站",
        "type": "URBAN_INTERIOR",
        "sub": "subway",
        "desc": "现代地铁站/站台/扶梯/广告",
        "light": "冷白 LED 5500K + 列车灯光",
        "color": "水泥/不锈钢/广告彩",
        "lens": "广角(WS) 站台 / 中近景(MCU) 候车",
        "sound": "列车进站/广播/人群嘈杂",
        "ref": "奉俊昊《寄生虫》/是枝裕和《无人知晓》/岩井俊二《燕尾蝶》",
        "mood": "loneliness,anticipation,longing",
    },
    {
        "id": "interior_modern_office_glass",
        "name": "现代玻璃办公室",
        "type": "URBAN_INTERIOR",
        "sub": "office",
        "desc": "现代玻璃办公室/工位/会议室/茶水间",
        "light": "冷白 LED + 落地窗自然光",
        "color": "玻璃/银灰/品牌色",
        "lens": "广角(WS) 办公室 / 中景(MS) 会议室",
        "sound": "键盘/电话/打印机/空调",
        "ref": "诺兰《盗梦空间》/大卫·芬奇《社交网络》/丹尼斯·维伦纽瓦《银翼杀手2049》",
        "mood": "anticipation,trust,anticipation",
    },

    # ============================================================
    # 类别 5: 影片拍摄外景 (PERIOD_FILM_LOCATION) - 15 个
    # ============================================================
    {
        "id": "period_hengdian_qing",
        "name": "横店明清宫/紫禁城",
        "type": "PERIOD_FILM_LOCATION",
        "sub": "hengdian_qing",
        "desc": "横店明清宫/紫禁城/红墙黄瓦",
        "light": "顶光 + 宫灯 2200K, 宫廷",
        "color": "朱红/琉璃黄/玉石白",
        "lens": "广角(WS) 宫殿 / 中近景(MCU) 宫门",
        "sound": "钟鼓/太监传报/脚步/朝臣",
        "ref": "陈凯歌《刺秦》/张艺谋《英雄》/贝纳尔多·贝托鲁奇《末代皇帝》",
        "mood": "awe,anticipation,trust",
    },
    {
        "id": "period_hengdian_tang",
        "name": "横店唐城/长安",
        "type": "PERIOD_FILM_LOCATION",
        "sub": "hengdian_tang",
        "desc": "横店唐城/长安城/大明宫/西市",
        "light": "顶光 + 灯笼 2200K, 大唐盛世",
        "color": "朱红/金/青/唐三彩",
        "lens": "广角(WS) 长安城 / 中景(MS) 街头",
        "sound": "唐乐/叫卖/马蹄/朝臣",
        "ref": "陈凯歌《妖猫传》/张艺谋《满城尽带黄金甲》/李少红《大明宫词》",
        "mood": "awe,anticipation,trust",
    },
    {
        "id": "period_hengdian_song",
        "name": "横店宋城/清明上河图",
        "type": "PERIOD_FILM_LOCATION",
        "sub": "hengdian_song",
        "desc": "横店宋城/清明上河图/汴京",
        "light": "晨光 4500K + 灯笼, 汴京繁华",
        "color": "青砖灰/红/木",
        "lens": "广角(WS) 汴京 / 中景(MS) 街头",
        "sound": "市集/宋词/叫卖/船桨",
        "ref": "张纪中《射雕英雄传》/李少红《大明宫词》/王家卫《一代宗师》",
        "mood": "warm_regret,anticipation,trust",
    },
    {
        "id": "period_hengdian_30s",
        "name": "民国上海滩/老上海",
        "type": "PERIOD_FILM_LOCATION",
        "sub": "hengdian_30s",
        "desc": "民国上海滩/老上海/百乐门/弄堂",
        "light": "霓虹 + 黄包车灯 2700K, 浮华",
        "color": "霓虹红/绿/老上海",
        "lens": "广角(WS) 老上海 / 中景(MS) 街头",
        "sound": "爵士/百乐门舞曲/黄包车",
        "ref": "王家卫《花样年华》/程耳《罗曼蒂克消亡史》/李安《色,戒》",
        "mood": "nostalgia,longing,desire",
    },
    {
        "id": "period_hengdian_war",
        "name": "民国战时/重庆/延安",
        "type": "PERIOD_FILM_LOCATION",
        "sub": "hengdian_war",
        "desc": "民国战时/重庆陪都/延安/窑洞",
        "light": "战时阴冷 + 油灯 2200K, 沉重",
        "color": "土黄/灰/油灯暖橙",
        "lens": "广角(WS) 战时 / 中近景(MCU) 窑洞",
        "sound": "警报/脚步/广播/远处炮火",
        "ref": "陈凯歌《霸王别姬》/姜文《让子弹飞》/张艺谋《金陵十三钗》",
        "mood": "sadness,anticipation,fear",
    },
    {
        "id": "period_hengdian_culture_revolution",
        "name": "文革时期/红色海洋",
        "type": "PERIOD_FILM_LOCATION",
        "sub": "hengdian_cr",
        "desc": "文革时期/红色海洋/大字报/绿军装",
        "light": "强烈侧光 + 革命红光, 红色",
        "color": "红/绿军装/标语",
        "lens": "广角(WS) 红色海洋 / 中景(MS) 游行",
        "sound": "革命歌曲/广播/口号/脚步",
        "ref": "陈凯歌《霸王别姬》/张艺谋《活着》/姜文《阳光灿烂的日子》",
        "mood": "sadness,anger,anticipation",
    },
    {
        "id": "period_hengdian_ancient_rome",
        "name": "古罗马斗兽场",
        "type": "PERIOD_FILM_LOCATION",
        "sub": "rome_colosseum",
        "desc": "古罗马斗兽场/万神殿/罗马广场",
        "light": "强烈侧光 + 黄昏金红 2700K, 史诗",
        "color": "古石米黄/赭石/金",
        "lens": "广角(WS) 斗兽场 / 中景(MS) 广场",
        "sound": "拉丁语/角斗/人群/铁器",
        "ref": "雷德利·斯科特《角斗士》/斯坦利·库布里克《斯巴达克斯》",
        "mood": "awe,anticipation,fear",
    },
    {
        "id": "period_hengdian_ancient_egypt",
        "name": "古埃及/卡纳克",
        "type": "PERIOD_FILM_LOCATION",
        "sub": "egypt",
        "desc": "古埃及/卡纳克神庙/狮身人面像/金字塔",
        "light": "沙漠强烈侧光 + 黄昏金红",
        "color": "古石米黄/赭石/沙漠金",
        "lens": "广角(WS) 神庙 / 中景(MS) 法老",
        "sound": "古埃及语/祭祀/远处沙漠风",
        "ref": "雷德利·斯科特《埃及艳后》/斯蒂文·索德伯格《辛德勒的名单》",
        "mood": "awe,anticipation,trust",
    },
    {
        "id": "period_hengdian_medieval_europe",
        "name": "中世纪欧洲城堡",
        "type": "PERIOD_FILM_LOCATION",
        "sub": "medieval",
        "desc": "中世纪欧洲城堡/骑士/城墙",
        "light": "火把 + 阴天 5500K, 战争",
        "color": "石灰/铁灰/火把橙",
        "lens": "广角(WS) 城堡 / 中近景(MCU) 骑士",
        "sound": "拉丁语/铁器/马蹄/远处号角",
        "ref": "梅尔·吉布森《勇敢的心》/雷德利·斯科特《天国王朝》",
        "mood": "anticipation,fear,trust",
    },
    {
        "id": "period_hengdian_victorian",
        "name": "维多利亚时代/工业革命",
        "type": "PERIOD_FILM_LOCATION",
        "sub": "victorian",
        "desc": "维多利亚时代伦敦/工业革命/雾都",
        "light": "煤气灯 + 雾 5500K, 阴沉",
        "color": "雾灰/铁黑/煤气灯暖橙",
        "lens": "广角(WS) 工业伦敦 / 中近景(MCU) 工厂",
        "sound": "蒸汽机/马车/工厂/远处钟声",
        "ref": "马丁·斯科塞斯《雨果》/蒂姆·伯顿《 Sweeney Todd》",
        "mood": "sadness,anticipation,fear",
    },
    {
        "id": "period_hengdian_japan_feudal",
        "name": "日本战国/江户",
        "type": "PERIOD_FILM_LOCATION",
        "sub": "japan_feudal",
        "desc": "日本战国/江户城/武士/樱花",
        "light": "晨昏侧光 + 灯笼, 武士道",
        "color": "古木/樱花/盔甲黑",
        "lens": "广角(WS) 城 / 中近景(MCU) 武士",
        "sound": "日语/太鼓/刀剑/远处三味线",
        "ref": "黑泽明《七武士》/黑泽明《乱》/是枝裕和《影武者》",
        "mood": "awe,anticipation,trust",
    },
    {
        "id": "period_hengdian_ancient_india",
        "name": "古印度/泰姬陵",
        "type": "PERIOD_FILM_LOCATION",
        "sub": "india",
        "desc": "古印度/泰姬陵/恒河/佛教石窟",
        "light": "强烈侧光 + 黄昏金红, 神性",
        "color": "古石白/赭石/金",
        "lens": "广角(WS) 泰姬陵 / 中景(MS) 石窟",
        "sound": "梵语/诵经/风铃/远处恒河",
        "ref": "萨蒂亚吉特·雷伊《阿普三部曲》/贝纳尔多·贝托鲁奇《小活佛》",
        "mood": "awe,anticipation,trust",
    },
    {
        "id": "period_hengdian_ancient_meso",
        "name": "古玛雅/阿兹特克",
        "type": "PERIOD_FILM_LOCATION",
        "sub": "meso",
        "desc": "古玛雅/阿兹特克金字塔/丛林神庙",
        "light": "丛林强光 + 神庙阴影, 神秘",
        "color": "古石/丛林绿/金",
        "lens": "广角(WS) 神庙 / 中景(MS) 祭祀",
        "sound": "玛雅语/祭祀/丛林鸟/鼓",
        "ref": "梅尔·吉布森《启示录》/丹尼斯·维伦纽瓦《降临》",
        "mood": "awe,fear,anticipation",
    },
    {
        "id": "period_hengdian_ancient_persia",
        "name": "古波斯/波斯波利斯",
        "type": "PERIOD_FILM_LOCATION",
        "sub": "persia",
        "desc": "古波斯/波斯波利斯/空中花园",
        "light": "沙漠侧光 + 蓝金, 神秘",
        "color": "蓝瓷砖/金/赭石",
        "lens": "广角(WS) 波斯波利斯 / 中景(MS) 空中花园",
        "sound": "古波斯语/风/远处集市",
        "ref": "雷德利·斯科特《天国王朝》/大卫·里恩《阿拉伯的劳伦斯》",
        "mood": "awe,anticipation,trust",
    },
    {
        "id": "period_hengdian_ancient_greece",
        "name": "古希腊/雅典卫城",
        "type": "PERIOD_FILM_LOCATION",
        "sub": "greece",
        "desc": "古希腊/雅典卫城/帕特农/爱琴海",
        "light": "地中海强光 + 大理石反光",
        "color": "大理石白/爱琴海蓝/金",
        "lens": "广角(WS) 卫城 / 中景(MS) 帕特农",
        "sound": "古希腊语/海浪/远处祭祀",
        "ref": "奥利弗·斯通《亚历山大大帝》/扎克·施奈德《诸神之战》",
        "mood": "awe,anticipation,trust",
    },

    # ============================================================
    # 类别 6: 虚拟场景 (VIRTUAL_SCENE) - 10 个
    # ============================================================
    {
        "id": "virtual_cyberpunk_city",
        "name": "赛博朋克未来都市",
        "type": "VIRTUAL_SCENE",
        "sub": "cyberpunk",
        "desc": "赛博朋克未来都市/霓虹/飞行器/全息",
        "light": "霓虹全息 + 雨夜反射, 科幻",
        "color": "霓虹彩/黑/电子蓝紫",
        "lens": "广角(WS) 都市 / 中近景(MCU) 街头",
        "sound": "电子乐/飞行器/全息/雨",
        "ref": "丹尼斯·维伦纽瓦《银翼杀手2049》/雷德利·斯科特《银翼杀手》/押井守《攻壳机动队》",
        "mood": "anticipation,fear,loneliness",
    },
    {
        "id": "virtual_underwater_palace",
        "name": "水下宫殿/海底世界",
        "type": "VIRTUAL_SCENE",
        "sub": "underwater",
        "desc": "水下宫殿/海底龙宫/珊瑚/水母",
        "light": "水下散射蓝绿 8000K + 阳光透射",
        "color": "海蓝/珊瑚彩/水母透明",
        "lens": "广角(WS) 海底 / 中景(MS) 宫殿",
        "sound": "水流/气泡/远处鲸歌",
        "ref": "宫崎骏《悬崖上的金鱼姬》/詹姆斯·卡梅隆《阿凡达》/陈凯歌《妖猫传》",
        "mood": "awe,trust,tenderness",
    },
    {
        "id": "virtual_space_station",
        "name": "太空站/飞船",
        "type": "VIRTUAL_SCENE",
        "sub": "space",
        "desc": "太空站/飞船/失重/星空",
        "light": "太空冷白 6000K + 仪表光",
        "color": "金属银/太空黑/电子蓝",
        "lens": "广角(WS) 太空 / 中景(MS) 飞船内",
        "sound": "电子音/失重/通讯/空气循环",
        "ref": "库布里克《2001太空漫游》/诺兰《星际穿越》/丹尼斯·维伦纽瓦《降临》",
        "mood": "awe,fear,anticipation",
    },
    {
        "id": "virtual_alien_planet",
        "name": "外星球/异星",
        "type": "VIRTUAL_SCENE",
        "sub": "alien",
        "desc": "外星球/异星/双星天空/异形生物",
        "light": "异星双源光 6000-8000K",
        "color": "异星彩/外星植物/岩石",
        "lens": "广角(WS) 异星 / 中景(MS) 探险",
        "sound": "异星风/外星生物/通讯干扰",
        "ref": "詹姆斯·卡梅隆《阿凡达》/丹尼斯·维伦纽瓦《降临》/库布里克《2001太空漫游》",
        "mood": "awe,fear,anticipation",
    },
    {
        "id": "virtual_magic_realm",
        "name": "魔法世界/中土世界",
        "type": "VIRTUAL_SCENE",
        "sub": "fantasy",
        "desc": "中土世界/魔法森林/城堡/精灵",
        "light": "魔法光 6000K + 星光",
        "color": "魔法彩/绿/金/银",
        "lens": "广角(WS) 魔法世界 / 中近景(MCU) 城堡",
        "sound": "魔法音/远处号角/精灵歌声",
        "ref": "彼得·杰克逊《指环王》/宫崎骏《幽灵公主》/陈凯歌《妖猫传》",
        "mood": "awe,anticipation,trust",
    },
    {
        "id": "virtual_post_apocalyptic",
        "name": "末日废土/核冬天",
        "type": "VIRTUAL_SCENE",
        "sub": "apocalypse",
        "desc": "末日废土/核冬天/废墟/辐射",
        "light": "末日灰白 + 辐射光, 绝望",
        "color": "灰/辐射绿/锈红",
        "lens": "广角(WS) 废土 / 中景(MS) 废墟",
        "sound": "废土风/远处机械/沉默",
        "ref": "乔治·米勒《疯狂的麦克斯》/丹尼斯·维伦纽瓦《银翼杀手2049》",
        "mood": "fear,sadness,anticipation",
    },
    {
        "id": "virtual_steampunk",
        "name": "蒸汽朋克世界",
        "type": "VIRTUAL_SCENE",
        "sub": "steampunk",
        "desc": "蒸汽朋克/齿轮/铜管/飞艇",
        "light": "煤气灯 + 蒸汽散射, 复古未来",
        "color": "铜/铁/煤气灯暖橙",
        "lens": "广角(WS) 蒸汽城 / 中景(MS) 飞艇",
        "sound": "蒸汽/齿轮/飞艇/远处钟声",
        "ref": "马丁·斯科塞斯《雨果》/宫崎骏《哈尔的移动城堡》",
        "mood": "anticipation,trust,awe",
    },
    {
        "id": "virtual_matrix_digital",
        "name": "矩阵/数字空间",
        "type": "VIRTUAL_SCENE",
        "sub": "matrix",
        "desc": "矩阵/数字空间/绿色代码/虚拟",
        "light": "数字冷绿 + 全息光",
        "color": "数字绿/黑/电子蓝",
        "lens": "广角(WS) 数字空间 / 中近景(MCU) 角色",
        "sound": "电子雨/代码/远处理信号",
        "ref": "沃卓斯基姐妹《黑客帝国》/诺兰《盗梦空间》/丹尼斯·维伦纽瓦《银翼杀手2049》",
        "mood": "anticipation,fear,trust",
    },
    {
        "id": "virtual_dystopia_1984",
        "name": "反乌托邦/1984",
        "type": "VIRTUAL_SCENE",
        "sub": "dystopia",
        "desc": "反乌托邦/老大哥/监控/极权",
        "light": "阴冷 + 监视器冷白, 压抑",
        "color": "灰/监控冷白/老大哥海报红",
        "lens": "广角(WS) 极权城 / 中景(MS) 监视",
        "sound": "广播/监视器/脚步/远处警报",
        "ref": "迈克尔·莱德福德《1984》/乔治·奥威尔《1984》",
        "mood": "fear,anticipation,sadness",
    },
    {
        "id": "virtual_zoo_creature",
        "name": "虚拟生物/奇幻生物",
        "type": "VIRTUAL_SCENE",
        "sub": "creature",
        "desc": "虚拟生物/恐龙/巨兽/奇幻生物",
        "light": "自然光 + 神秘光, 奇幻",
        "color": "生物色/绿/灰/彩",
        "lens": "广角(WS) 生物 / 中近景(MCU) 探险",
        "sound": "生物吼叫/自然/远处理信号",
        "ref": "史蒂文·斯皮尔伯格《侏罗纪公园》/宫崎骏《幽灵公主》",
        "mood": "awe,fear,anticipation",
    },

    # ============================================================
    # 类别 7: 心理空间 (PSYCHE_SPACE) - 8 个 (扩展)
    # ============================================================
    {
        "id": "psyche_loneliness_room",
        "name": "孤独心理空间 (空旷房间)",
        "type": "PSYCHE_SPACE",
        "sub": "loneliness",
        "desc": "极简空房间, 孤独心理外化, 一束顶光",
        "light": "单束顶光 + 周围黑暗, 聚焦",
        "color": "白墙/灰/单色光",
        "lens": "中景(MS) 人物 / 特写(CU) 表情",
        "sound": "回声/钟摆/呼吸",
        "ref": "王家卫《花样年华》/塔可夫斯基《镜子》/诺兰《盗梦空间》",
        "mood": "loneliness,sadness,longing",
    },
    {
        "id": "psyche_madness_corridor",
        "name": "疯狂心理空间 (无限走廊)",
        "type": "PSYCHE_SPACE",
        "sub": "madness",
        "desc": "无限循环走廊/扭曲空间/疯狂心理",
        "light": "频闪 + 冷白, 扭曲",
        "color": "冷白/扭曲/红警示",
        "lens": "广角(WS) 走廊 / 中景(MS) 人物",
        "sound": "回声/脚步/心跳/嗡鸣",
        "ref": "诺兰《盗梦空间》/大卫·芬奇《七宗罪》/丹尼斯·维伦纽瓦《银翼杀手2049》",
        "mood": "fear,anticipation,surprise",
    },
    {
        "id": "psyche_memory_hollywood",
        "name": "记忆好莱坞 (黑白色调)",
        "type": "PSYCHE_SPACE",
        "sub": "memory",
        "desc": "记忆中的好莱坞/黑白色调/怀旧",
        "light": "黑白高对比 + 柔光, 怀旧",
        "color": "黑白/灰阶",
        "lens": "中景(MS) 回忆 / 特写(CU) 旧照",
        "sound": "老歌/旧广播/胶片",
        "ref": "大卫·芬奇《好莱坞往事》/伍迪·艾伦《曼哈顿》/昆汀《好莱坞往事》",
        "mood": "nostalgia,warm_regret,longing",
    },
    {
        "id": "psyche_fear_shadow",
        "name": "恐惧心理空间 (阴影)",
        "type": "PSYCHE_SPACE",
        "sub": "fear",
        "desc": "阴影弥漫/未知恐惧/心理外化",
        "light": "极暗 + 局部强光, 恐惧",
        "color": "黑/暗处/局部强光",
        "lens": "中近景(MCU) 阴影 / 特写(CU) 眼睛",
        "sound": "心跳/呼吸/远处脚步声",
        "ref": "希区柯克《精神病患者》/阿尔弗雷德·希区柯克《惊魂记》",
        "mood": "fear,anticipation,surprise",
    },
    {
        "id": "psyche_joy_festival",
        "name": "欢乐心理空间 (彩带)",
        "type": "PSYCHE_SPACE",
        "sub": "joy",
        "desc": "欢乐心理/彩带/气球/庆祝",
        "light": "彩光 + 暖橙 3000K, 庆祝",
        "color": "彩带彩/气球/暖橙",
        "lens": "广角(WS) 庆祝 / 中景(MS) 人物",
        "sound": "欢笑/音乐/庆祝",
        "ref": "韦斯·安德森《布达佩斯大饭店》/韦斯·安德森《月升王国》",
        "mood": "joy,trust,tenderness",
    },
    {
        "id": "psyche_grief_rain",
        "name": "悲伤心理空间 (雨)",
        "type": "PSYCHE_SPACE",
        "sub": "grief",
        "desc": "悲伤外化/无休止雨/心理雨",
        "light": "灰暗 + 雨光 5500K, 悲伤",
        "color": "灰/雨/泪水",
        "lens": "中景(MS) 雨中 / 特写(CU) 眼泪",
        "sound": "雨声/哽咽/寂静",
        "ref": "王家卫《重庆森林》/陈凯歌《霸王别姬》/是枝裕和《步履不停》",
        "mood": "sadness,longing,loneliness",
    },
    {
        "id": "psyche_anger_fire",
        "name": "愤怒心理空间 (火)",
        "type": "PSYCHE_SPACE",
        "sub": "anger",
        "desc": "愤怒外化/火焰/燃烧/炽热",
        "light": "火光 2200K + 暗部对比, 炽热",
        "color": "火橙红/黑/烟雾",
        "lens": "中景(MS) 燃烧 / 特写(CU) 火焰",
        "sound": "火焰/吼叫/远处雷声",
        "ref": "陈凯歌《霸王别姬》/奉俊昊《母亲》/诺兰《黑暗骑士》",
        "mood": "anger,fear,anticipation",
    },
    {
        "id": "psyche_awe_cosmos",
        "name": "敬畏心理空间 (宇宙)",
        "type": "PSYCHE_SPACE",
        "sub": "awe",
        "desc": "敬畏外化/宇宙/星云/无限",
        "light": "宇宙冷光 6000K + 星光, 敬畏",
        "color": "宇宙深蓝/星云彩/黑",
        "lens": "广角(WS) 宇宙 / 中景(MS) 仰望",
        "sound": "寂静/宇宙低频/远处回响",
        "ref": "库布里克《2001太空漫游》/诺兰《星际穿越》/泰伦斯·马力克《生命之树》",
        "mood": "awe,loneliness,trust",
    },

    # ============================================================
    # 类别 8: 梦境/记忆 (DREAM_MEMORY) - 7 个 (扩展)
    # ============================================================
    {
        "id": "dream_magical_forest",
        "name": "魔法森林梦境",
        "type": "DREAM_MEMORY",
        "sub": "dream_forest",
        "desc": "魔法森林梦境/发光蘑菇/萤火虫/精灵",
        "light": "月光 7000K + 萤火虫光, 梦幻",
        "color": "深绿/萤火虫黄/魔法蓝",
        "lens": "广角(WS) 梦境 / 中近景(MCU) 精灵",
        "sound": "梦境音乐/远处风铃/精灵笑声",
        "ref": "宫崎骏《幽灵公主》/蒂姆·伯顿《爱丽丝梦游仙境》",
        "mood": "awe,tenderness,joy",
    },
    {
        "id": "dream_floating_island",
        "name": "漂浮岛梦境",
        "type": "DREAM_MEMORY",
        "sub": "floating",
        "desc": "漂浮岛/空中楼阁/失重/梦境",
        "light": "天光 + 失重光, 梦幻",
        "color": "天蓝/云白/漂浮岛绿",
        "lens": "广角(WS) 漂浮 / 中景(MS) 人物",
        "sound": "梦境音乐/风/远处瀑布",
        "ref": "宫崎骏《天空之城》/詹姆斯·卡梅隆《阿凡达》/诺兰《盗梦空间》",
        "mood": "awe,anticipation,trust",
    },
    {
        "id": "dream_mirror_room",
        "name": "镜面房间梦境",
        "type": "DREAM_MEMORY",
        "sub": "mirror",
        "desc": "无限镜面/自我复制/超现实",
        "light": "镜面反射 + 强光, 超现实",
        "color": "镜面/反光/白光",
        "lens": "广角(WS) 镜面房 / 中近景(MCU) 人物",
        "sound": "回声/脚步/心跳",
        "ref": "诺兰《盗梦空间》/大卫·林奇《穆赫兰道》",
        "mood": "anticipation,surprise,loneliness",
    },
    {
        "id": "dream_childhood_room",
        "name": "童年房间记忆",
        "type": "DREAM_MEMORY",
        "sub": "childhood",
        "desc": "童年房间/旧玩具/暖光/怀旧",
        "light": "黄昏暖橙 2700K, 童年",
        "color": "暖橙/木质/旧玩具彩",
        "lens": "中景(MS) 童年 / 特写(CU) 旧物",
        "sound": "童年音乐/旧钟表/远处叫卖",
        "ref": "侯孝贤《童年往事》/是枝裕和《步履不停》/陈凯歌《霸王别姬》",
        "mood": "warm_regret,nostalgia,tenderness",
    },
    {
        "id": "dream_underwater_memory",
        "name": "水下记忆/沉没",
        "type": "DREAM_MEMORY",
        "sub": "underwater_memory",
        "desc": "水下记忆/沉没/水泡/失重",
        "light": "水下散射 8000K, 沉没",
        "color": "海蓝/水泡/灰",
        "lens": "中景(MS) 水中 / 特写(CU) 眼睛",
        "sound": "水下/气泡/寂静",
        "ref": "宫崎骏《悬崖上的金鱼姬》/塔可夫斯基《镜子》",
        "mood": "sadness,longing,loneliness",
    },
    {
        "id": "dream_train_never_lands",
        "name": "永不到站列车",
        "type": "DREAM_MEMORY",
        "sub": "train_loop",
        "desc": "永不到站列车/循环时间/超现实",
        "light": "车厢顶灯 + 窗外明暗交替",
        "color": "车厢白/窗外明暗",
        "lens": "中景(MS) 列车 / 特写(CU) 窗外",
        "sound": "列车/窗外风声/广播",
        "ref": "诺兰《盗梦空间》/王家卫《重庆森林》/宫崎骏《千与千寻》",
        "mood": "anticipation,loneliness,longing",
    },
    {
        "id": "dream_paper_world",
        "name": "纸世界梦境",
        "type": "DREAM_MEMORY",
        "sub": "paper",
        "desc": "纸世界/折纸/平面化/2.5 维",
        "light": "柔和均匀 5000K, 平面化",
        "color": "纸张白/折纸彩",
        "lens": "广角(WS) 纸世界 / 中景(MS) 折纸人物",
        "sound": "纸张沙沙/折纸/远处铃声",
        "ref": "韦斯·安德森《了不起的狐狸爸爸》/宫崎骏《千与千寻》",
        "mood": "awe,tenderness,trust",
    },
]


# ============================================================
# 场景分类函数
# ============================================================
def get_scene_by_id(scene_id):
    """根据 ID 获取场景"""
    for s in SCENES:
        if s["id"] == scene_id:
            return s
    return None


def get_scenes_by_type(scene_type):
    """根据类型获取场景列表"""
    return [s for s in SCENES if s["type"] == scene_type]


def get_scenes_by_mood(emotion):
    """根据情绪获取场景列表"""
    return [s for s in SCENES if emotion in s.get("mood", "")]


def get_scenes_by_director(director_hint):
    """根据导演风格提示获取场景"""
    director_hints = {
        "王家卫": ["urban_hk_neon_street", "urban_sh_liaison_alley", "nature_rain_storm", "psyche_loneliness_room", "psyche_grief_rain", "dream_train_never_lands"],
        "侯孝贤": ["interior_teahouse_old", "interior_old_chinese_yard", "nature_field_grass", "nature_river_stream", "dream_childhood_room", "nature_autumn_leaves", "urban_taipei_night_market"],
        "是枝裕和": ["interior_bathhouse_japan", "studio_kitchen_restaurant", "dream_childhood_room", "interior_modern_coffee", "nature_meadow_wildflower", "nature_starry_night_sky", "nature_cherry_blossom"],
        "塔可夫斯基": ["nature_lake_reflection", "nature_starry_night_sky", "psyche_awe_cosmos", "nature_rain_storm", "nature_meadow_wildflower", "dream_underwater_memory", "nature_forest_deep"],
        "诺兰": ["virtual_matrix_digital", "psyche_madness_corridor", "dream_mirror_room", "dream_train_never_lands", "virtual_space_station", "studio_office_modern", "studio_lab_science"],
        "陈凯歌": ["studio_throne_palace", "studio_brothel_red_lantern", "period_hengdian_tang", "period_hengdian_qing", "psyche_anger_fire", "psyche_awe_cosmos", "studio_bathhouse_dressing"],
        "张艺谋": ["period_hengdian_qing", "period_hengdian_tang", "nature_field_grass", "nature_cherry_blossom", "studio_brothel_red_lantern", "urban_xian_terracotta"],
        "韦斯·安德森": ["dream_paper_world", "psyche_joy_festival", "interior_modern_coffee", "urban_tokyo_shinjuku", "nature_cherry_blossom", "interior_old_opera_house"],
        "宫崎骏": ["dream_floating_island", "dream_magical_forest", "nature_ancient_tree", "virtual_underwater_palace", "nature_forest_deep", "nature_sea_ocean", "studio_kitchen_restaurant"],
        "李安": ["nature_bamboo_forest", "nature_rain_storm", "psyche_grief_rain", "interior_teahouse_old", "nature_meadow_wildflower"],
        "黑泽明": ["nature_mountain_snow", "nature_cherry_blossom", "nature_rain_storm", "psyche_awe_cosmos", "nature_field_grass", "studio_throne_palace"],
        "丹尼斯·维伦纽瓦": ["virtual_cyberpunk_city", "virtual_alien_planet", "virtual_post_apocalyptic", "studio_lab_science", "studio_office_modern", "virtual_matrix_digital"],
    }
    hint_ids = director_hints.get(director_hint, [])
    return [s for s in SCENES if s["id"] in hint_ids]


def scene_to_prompt(scene, prefix="[场景]"):
    """将场景转成 prompt 字符串"""
    parts = [
        "{}【{}】({})".format(prefix, scene["name"], scene["type"]),
        "描述: {}".format(scene["desc"]),
        "灯光: {}".format(scene["light"]),
        "色彩: {}".format(scene["color"]),
        "镜头: {}".format(scene["lens"]),
        "声音: {}".format(scene["sound"]),
        "参考: {}".format(scene["ref"]),
    ]
    return " | ".join(parts)


# ============================================================
# 场景库统计
# ============================================================
def get_stats():
    """获取场景库统计"""
    by_type = {}
    for s in SCENES:
        by_type[s["type"]] = by_type.get(s["type"], 0) + 1
    return {
        "total": len(SCENES),
        "by_type": by_type,
        "types_count": len(by_type),
    }


if __name__ == "__main__":
    stats = get_stats()
    print("=" * 60)
    print("SCENE_LIBRARY_120 场景库")
    print("=" * 60)
    print("总场景数: {}".format(stats["total"]))
    print("类型数: {}".format(stats["types_count"]))
    for t, n in stats["by_type"].items():
        print("  - {}: {} 个".format(t, n))
    print()
    print("示例场景 (王家卫风格):")
    for s in get_scenes_by_director("王家卫")[:3]:
        print("- {} | {}".format(s["id"], s["name"]))
        print("  {}".format(scene_to_prompt(s)[:120] + "..."))
