# ============================================================
# 大师级影视摄影知识库
# 来源：IMDB Top 250电影分析 + 专业摄影教材 + 导演访谈
# ============================================================

MASTER_CINEMATOGRAPHY = {
    "shot_types": {
        # ─── 深度决策条目: 每个景别 = 触发→原理→量化执行→失败模式→验收→替代→交叉 ───
        "extreme_wide": {
            "cn": "极远景",
            "trigger": "建立世界观/展示人与环境的比例/存在主义主题/史诗定场/结尾渺小化",
            "rationale": "人物占画面<10%时,环境成为主角。渺小化=命运压迫或孤独升华;史诗感来自尺度对比。",
            "execution": {
                "duration": "5-15秒(观众需时间读取环境信息)",
                "movement": "固定或极缓慢推拉/升降(快切会破坏史诗感)",
                "lens": "广角16-35mm容纳大环境, 或长焦压缩纵深",
                "subject_ratio": "人物占画面<10%",
            },
            "failure_modes": [
                "信息过载无焦点=观众不知道看哪, 须有视觉引导线或渺小人影作锚点",
                "短剧/竖屏用极远景=看不清, 竖屏主体须放大",
                "极远景无叙事目的=炫技拖节奏, 完播率崩",
            ],
            "measurement": "观众应在5秒内建立空间认知+感受到尺度情绪(渺小/史诗/孤独)",
            "alternatives": ["wide(人物比例更大,信息更聚焦)", "鸟瞰(更全知但失地平线感)"],
            "cross_refs": {"composition": "极远景必配引导线/负空间/渺小人影", "narrative": "开场定场/结尾收束标配", "vertical": "竖屏慎用"},
            "masters": "《阿拉伯的劳伦斯》沙漠渺小人影, 《银翼杀手2049》废墟全景, 《指环王》中土远景, 《荒野猎人》雪原孤影",
        },
        "wide": {
            "cn": "远景/全景",
            "trigger": "场景建立/新场景首镜/群戏展示/时间标记/交代空间关系",
            "rationale": "全景=定场工具。让观众知道'在哪+有谁+在做什么', 是新场景的地图。",
            "execution": {
                "duration": "4-10秒(观众读取空间布局需时间)",
                "movement": "固定/缓慢摇移/升降(建立镜忌快切)",
                "subject_ratio": "人物占画面15-30%, 全身可见",
                "info_layers": "前景+中景+背景三层信息清晰",
            },
            "failure_modes": [
                "定场镜信息不足=后续镜头空间感崩, 观众不知道角色在哪",
                "定场镜过长=拖节奏, 须在4-6秒内完成建立",
                "群戏全景无焦点=杂乱, 须有视觉重心",
            ],
            "measurement": "观众应能复述'这是哪里+有谁+环境特征'",
            "alternatives": ["establishing oner(长镜头跟随进入更沉浸)", "medium(更快但失空间全貌)"],
            "cross_refs": {"narrative": "新场景首镜标配", "composition": "纵深分层/前景遮挡增加层次", "continuity": "定场后所有镜头空间须与此一致"},
            "masters": "《肖申克》监狱全貌, 《教父》婚礼花园, 《千与千寻》汤屋, 《寄生虫》豪宅",
        },
        "full": {
            "cn": "全身景",
            "trigger": "角色出场/动作戏/展示服装道具/舞蹈打斗/角色完整形象",
            "rationale": "全身=展示角色'硬件'。肢体语言完整可见, 适合动作与仪式化出场。",
            "execution": {
                "duration": "3-8秒(动作戏可更短, 出场须留够)",
                "movement": "跟拍/环绕/固定(动作戏手持, 出场固定)",
                "framing": "头顶脚底各留一点空间, 不切关节",
            },
            "failure_modes": [
                "切到关节(脚踝/膝盖/手腕)=构图失误",
                "全身拍对话=表情看不清, 须切到中近景",
                "动作戏全身过多=失去冲击, 须与特写交替",
            ],
            "measurement": "观众能看清角色全身形象+肢体动作意图",
            "alternatives": ["medium(表情更清但失全身)", "full+cut到特写(动作戏节奏)"],
            "cross_refs": {"performance": "全身须肢体表演完整, 不靠表情", "action": "动作戏全身与特写交替", "costume": "服装展示标配"},
            "masters": "《杀死比尔》新娘持刀, 《黑客帝国》子弹时间全身, 《卧虎藏龙》竹林",
        },
        "medium": {
            "cn": "中景(腰上)",
            "trigger": "对话场景/日常叙事/人物互动/过渡镜头/叙事主力",
            "rationale": "中景=信息平衡点。表情可见+手势可见+环境可见, 是对话戏的标准景别。",
            "execution": {
                "duration": "2-6秒(按台词节奏, 每句话一个镜头)",
                "movement": "固定/轻微推拉/过肩(对话标配)",
                "framing": "腰以上, 手势可见, 表情可辨",
            },
            "failure_modes": [
                "中景拍高潮情绪=情绪不够强, 须推到特写",
                "中景过多=平淡, 须景别变化制造节奏",
                "双人中景站位越轴=观众空间感崩",
            ],
            "measurement": "对话清晰可辨+表情手势兼顾+节奏自然",
            "alternatives": ["medium_close(更亲密但失手势)", "over_shoulder(更主观)"],
            "cross_refs": {"dialogue": "对话戏主力景别", "continuity": "正反打须守180度轴线", "pacing": "中景是节奏基准, 升级=推到特写, 降级=拉到全景"},
            "masters": "《低俗小说》餐厅对话, 《花样年华》走廊擦肩, 《寄生虫》桌面对话",
        },
        "medium_close": {
            "cn": "中近景(胸上)",
            "trigger": "重要对话/情感交流/角色特写但保留手势/亲密但有距离",
            "rationale": "中近景=亲密临界。表情是主角, 但手势仍可见, 适合情感升级段。",
            "execution": {
                "duration": "2-5秒",
                "movement": "固定/微推(情绪升级时缓推向面部)",
                "framing": "胸以上, 头顶留空间, 表情是焦点",
            },
            "failure_modes": [
                "中近景拍群戏=只能容一人, 须切到中景",
                "中近景无情绪递进=停滞, 须推向特写释放",
            ],
            "measurement": "表情为主+手势辅助, 情感交流清晰",
            "alternatives": ["medium(更全但表情弱)", "close_up(更亲密但失手势)"],
            "cross_refs": {"performance": "微表情开始重要", "dialogue": "重要对话标配", "pacing": "中景→中近景→特写=情绪升级三段式"},
            "masters": "《闻香识女人》探戈, 《沉默的羔羊》隔玻璃对话",
        },
        "close_up": {
            "cn": "特写(面部)",
            "trigger": "情绪高潮/关键道具/微表情捕捉/悬念营造/重要信息强调",
            "rationale": "特写=放大器。把表情/物件放大到观众无法回避, 强制聚焦情绪或细节。",
            "execution": {
                "duration": "1-4秒(特写不宜长, 长则压迫)",
                "movement": "固定/极缓推(推向眼睛/嘴唇=情绪逼问)",
                "framing": "面部占画面60%+, 头顶可切(情绪特写)",
                "lens": "50-85mm中焦, 避免广角变形",
            },
            "failure_modes": [
                "特写无前置铺垫=突兀, 须从中近景推过来",
                "特写过长=压迫疲劳, 一般<4秒",
                "特写面部布光差=放大瑕疵, 须face-light",
                "竖屏情感特写面部占70%+是标配, 横屏则60%",
            ],
            "measurement": "观众应被强制聚焦到情绪/细节, 注意力达峰值",
            "alternatives": ["medium_close(更全但情绪弱)", "extreme_close_up(更极致但慎用)"],
            "cross_refs": {"performance": "微表情是特写的灵魂", "lighting": "特写须face-light, 伦勃朗光", "vertical": "竖屏情感场景面部占70%+", "pacing": "特写是情绪高点标记"},
            "masters": "《教父》白兰度抚猫, 《这个杀手不太冷》Mathilda眼泪, 《霸王别姬》妆面, 《寄生虫》石头",
        },
        "extreme_close_up": {
            "cn": "极特写",
            "trigger": "极端情绪/微观世界/超现实感/心理崩溃/瞳孔嘴唇手指等极致细节",
            "rationale": "极特写=剥夺上下文, 只剩局部。放大到失真=心理崩塌的视觉化; 微观=发现感。",
            "execution": {
                "duration": "0.5-3秒(极短, 是冲击不是停留)",
                "movement": "固定(任何晃动都放大成失误)",
                "framing": "单一局部: 瞳孔/嘴唇/手指/物件细节",
                "lens": "微距或长焦, 极浅景深",
            },
            "failure_modes": [
                "极特写滥用=廉价, 经典技法须慎用(每片1-3次)",
                "极特写无上下文=观众不知道在看什么, 须有前置建立",
                "极特写过长=不适, 须快切回正常景别",
            ],
            "measurement": "应在极短时间内制造冲击/崩塌感, 不可停留",
            "alternatives": ["close_up(更克制)", "insert(物件极特写)"],
            "cross_refs": {"performance": "极特写靠微表情或物件细节", "psychological": "心理崩塌/超现实标配", "pacing": "极特写是冲击点, 须快进快出"},
            "masters": "《2001太空漫游》HAL红眼, 《黑天鹅》瞳孔, 《安魂曲》瞳孔扩大",
        },
        "two_shot": {
            "cn": "双人景(两人同框)",
            "trigger": "对话/对峙/亲密场景/确立两人关系/势均力敌或权力对比",
            "rationale": "双人景=关系可视化。两人同框=关系当下状态的直接呈现, 谁高谁低谁亲谁疏一目了然。",
            "execution": {
                "duration": "3-8秒(关系建立需时间)",
                "movement": "固定/缓推/环绕(环绕=世界只有彼此)",
                "framing": "两人同框, 可左右/前后(前后=权力差)",
                "composition": "对称=势均力敌, 不对称=权力倾斜",
            },
            "failure_modes": [
                "双人景拍多人=失焦, 须切到中景",
                "双人景站位越轴=正反打时方向崩",
                "双人景无关系信息=浪费同框, 须让站位/距离传递关系",
            ],
            "measurement": "观众应从站位/距离/对称性读出两人关系状态",
            "alternatives": ["over_shoulder(更主观但失同框)", "正反打(更聚焦个体但失关系)"],
            "cross_refs": {"composition": "对称=平等, 不对称=权力", "performance": "双人须肢体互动或对视", "romance": "亲密双人景标配"},
            "masters": "《低俗小说》双人舞, 《霸王别姬》双人构图, 《爱乐之城》双人舞",
        },
        "insert": {
            "cn": "插入镜头(细节特写)",
            "trigger": "强调关键细节/信息补充/伏笔埋设/手部动作/道具特写/信件内容",
            "rationale": "插入=给观众'看清'的特权。把关键信息从环境中抽出放大, 是叙事的标点。",
            "execution": {
                "duration": "1-3秒(短而精, 是强调不是停留)",
                "movement": "固定/微推(推向细节=聚焦)",
                "framing": "单一物件/手部/文字, 极浅景深",
            },
            "failure_modes": [
                "插入无叙事意义=打断节奏, 须有信息/伏笔/象征价值",
                "插入过长=拖沓, 须快切回主线",
                "插入伏笔太明显=观众察觉, 须自然融入",
            ],
            "measurement": "插入应传递关键信息/埋伏笔/强调细节, 不可无意义",
            "alternatives": ["cutaway(更隐喻但失直接)", "medium中带出细节(更连贯)"],
            "cross_refs": {"foreshadow": "伏笔埋设标配(契诃夫之枪)", "narrative": "信息补足/标点", "pacing": "插入是节奏重音"},
            "masters": "《教父》打字机声插入, 《肖申克》海报插入(伏笔)",
        },
        "cutaway": {
            "cn": "切出镜头(环境/反应)",
            "trigger": "暗示隐喻/反应补充/信息对照/旁观者视角/象征物",
            "rationale": "切出=主线的'呼吸'。切到环境/反应/象征, 给观众消化空间或埋下潜台词。",
            "execution": {
                "duration": "1-3秒(短, 是呼吸不是停留)",
                "movement": "固定(切出忌运动, 否则抢戏)",
                "framing": "环境/旁观者/象征物, 与主线对照",
            },
            "failure_modes": [
                "切出无对照意义=浪费, 须与主线形成隐喻/反应/对比",
                "切出过多=主线被打断",
                "切出物件无后续=悬置, 须回收(伏笔)",
            ],
            "measurement": "切出应与主线形成对照(隐喻/反应/对比), 不空切",
            "alternatives": ["insert(更直接但失隐喻)", "reaction shot(更聚焦反应)"],
            "cross_refs": {"metaphor": "视觉隐喻标配", "performance": "旁观者反应cutaway强化主线情绪", "foreshadow": "象征物切出可埋伏笔"},
            "masters": "《教父》洗礼+刺杀交叉(神圣与暴力), 《现代启示录》直升机+冲浪对照",
        },
    },

    "camera_angles": {
        # ─── 深度决策: 每个角度 = 触发→原理→量化执行→失败模式→验收→替代→交叉 ───
        "eye_level": {
            "cn": "平视(眼平)",
            "trigger": "客观叙事/对话/日常/平等关系/让观众与角色平起平坐",
            "rationale": "眼平=人眼视角, 无权力倾斜。是最中性的机位, 让观众成为平等的旁观者。",
            "execution": {
                "height": "机位与角色眼睛齐平(站姿1.5-1.7m, 坐姿1.2m, 儿童0.9m)",
                "lens": "50mm标准, 避免变形",
                "tone": "客观中立, 无情绪偏向",
            },
            "failure_modes": ["全程平视=单调, 须角度变化制造节奏", "平视拍权力场景=失层次, 须仰/俯"],
            "measurement": "观众应感到客观平等, 无权力暗示",
            "alternatives": ["low_angle(权力化)", "high_angle(弱化)"],
            "cross_refs": {"genre": "日常/对话标配", "child": "拍儿童须降到其眼平, 否则成俯视压迫", "realism": "纪实感来源"},
            "masters": "小津安二郎低机位平视, 纪实摄影",
        },
        "low_angle": {
            "cn": "仰拍(低于眼平向上)",
            "trigger": "展示权力/反派威胁/英雄时刻/崇高/权威人物",
            "rationale": "仰拍=观众低于角色, 潜意识仰视=权威/崇高。是权力关系的视觉化。",
            "execution": {
                "angle": "机位低于眼平15-45度向上, 角度越大越夸张",
                "lens": "广角24-35mm强化仰视张力, 但人物变形",
                "ceiling": "可纳入天花板/天空=被结构包裹(《公民凯恩》)",
            },
            "failure_modes": ["仰拍过陡(>45度)=鼻孔变形失真, 须控制", "仰拍反派过度=廉价反派", "仰拍日常=违和(无权力理由)"],
            "measurement": "观众应读出'权威/英雄/威胁'的权力感",
            "alternatives": ["worms_eye(更极端)", "eye_level(更中性)"],
            "cross_refs": {"power": "仰拍=权力上扬的核心工具", "composition": "仰拍常配center_frame/symmetry", "lighting": "仰拍常配rembrandt光强化权力"},
            "masters": "《公民凯恩》仰拍凯恩, 《黑暗骑士》小丑仰拍",
        },
        "high_angle": {
            "cn": "俯拍(高于眼平向下)",
            "trigger": "展示角色弱势/被审视/命运压迫/上帝视角/揭示全局",
            "rationale": "俯拍=观众高于角色, 潜意识俯视=弱小/被审视。是脆弱与命运的视觉化。",
            "execution": {
                "angle": "机位高于眼平15-45度向下, 角度越大越压迫",
                "lens": "广角强化俯视压迫, 或长焦压缩",
                "context": "俯拍揭示环境全局(战场/迷宫)",
            },
            "failure_modes": ["俯拍过陡=失角色主体, 须平衡", "俯拍英雄=失威, 须有理由", "俯拍日常=违和(无审视理由)"],
            "measurement": "观众应读出'弱小/被审视/命运压迫'",
            "alternatives": ["birds_eye(更极端全知)", "eye_level(更中性)"],
            "cross_refs": {"power": "俯拍=权力下降的核心工具", "composition": "俯拍常配negative_space渺小化", "vulnerability": "俯拍强化角色弱势"},
            "masters": "《精神病患者》浴室俯拍, 《辛德勒的名单》俯瞰",
        },
        "birds_eye": {
            "cn": "鸟瞰(正上方)",
            "trigger": "全知视角/命运感/宏观叙事/战场鸟瞰/迷宫空间/上帝视角",
            "rationale": "正上方俯瞰=完全的全知, 角色成棋盘上的棋子, 命运感最强。",
            "execution": {
                "angle": "机位接近正上方90度",
                "tool": "无人机/摇臂/直升机/上帝视角",
                "pattern": "可拍出地面图案(队列/迷宫/战场布局)",
            },
            "failure_modes": ["鸟瞰无图案=失宏观价值, 须有可辨布局", "鸟瞰过多=失角色主体", "鸟瞰连戏困难(天气/光线)"],
            "measurement": "观众应读出'全知/命运/宏观', 须有可辨地面布局",
            "alternatives": ["high_angle(更柔和)", "drone(无人机鸟瞰是现代标配)"],
            "cross_refs": {"genre": "史诗/战争/迷宫标配", "composition": "鸟瞰常配几何图案", "vfx": "现代多配无人机"},
            "masters": "《盗梦空间》城市折叠, 《1917》战壕鸟瞰, 《闪灵》迷宫鸟瞰",
        },
        "worms_eye": {
            "cn": "虫视(极低角度)",
            "trigger": "极端渺小感/恐惧/陌生化/怪物视角/压迫性环境",
            "rationale": "贴近地面的极低视角=人无法达到的角度, 制造陌生与恐惧。常作怪物/巨物POV。",
            "execution": {
                "height": "机位贴近地面(0-30cm)",
                "subject": "仰视角色/巨物, 强化巨大感",
                "lens": "广角强化垂直线条张力",
            },
            "failure_modes": ["虫视滥用=眩晕, 须慎用", "虫视无巨大主体=失对照", "虫视连戏困难"],
            "measurement": "观众应读出'极端渺小/恐惧/陌生化'",
            "alternatives": ["low_angle(更柔和权力)", "dutch_angle(更失衡)"],
            "cross_refs": {"genre": "恐怖/巨物/超现实标配", "monster_pov": "怪物视角常配虫视", "composition": "虫视强化垂直线条"},
            "masters": "《侏罗纪公园》恐龙虫视, 《指环王》巨物",
        },
        "dutch_angle": {
            "cn": "荷兰角(倾斜构图)",
            "trigger": "不安/失衡/疯狂/世界观崩塌/心理失常/梦境/混乱战斗",
            "rationale": "画面倾斜=打破水平稳定, 潜意识读为'不对劲'。是心理失常的视觉编码。",
            "execution": {
                "tilt": "画面倾斜15-45度, 角度越大越失常",
                "use": "Batmn小丑=疯狂; 战斗混乱=失衡; 梦境=逻辑断裂",
                "combine": "可配对角线构图强化失衡",
            },
            "failure_modes": ["荷兰角滥用=廉价, 须有失常理由", "荷兰角拍日常=违和", "荷兰角过陡=眩晕"],
            "measurement": "观众应读出'不安/失衡/失常', 须有心理理由",
            "alternatives": ["diagonal(更动态但稳)", "handheld(更混乱但失构图)"],
            "cross_refs": {"genre": "心理恐怖/超现实/疯狂标配", "narrative": "荷兰角=世界观崩塌的视觉化", "composition": "常配对角线失衡"},
            "masters": "《第三人》倾斜维也纳, 《蝙蝠侠》小丑场景, 《12猴子》",
        },
        "over_shoulder": {
            "cn": "过肩镜头",
            "trigger": "对话场景/对话参与感/关系建立/主观性但保留两人",
            "rationale": "从一人肩后看过另一人=既主观(代入听者)又保留两人关系。是对话戏的标准机位。",
            "execution": {
                "framing": "前景肩(虚化)+主体面部, 两人同框",
                "angle": "过肩角度变化须守180度轴线",
                "ratio": "前景肩占画面1/4-1/3, 主体占2/3",
            },
            "failure_modes": ["过肩越轴=空间感崩, 须守轴线", "前景肩过实=抢主体, 须虚化", "过肩无对话=浪费"],
            "measurement": "对话参与感+保留两人关系, 须守轴线",
            "alternatives": ["two_shot(更同框但失主观)", "pov(更主观但失另一人)"],
            "cross_refs": {"dialogue": "对话戏标准机位", "continuity": "过肩须守180度轴线", "composition": "前景虚化肩+主体清晰"},
            "masters": "对话戏通用, 《社交网络》过肩对话",
        },
        "pov": {
            "cn": "主观视角(POV)",
            "trigger": "恐怖(看不到背后)/追逐/角色发现重要物品/沉浸代入/第一人称",
            "rationale": "完全代入角色视角=观众成为角色, 沉浸最强。恐怖片用POV让'看不到背后'的恐惧最大化。",
            "execution": {
                "height": "机位=角色眼睛高度, 模拟其视角",
                "movement": "手持/呼吸晃动=代入感, 或steadicam流畅",
                "reveal": "POV常用于揭示角色看到的重要物(让揭示更有冲击)",
            },
            "failure_modes": ["POV过长=观众失角色主体, 须切回角色反应", "POV无揭示=浪费代入", "POV晃过大=晕"],
            "measurement": "观众应感到'成为角色', 须有揭示或恐惧理由",
            "alternatives": ["over_shoulder(更保留角色)", "fpv_drone(更极速但失人视角)"],
            "cross_refs": {"genre": "恐怖/追逐/第一人称标配", "performance": "POV后须切角色反应镜", "sound": "POV常配角色呼吸/心跳声"},
            "masters": "《闪灵》Danny三轮车POV, 《1917》连续POV, 《硬核亨利》全片POV",
        },
    },

    "camera_movements": {
        # ─── 深度决策条目(金标准模板): 每个运镜 = 触发→原理→量化执行→失败模式→验收→替代→交叉 ───
        "static": {
            "cn": "固定机位",
            "trigger": "对话场景/肖像式构图/让角色自身动作说话/庄严仪式感",
            "rationale": "不动机位=不介入, 把判断权交给观众。固定让画框可见, 强化'被审视'感。",
            "execution": {
                "duration": "对话3-8s, 仪式5-15s, 长凝视10-30s",
                "stability": "三脚架/沙袋, 严禁手持(否则失庄重)",
                "frame": "构图须工整, 固定下任何歪斜都成失误",
            },
            "failure_modes": [
                "长固定无信息递进=观众出戏, 须靠表演/调度内部变化",
                "固定+构图差=暴露构图无能(无法靠运动救场)",
            ],
            "measurement": "观众注意力曲线应靠画面内动作维持, 而非靠机位变化",
            "alternatives": ["微推(push_in)增加压迫", "滑轨(slider)加纵深而不破坏庄重"],
            "cross_refs": {"composition": "固定必配对称/三分/居中", "performance": "固定=把舞台让给演员, 表演须撑住"},
            "masters": "Kubrick对称固定、Wes Anderson居中、小津低机位固定",
        },
        "push_in": {
            "cn": "推镜头(机位前移)",
            "trigger": "角色做重要决定/发现真相/情绪积累到爆发前/让观众逼近角色内心",
            "rationale": "物理逼近=心理逼近。推的过程制造'被迫靠近'的不安与聚焦, 终点应是信息/情绪高点。",
            "execution": {
                "speed_calm": "0.3-0.8m/s, 5-10秒推完, 渐进压迫(蓄势/情绪铺垫)",
                "speed_normal": "1-2m/s, 2-4秒, 常规聚焦(对话情绪升级)",
                "speed_shock": ">3m/s 或切到更近景别, <1秒, 惊吓/冲击(慎用)",
                "focal": "推近时若焦段不变, 背景透视不变(区别于zoom)",
                "endpoint": "推到0.5m以内=亲密临界, 越界=侵犯感",
            },
            "failure_modes": [
                "推得无理由=观众察觉机心, 出戏",
                "推到面部过近+短焦段=鼻孔变形失真, 须换更短焦",
                "推镜终点表演没跟上=推了个寂寞, 须与演员约定爆发点",
                "推镜中面部光丢失(逆光)=脸黑, 须补face-light",
            ],
            "measurement": "推镜终点应=信息高点(真相揭示)或情绪高点(表演爆发); 观众注意力曲线随推上升",
            "alternatives": ["zoom(无位移,仅视角,更廉价更突兀)", "切到近景(最快最省, 但失过程感)", "slider微推(对话场景精致小推)"],
            "cross_refs": {"performance": "终点=表演爆发点, 需约定", "sound": "常配呼吸声/低频渐强", "lighting": "推时面部光须保持"},
            "masters": "Hitchcock《迷魂记》缓推逼近真相, Spielberg《ET》推到对视",
        },
        "pull_back": {
            "cn": "拉镜头(机位后移)",
            "trigger": "角色陷入孤独/揭示真实环境规模/结尾收束/角色失去控制",
            "rationale": "后退=疏离。拉开展现角色在更大世界中的渺小, 或揭示之前未看见的真相(环境/人群/尸体)。",
            "execution": {
                "speed_sad": "缓拉0.3-0.5m/s, 6-12秒, 惆怅/余韵(结尾)",
                "speed_reveal": "匀拉1-2m/s, 3-6秒, 揭示环境",
                "speed_shock": "急拉>3m/s, <1秒, 震撼揭示(发现尸体/真相)",
                "endpoint": "拉到极远景=人物渺小化; 拉到能看清全景=规模揭示",
            },
            "failure_modes": [
                "拉到环境与情绪无关=浪费揭示, 须拉的终点有意义",
                "结尾缓拉过长=拖沓, 短片尤忌(完播率崩)",
            ],
            "measurement": "拉镜终点应让画面产生新含义(角色渺小/环境真相), 否则无效",
            "alternatives": ["cut到远景(更快)", "crane升起(更壮阔)"],
            "cross_refs": {"narrative": "结尾收束标配", "composition": "拉到负空间=孤独强化"},
            "masters": "《寄生虫》缓拉揭示阶级空间, 《现代启示录》结尾拉离",
        },
        "pan": {
            "cn": "摇镜头(水平转动)",
            "trigger": "环境扫描/从A摇到B建立关系/跟随视线/时间流逝",
            "rationale": "横摇=在同一水平线上连接元素。摇的速度=观众读取信息的节奏。",
            "execution": {
                "speed_scan": "缓摇5-15秒, 环境全貌/跟随视线",
                "speed_follow": "匀速跟随运动主体, 保持主体在画面固定位置",
                "arc": "横摇幅度>180度=眩晕, 一般<120度",
                "vertical_forbid": "竖屏禁用大幅横摇(水平运动在竖屏效果差)",
            },
            "failure_modes": [
                "横摇过快=模糊眩晕(除非刻意), 一般观众跟得上",
                "摇到无关元素=信息噪声, 摇的路径每点都应有意义",
                "竖屏横摇=破坏9:16构图, 改用tilt",
            ],
            "measurement": "摇的起点与终点都应是信息点, 中间路径不浪费",
            "alternatives": ["cut到不同元素(更快)", "whip_pan(时间跳跃/能量爆发)"],
            "cross_refs": {"vertical": "竖屏改用tilt(垂直摇)", "continuity": "横摇后正反打须守视线匹配"},
            "masters": "《星球大战》开场横摇定场, Kurosawa横摇跟武士对决",
        },
        "tilt": {
            "cn": "抬/压镜头(垂直转动)",
            "trigger": "揭示高度/从脚到头揭示角色/仰望建筑/低头发现地面线索",
            "rationale": "垂直摇=纵向连接。从下到上=揭示角色全貌/建筑伟岸; 从上到下=发现/坠落/低头情绪。",
            "execution": {
                "speed_reveal": "匀速3-6秒, 从脚摇到头揭示角色",
                "speed_loom": "缓仰2-5秒, 仰望建筑/巨型物, 制造压迫",
                "vertical_friendly": "竖屏首选(纵向运动适配9:16)",
            },
            "failure_modes": ["摇到无关高度=浪费", "仰拍人物过陡=鼻孔变形, 须控制角度<45度"],
            "measurement": "tilt终点应是揭示点(角色全貌/巨大物/地面线索)",
            "alternatives": ["cut到不同高度景别", "crane升降(更壮阔)"],
            "cross_refs": {"vertical": "竖屏友好运镜", "power": "从脚到头=逐步建立角色权威感"},
            "masters": "《公民凯恩》仰拍天花板, Kubrick从脚到头揭示角色",
        },
        "dolly": {
            "cn": "轨道推移(机位平移)",
            "trigger": "穿过走廊/人群/平行跟随角色/流畅叙事推进",
            "rationale": "轨道=最丝滑的物理位移。dolly前进=观众主动进入空间; dolly横移=伴随角色移动。",
            "execution": {
                "speed_smooth": "匀速0.5-1.5m/s, 须丝滑无顿挫",
                "track_type": "直线轨(走廊)/曲线轨(环绕)/高低轨(升降)",
                "dolly_zoom": "dolly+zoom反方向=Vertigo Shot(眩晕)",
            },
            "failure_modes": ["轨不直/有顿挫=穿帮", "dolly无叙事目的=炫技"],
            "measurement": "dolly的起点终点须有空间/信息递进",
            "alternatives": ["steadicam(更自由但失丝滑)", "slider(小范围精致)"],
            "cross_refs": {"continuity": "dolly中轴线须守", "performance": "dolly跟角色同步, 演员须走位精确"},
            "masters": "Spielberg前进dolly, Kubrick《闪灵》走廊dolly",
        },
        "tracking": {
            "cn": "跟拍(跟随主体)",
            "trigger": "角色行走/奔跑/跟随进入新环境",
            "rationale": "跟拍=陪伴感。观众与角色同行, 沉浸式代入。tracking方向=前跟/后跟/侧跟各不同。",
            "execution": {
                "front_track": "后退跟拍, 角色朝镜头走来, 表情清晰",
                "back_track": "背后跟拍, 角色背对, 跟随式陪伴",
                "side_track": "侧面平移, 展现角色行进与环境",
                "stabilization": "steadicam/手持稳定器, 模拟人的步频但更稳",
            },
            "failure_modes": ["跟拍晃过大=观众晕", "跟拍无终点=拖沓"],
            "measurement": "跟拍应让代入感上升, 终点到达新空间/新信息",
            "alternatives": ["handheld(更真实但更乱)", "dolly(更丝滑但受轨道限制)"],
            "cross_refs": {"performance": "跟拍中演员自然走位, 避免表演痕迹"},
            "masters": "《好家伙》后厨长跟拍, 《赎罪》海滩跟拍",
        },
        "crane": {
            "cn": "升降/摇臂",
            "trigger": "从特写升起到全景/从高处降落到角色身边/史诗开场/视角转换",
            "rationale": "升降=视角的垂直戏剧性。升起=俯瞰/命运/渺小; 降落=降临/接近/着陆。",
            "execution": {
                "speed_rise": "缓升5-15秒, 从特写到极远景, 揭示规模",
                "speed_descent": "缓降3-8秒, 从鸟瞰到角色, 降临感",
                "range": "摇臂可达3-10米垂直范围; 大型crane可达30米+",
            },
            "failure_modes": ["升降无目的=炫技", "升降过快=失史诗感"],
            "measurement": "升降起点终点须有视角/规模/命运的转变",
            "alternatives": ["无人机(更灵活但失丝滑)", "jib(小范围)"],
            "cross_refs": {"narrative": "史诗开场/结尾收束标配", "composition": "升降到鸟瞰=上帝视角"},
            "masters": "《乱世佳人》红十字升降, Spielberg开场升降",
        },
        "handheld": {
            "cn": "手持摄影",
            "trigger": "战争/追逐/恐惧/纪实风格/临场混乱感",
            "rationale": "手持的微晃=人的在场感。观众潜意识代入'我也在现场'。晃动幅度=混乱/恐惧强度。",
            "execution": {
                "shake_subtle": "微晃, 模拟呼吸, 纪实感(日常/对话)",
                "shake_chaos": "大幅晃动, 战争/追逐/恐惧, 失控感",
                "shutter": "手持常配高快门(1/200+)减少模糊, 增强颗粒感",
            },
            "failure_modes": [
                "手持晃过大=观众晕, 完播率崩(短视频尤甚)",
                "手持拍对话=违和(除非刻意纪实)",
                "手持破坏连戏(每镜晃动不同)",
            ],
            "measurement": "手持应服务于临场/混乱, 而非偷懒省设备",
            "alternatives": ["steadicam(流畅但不失代入)", "固定(庄重但失临场)"],
            "cross_refs": {"genre": "战争/恐怖/纪实标配", "vertical": "竖屏手持更易晃晕, 慎用"},
            "masters": "《拯救大兵瑞恩》D-Day, Paul Greengrass动作戏, Dogme 95",
        },
        "steadicam": {
            "cn": "斯坦尼康(稳定器)",
            "trigger": "长走廊跟随/穿越人群/幽灵般视角/长镜头场面调度",
            "rationale": "steadicam=手持的流畅版。像幽灵般飘浮跟随, 既代入又丝滑, 适合一镜到底。",
            "execution": {
                "duration": "长镜头15-90秒+, 一镜到底伪剪辑",
                "movement": "前后左右环绕均可, 丝滑无顿挫",
                "operator": "须专业操作员, 走位如舞步",
            },
            "failure_modes": ["长镜头无调度层次=炫技拖沓", "操作不稳=穿帮"],
            "measurement": "steadicam长镜头应完成复杂场面调度(多角色/多空间)",
            "alternatives": ["dolly(更丝滑但受轨道)", "handheld(更真实但更乱)"],
            "cross_refs": {"narrative": "一镜到底/伪一镜到底核心运镜", "continuity": "长镜头内须守连戏"},
            "masters": "《闪灵》走廊steadicam, 《好家伙》后厨长镜头, 《鸟人》伪一镜到底",
        },
        "whip_pan": {
            "cn": "急速横摇/甩镜",
            "trigger": "快速场景转换/动作冲击/时间省略/注意力转移",
            "rationale": "甩镜的模糊瞬间可隐藏剪辑点=隐形转场。能量爆发, 节奏加速。",
            "execution": {
                "speed": ">360度/秒, 画面短暂模糊",
                "hidden_cut": "甩到B角色时切=隐形剪辑(《1917》全片用)",
                "timing": "甩镜须卡在动作/能量爆发的节拍上",
            },
            "failure_modes": ["甩镜过频=眩晕疲劳", "甩镜不卡节拍=突兀"],
            "measurement": "甩镜应实现场景跳转或能量爆发, 观众不察觉剪辑点为佳",
            "alternatives": ["cut(更快但失过程)", "match_cut(更精致但需构图匹配)"],
            "cross_refs": {"editing": "隐形剪辑技法", "vertical": "竖屏慎用(水平运动效果差)"},
            "masters": "《1917》甩镜隐形剪辑, Edgar Wright甩镜节奏",
        },
        "zoom": {
            "cn": "变焦(焦段变化无机位移动)",
            "trigger": "突然发现/恐惧放大/复古70年代风格/认知崩塌(配dolly反向)",
            "rationale": "zoom仅改变视角, 不移动机位。zoom in=逼近感(无物理位移); zoom out=暴露感。比dolly更突兀更廉价。",
            "execution": {
                "speed_snap": "急zoom<1秒, 情绪爆点标记(Tarantino式)",
                "speed_slow": "缓zoom5-15秒, 不安累积(Altman式)",
                "vertigo": "zoom+dolly反向=Vertigo Shot(认知崩塌)",
            },
            "failure_modes": [
                "滥用zoom=廉价感(除非刻意复古)",
                "zoom in到面部+长焦=浅景深, 须注意连戏",
                "zoom与dolly混用无目的=混乱",
            ],
            "measurement": "zoom应标记情绪爆点或制造不安, 须有叙事理由",
            "alternatives": ["dolly(物理逼近更自然)", "cut到近景(更快)"],
            "cross_refs": {"style": "70年代复古/类型片常用", "vertigo": "zoom+dolly反=眩晕"},
            "masters": "Tarantino急zoom, Robert Altman缓zoom, Hitchcock《迷魂记》Vertigo",
        },
        "orbit": {
            "cn": "环绕(绕主体旋转)",
            "trigger": "角色情绪爆发/两人对峙张力/时间凝固/命运之轮",
            "rationale": "环绕=360度审视。世界在转而角色不动=时间凝固。对峙时环绕=张力拉满。",
            "execution": {
                "speed_slow": "缓绕10-30秒, 情绪凝固",
                "speed_bullet": "极速环绕+多机位=子弹时间(《黑客帝国》)",
                "radius": "环绕半径决定亲密度(近=亲密, 远=审视)",
            },
            "failure_modes": ["环绕无目的=眩晕", "环绕过快=晕(除非刻意子弹时间)"],
            "measurement": "环绕应服务于情绪凝固或对峙张力, 终点应有新视角揭示",
            "alternatives": ["cut多机位(更快)", "steadicam环绕(更丝滑)"],
            "cross_refs": {"performance": "环绕中演员须保持情绪持续", "vfx": "子弹时间常配多机位CG"},
            "masters": "《黑客帝国》子弹时间, 《迷失东京》对峙环绕",
        },
        "vertigo_shot": {
            "cn": "推拉变焦(Vertigo/Dolly Zoom)",
            "trigger": "角色意识到真相的瞬间/恐惧/震惊的顿悟/认知崩塌",
            "rationale": "dolly前进+zoom拉远(或反之)=主体大小不变而背景透视剧变=世界变形而我不变=认知崩塌的视觉化。",
            "execution": {
                "coordination": "dolly与zoom须精确反向协调, 主体在画面保持大小不变",
                "focal_range": "从中广角到长焦(或反之), 透视剧变",
                "duration": "3-8秒, 顿悟瞬间",
            },
            "failure_modes": ["dolly与zoom不协调=主体大小变化, 失效果", "滥用=廉价(经典技法须慎用)"],
            "measurement": "应精准卡在'角色顿悟真相'的瞬间, 不可滥用",
            "alternatives": ["急推特写(更直接但失眩晕感)", "static+表情(更克制)"],
            "cross_refs": {"narrative": "顿悟/真相揭示瞬间标配", "performance": "须配面部表情的'认知崩塌'"},
            "masters": "《迷魂记》(Vertigo)希区柯克首创, 《魔戒》Frodo戴戒, 《嗜血法医》",
        },
        "jib_arm": {
            "cn": "摇臂(中小型升降)",
            "trigger": "中小规模升降/从地面到中景/对话场景高低转换",
            "rationale": "jib比crane小, 适合室内/对话场景的灵活升降。比crane快, 比slider有垂直维度。",
            "execution": {
                "range": "1-3米垂直范围, 室内友好",
                "speed": "比crane快, 适合对话节奏",
                "combo": "常配横移=复合运动",
            },
            "failure_modes": ["室内jib幅度过大=碰天花板/灯具"],
            "measurement": "jib升降应服务视角转换, 不可炫技",
            "alternatives": ["crane(更壮阔)", "slider(无垂直维度)"],
            "cross_refs": {"genre": "室内剧/对话场景常用"},
            "masters": "电视直播/室内剧常用jib",
        },
        "cable_cam": {
            "cn": "索道摄影",
            "trigger": "跨越不可能的角度/动态上帝视角/体育赛事/穿越峡谷",
            "rationale": "索道=机位悬空飞跃, 实现人无法到达的角度。上帝视角+动态运动。",
            "execution": {
                "range": "可跨数十米, 高空悬拉",
                "speed": "匀速或变速, 跟随运动主体",
                "control": "远程遥控云台, 可 pan/tilt/zoom",
            },
            "failure_modes": ["索道晃动=画面不稳(须配稳定器)", "高空作业风险"],
            "measurement": "应实现人无法到达的视角, 不可平地可用就上索道",
            "alternatives": ["无人机(更灵活但续航短)", "crane(更受臂长限制)"],
            "cross_refs": {"genre": "体育/演唱会/户外大片"},
            "masters": "冬奥会/超级碗直播, 《碟中谍》户外大场面",
        },
        "fpv_drone": {
            "cn": "FPV穿越机",
            "trigger": "一镜到底穿越建筑/自然/极限运动跟拍/新锐短视频",
            "rationale": "FPV=第一人称视角的极速穿越。沉浸感极强, 适合一镜到底的空间穿越。",
            "execution": {
                "speed": "极速可达100km/h+, 穿越感",
                "control": "飞手戴VR眼镜第一人称操控, 须高超技术",
                "safety": "室内/人群穿越风险高, 须专业飞手+安全预案",
            },
            "failure_modes": ["飞手技术不足=炸机/伤人", "穿越无叙事目的=炫技", "竖屏适配差(横向运动)"],
            "measurement": "FPV应实现沉浸穿越, 终点到达新空间/新信息",
            "alternatives": ["cable_cam(更安全但受索道)", "steadicam(更近但受地形)"],
            "cross_refs": {"genre": "极限运动/新锐短视频/户外大片", "vertical": "竖屏适配差"},
            "masters": "Red Bull极限运动, 新锐旅行Vlog",
        },
        "slider": {
            "cn": "滑轨(小范围精致运动)",
            "trigger": "对话场景微推/产品展示/静物精致运动/不引人注目的纵深推进",
            "rationale": "slider=小范围(0.5-1.5m)的丝滑运动。比dolly轻便, 适合微推不破坏对话节奏。",
            "execution": {
                "range": "0.5-1.5m, 小范围",
                "speed": "匀速或手动, 须丝滑",
                "use": "对话中微推增加亲密感, 不打断节奏",
            },
            "failure_modes": ["slider幅度过大=超出设计范围", "slider不丝滑=穿帮"],
            "measurement": "slider应做'不被察觉的'纵深推进, 强化而不打断",
            "alternatives": ["dolly(更大范围)", "push_in(更大但更重)"],
            "cross_refs": {"genre": "产品展示/对话场景标配", "vertical": "竖屏slider纵深友好"},
            "masters": "产品广告/美食视频/对话场景常用",
        },
    },

    "lighting": {
        # ─── 深度决策: 每种布光 = 触发→原理→量化执行→失败模式→验收→替代→交叉 ───
        "three_point": {
            "cn": "三点布光",
            "trigger": "商业/对话/标准人像/需要清晰美观且无风格偏向的场景",
            "rationale": "主光塑形+补光减阴影+轮廓光分离背景=最通用的人像照明, 美观且信息清晰。",
            "execution": {
                "key_light": "主光45度侧前, 最强, 塑形+定调",
                "fill_light": "补光在对侧, 强度为主光30-50%, 减阴影",
                "rim_light": "轮廓光背后侧逆, 分离主体与背景",
                "ratio": "主:补=2:1(柔和)到4:1(戏剧)",
            },
            "failure_modes": ["三点布光过于标准=无风格, 艺术片显平庸", "补光过强=平, 失立体感", "轮廓光过强=不自然发边"],
            "measurement": "主体清晰美观+立体感+与背景分离, 适合商业但不显个性",
            "alternatives": ["rembrandt(更深沉艺术)", "practical(更真实沉浸)"],
            "cross_refs": {"genre": "商业/对话标配", "close_up": "特写须配face-light三点", "continuity": "连戏内光位不变"},
            "masters": "好莱坞经典照明",
        },
        "rembrandt": {
            "cn": "伦勃朗光",
            "trigger": "深沉对话/古典艺术感/权力人物/需要庄重与立体的人像",
            "rationale": "45度高位主光在面颊形成三角亮区=古典绘画的光影雕塑, 庄重而有人文厚度。",
            "execution": {
                "key_angle": "主光45度侧前+略高位, 形成鼻侧三角亮区",
                "shadow": "鼻影三角形, 一侧脸颊亮区",
                "fill": "补光极弱或不补, 强化明暗",
                "ratio": "主:补=4:1到8:1(高戏剧对比)",
            },
            "failure_modes": ["三角亮区位置不准=失古典感, 须精确调光位", "补光过强=破坏明暗, 须弱补或无补"],
            "measurement": "面颊可见三角亮区+庄重艺术感",
            "alternatives": ["three_point(更通用但浅)", "chiaroscuro(更极端对比)"],
            "cross_refs": {"genre": "权力叙事/古典人像", "close_up": "权力特写标配", "color_grading": "常配暖金调色"},
            "masters": "《教父》白兰度面部光影",
        },
        "chiaroscuro": {
            "cn": "明暗对比法(极端对比)",
            "trigger": "黑色电影/戏剧性/紧张/权力幽暗/道德灰色地带",
            "rationale": "大面积阴影+少量高光=把不可见藏在暗处, 制造不安与神秘。黑暗是叙事材料而非缺光。",
            "execution": {
                "key": "单点强主光, 大面积暗部",
                "shadow": "阴影占画面60%+, 信息藏在暗处",
                "fill": "几乎不补光, 明暗极端",
                "ratio": "主:补=8:1以上",
            },
            "failure_modes": ["暗部过黑看不清=信息丢失, 须留一点暗部细节", "滥用=所有场景都暗=失对比力量", "连戏困难(暗部细微差异难复制)"],
            "measurement": "阴影占画面60%+, 但暗部仍有可辨细节, 戏剧性张力强",
            "alternatives": ["low_key(更广义低调)", "rembrandt(更柔和)"],
            "cross_refs": {"genre": "黑色电影/权力幽暗标配", "composition": "常配框中框/前景遮挡增加困局感", "color_grading": "去饱和冷调"},
            "masters": "《公民凯恩》深影构图, 《银翼杀手》黑暗城市",
        },
        "high_key": {
            "cn": "高调光(整体明亮)",
            "trigger": "喜剧/欢快/纯净天真/家庭温情/儿童/Wes Anderson式风格化",
            "rationale": "阴影极少=视觉轻松, 暗示安全/欢乐/纯真。明亮本身成为情绪语言。",
            "execution": {
                "fill": "补光强, 阴影极少",
                "ratio": "主:补=1.5:1到2:1(几乎无阴影)",
                "exposure": "整体偏亮1/3到1档",
            },
            "failure_modes": ["高调拍悲剧=违和(除非反讽)", "过亮=失立体, 须保留一点阴影", "喜剧用低调=破坏欢快"],
            "measurement": "阴影极少+整体明亮+视觉轻松, 适合欢快纯真",
            "alternatives": ["three_point(更通用)", "golden_hour(温暖但更柔和)"],
            "cross_refs": {"genre": "喜剧/儿童/家庭标配", "color": "常配暖色高饱和", "mood": "欢快天真"},
            "masters": "Wes Anderson电影, 浪漫喜剧",
        },
        "low_key": {
            "cn": "低调光(大面积暗部)",
            "trigger": "悬疑/恐惧/压抑/黑色电影/心理黑暗/惊悚",
            "rationale": "大面积暗部=把威胁藏在不可见处。低调光让黑暗成为主角, 制造不安与窥视感。",
            "execution": {
                "key": "单点主光, 大面积暗部",
                "shadow": "暗部占画面60-80%",
                "fill": "极弱补光, 仅保暗部可辨",
                "ratio": "主:补=4:1到8:1",
            },
            "failure_modes": ["暗部过黑=看不清, 须留细节", "低调拍欢快=违和", "低调连戏困难"],
            "measurement": "暗部占60%+但可辨, 悬疑恐惧氛围达成",
            "alternatives": ["chiaroscuro(更极端)", "neon(更风格化)"],
            "cross_refs": {"genre": "悬疑/恐怖/黑色标配", "composition": "负空间+框中框强化不安", "sound": "常配安静/低频"},
            "masters": "《七宗罪》《黑暗骑士》",
        },
        "practical": {
            "cn": "实景光源(动机光)",
            "trigger": "纪实风格/真实感/日常沉浸/自然光优先/Roger Deakins式现代摄影",
            "rationale": "用场景中可见光源(窗/灯/烛/月)照明=光线有叙事理由, 沉浸感最强, 不显布灯痕迹。",
            "execution": {
                "source": "窗光/台灯/烛光/月光/屏幕光等场景内可见源",
                "augment": "可用反光板/柔光板增强但保持动机",
                "white_balance": "按主光源色温白平衡",
            },
            "failure_modes": ["实景光不足=曝光不足, 须增强(反光板/LED补)", "动机不合理(光来自不可能的方向)=穿帮", "色温混乱(多源不同温)=须统一或刻意混合"],
            "measurement": "光线有合理动机+沉浸真实+不显布灯痕迹",
            "alternatives": ["motivated(广义动机光)", "three_point(更可控但失真实)"],
            "cross_refs": {"genre": "纪实/现代摄影标配", "continuity": "实景光随时间变, 连戏须注意", "color_grading": "保留实景光色温质感"},
            "masters": "Roger Deakins自然光运用, 《地心引力》",
        },
        "golden_hour": {
            "cn": "黄金时刻(日出日落金光)",
            "trigger": "温暖/怀旧/浪漫/希望/史诗庄严/田园/Terrence Malick式诗电影",
            "rationale": "日出日落低角度金光=色温暖+光线柔+方向低=天然的诗意与希望感, 不可复制的美。",
            "execution": {
                "timing": "日出后/日落前1小时(黄金时刻), 每天约60-90分钟窗口",
                "quality": "低角度+柔光+金色色温(2500-3500K)",
                "direction": "逆光/侧逆光最佳, 发丝光+长投影",
            },
            "failure_modes": ["窗口短(60-90分钟)=拍摄紧迫, 须预排通告", "黄金时刻拍悲剧=违和(除非反讽)", "错过窗口=等次日, 成本高"],
            "measurement": "金色暖光+柔光质感+诗意希望氛围",
            "alternatives": ["blue_hour(更忧郁)", "practical窗光(可控但失诗意)"],
            "cross_refs": {"genre": "田园/爱情/史诗标配", "composition": "逆光发丝光+长投影", "color": "暖金主调"},
            "masters": "Terrence Malick电影, 《天堂的日子》",
        },
        "blue_hour": {
            "cn": "蓝色时刻(日落后深蓝)",
            "trigger": "忧郁/神秘/过渡/黄昏寂寥/都市夜启/告别",
            "rationale": "日落后天空深蓝=过渡时刻的视觉化, 既非昼非夜=情绪的'之间'状态, 忧郁与神秘。",
            "execution": {
                "timing": "日落后20-40分钟(蓝时刻), 窗口更短",
                "quality": "深蓝色温(8000-10000K)+低强度",
                "balance": "天空蓝vs地面灯暖=冷暖对比",
            },
            "failure_modes": ["窗口极短(20-40分钟)=拍摄极紧迫", "蓝时刻过长曝光=动态模糊, 须三脚架"],
            "measurement": "深蓝天空+冷暖对比+忧郁过渡氛围",
            "alternatives": ["golden_hour(更暖)", "neon(更人工)"],
            "cross_refs": {"genre": "都市/忧郁标配", "composition": "冷暖对比构图", "mood": "寂寥过渡"},
            "masters": "《迷失东京》东京夜, 《她》",
        },
        "silhouette": {
            "cn": "剪影光(背光暗影)",
            "trigger": "神秘/匿名/史诗象征/英雄登场/西部日落/身份未明",
            "rationale": "背光使主体成暗影=去个体化, 强化象征性与轮廓美。剪影=英雄化或匿名化的二元工具。",
            "execution": {
                "backlight": "强背光(天空/窗口/火光), 主体曝光不足",
                "exposure": "按背景曝光, 主体欠曝成剪影",
                "shape": "轮廓须清晰可辨(姿态/帽子/武器)",
            },
            "failure_modes": ["剪影轮廓不清=看不出是谁/什么, 须姿态可辨", "剪影过多=失焦点", "剪影拍对话=看不清表情, 须切回正常曝光"],
            "measurement": "主体成清晰暗影轮廓+象征性/史诗感达成",
            "alternatives": ["rim_light(只勾边但保留细节)", "low_key(更广义暗)"],
            "cross_refs": {"genre": "西部/史诗/英雄标配", "composition": "剪影须配可辨姿态", "narrative": "英雄登场/身份未明"},
            "masters": "《辛德勒的名单》剪影, 西部片日落剪影",
        },
        "neon": {
            "cn": "霓虹光(人工彩色)",
            "trigger": "赛博朋克/都市夜生活/堕落未来/王家卫式迷离/赛博黑色",
            "rationale": "霓虹彩色光(红蓝紫绿)=去自然化, 暗示人工/堕落/未来。色彩本身成为情绪与身份标识。",
            "execution": {
                "colors": "红/蓝/紫/粉/绿彩色光源, 常多色对撞",
                "wet": "湿润地面/雨=霓虹反射倍增氛围",
                "source": "招牌/灯管/屏幕/全息",
            },
            "failure_modes": ["霓虹色过杂=混乱, 须主色+点缀色", "霓虹拍日常=违和(除非刻意)", "肤色被霓虹染绿/紫=失真, 须肤色保护调色"],
            "measurement": "霓虹彩色氛围+赛博/迷离感+肤色可辨",
            "alternatives": ["practical(更真实)", "blue_hour(更自然)"],
            "cross_refs": {"genre": "赛博朋克/都市夜标配", "color": "霓虹色彩即情绪", "wet": "雨夜反射倍增", "color_grading": "肤色保护+风格LUT"},
            "masters": "《银翼杀手》《攻壳机动队》, 王家卫",
        },
        "motivated": {
            "cn": "情境动机光",
            "trigger": "任何需要光线有叙事理由的场景/恐怖片手电/历史片烛光/现代屏幕光",
            "rationale": "光源必须来自场景中合理可见的来源=不违和, 观众潜意识接受光线, 沉浸感最强。是现代摄影的底线原则。",
            "execution": {
                "source_logic": "光源方向/色温/强度须与场景可见源一致",
                "augment": "可用隐藏灯增强但保持动机假象",
                "consistency": "连戏内动机光方向不变",
            },
            "failure_modes": ["动机不合理(光来自不可能方向)=穿帮", "动机光不足=曝光不够, 须隐藏增强", "多源色温不一=须统一或刻意混合"],
            "measurement": "光线有合理动机+不显布灯+连戏一致",
            "alternatives": ["practical(实景动机)", "three_point(可控但失动机)"],
            "cross_refs": {"continuity": "动机光连戏铁律", "genre": "现代摄影底线", "lighting_advanced.motivated_light": "详见进阶"},
            "masters": "Roger Deakins《银翼杀手2049》全场景动机光",
        },
    },

    "composition": {
        # ─── 深度决策: 每种构图 = 触发→原理→量化执行→失败模式→验收→替代→交叉 ───
        "rule_of_thirds": {
            "cn": "三分法",
            "trigger": "通用叙事/对话/日常/需要平衡又动态的常规构图",
            "rationale": "主体置于1/3交叉点=打破居中的呆板, 平衡且有动态张力, 是最通用的安全构图。",
            "execution": {
                "grid": "画面横竖各分三等分, 形成4个交叉点",
                "subject_position": "主体(眼睛/面部)置于交叉点, 通常上1/3",
                "horizon": "地平线置于上或下1/3, 不放正中",
            },
            "failure_modes": ["三分法过于标准=无风格, 艺术片显平庸", "主体不在交叉点=失平衡", "地平线居中=呆板"],
            "measurement": "画面平衡+动态张力+视线自然引导到主体",
            "alternatives": ["center_frame(更庄重)", "golden_ratio(更和谐自然)"],
            "cross_refs": {"genre": "通用叙事标配", "close_up": "特写眼睛置于上1/3", "vertical": "竖屏眼线置上1/3是铁律"},
            "masters": "好莱坞通用构图",
        },
        "center_frame": {
            "cn": "居中构图",
            "trigger": "庄重/对称/权力/仪式感/权威人物/Wes Anderson式风格化",
            "rationale": "主体居中=直接注视, 强调主体权威与画面的仪式感。居中是'被审视的主角'。",
            "execution": {
                "position": "主体严格居中, 左右对称",
                "lens": "中焦50mm避免变形, 或广角对称",
                "background": "背景须对称或有纵深, 强化庄重",
            },
            "failure_modes": ["居中拍日常=呆板, 须有庄重理由", "居中无对称背景=失衡", "广角居中变形=失庄重"],
            "measurement": "庄重/权威/仪式感达成, 须有对称背景",
            "alternatives": ["symmetry(更极端对称)", "rule_of_thirds(更动态)"],
            "cross_refs": {"genre": "权力/风格化标配", "lighting": "居中常配rembrandt光", "vertical": "竖屏居中是铁律(主体在纵轴中心线)"},
            "masters": "Kubrick对称居中, Wes Anderson居中",
        },
        "symmetry": {
            "cn": "对称构图",
            "trigger": "秩序/权威/完美主义/压迫/仪式/超现实/Kubrick式冷峻",
            "rationale": "完美对称=秩序的力量, 也是压迫的来源。对称越完美, 越暗示非人/制度/超自然。",
            "execution": {
                "axis": "左右/上下严格对称, 中轴清晰",
                "tolerance": "对称误差<5%否则失力量",
                "single_point": "单点透视(走廊/门厅)是极致对称",
            },
            "failure_modes": ["对称不完美=失力量, 须精确", "对称滥用=冷感疲劳", "对称拍欢快=违和"],
            "measurement": "秩序/权威/压迫感达成, 须精确对称",
            "alternatives": ["center_frame(更广义居中)", "rule_of_thirds(更动态)"],
            "cross_refs": {"genre": "恐怖/权力/超现实标配", "lighting": "对称常配chiaroscuro", "narrative": "对称=制度/非人, 是压迫的视觉化"},
            "masters": "《闪灵》走廊对称, 《布达佩斯大饭店》",
        },
        "leading_lines": {
            "cn": "引导线",
            "trigger": "需要引导视线到焦点/方向感/目的性/纵深揭示",
            "rationale": "线条(路/栏杆/走廊/河流)天然引导视线, 把观众目光带到焦点=高效的注意力工具。",
            "execution": {
                "lines": "道路/走廊/栏杆/河流/铁轨/阴影线",
                "convergence": "线条汇聚点=焦点(主体), 单点透视是极致",
                "direction": "线条方向=叙事方向(向内=聚集,向外=逃离)",
            },
            "failure_modes": ["引导线指向空=浪费, 须指向主体", "线条杂乱=失引导", "引导线与情绪无关=炫技"],
            "measurement": "观众视线被自然引导到焦点, 须指向主体",
            "alternatives": ["depth_layering(更广义纵深)", "rule_of_thirds(更平衡)"],
            "cross_refs": {"genre": "史诗/纵深叙事标配", "extreme_wide": "极远景常配引导线指向渺小人影", "vertical": "竖屏用纵向线条造纵深"},
            "masters": "《2001太空漫游》走廊引导线, 《教父》透视",
        },
        "frame_within_frame": {
            "cn": "画中画/框中框",
            "trigger": "困住/被观察/隔离/偷窥/密谋/层级嵌套",
            "rationale": "用门窗/镜/帘形成内部框=角色被'框'住, 暗示被困/被观察/被隔离。是心理困境的视觉化。",
            "execution": {
                "frames": "门框/窗框/镜/帘/拱门/栏杆",
                "layers": "可多层嵌套(框中框中框=层层设局)",
                "subject": "角色在内部框中, 被外部框包裹",
            },
            "failure_modes": ["框中无角色=失'被困'主体", "框过杂=失焦点", "框与情绪无关=炫技"],
            "measurement": "观众应读出'被困/被观察/隔离'的心理困境",
            "alternatives": ["negative_space(更广义孤独)", "claustrophobic(更压迫)"],
            "cross_refs": {"genre": "悬疑/密室/偷窥标配", "narrative": "框中框=困局/密谋的视觉化", "lighting": "框中常配chiaroscuro"},
            "masters": "《后窗》窗框构图, John Ford门框, 《教父》门帘",
        },
        "negative_space": {
            "cn": "负空间(留白)",
            "trigger": "孤独/渺小/呼吸感/极简/失去后的空虚/存在主义",
            "rationale": "主体周围大量留白=把角色放在空旷中, 强调孤独与渺小。负空间是'缺席的在场'。",
            "execution": {
                "ratio": "主体占画面<30%, 其余为空",
                "space_direction": "留白方向=视线/运动方向(留呼吸空间)",
                "minimal": "背景须极简, 无干扰元素",
            },
            "failure_modes": ["留白无主体=空洞, 须有渺小角色锚点", "留白方向错=堵, 须给视线/运动留空间", "留白过多=失信息"],
            "measurement": "观众应读出'孤独/渺小/呼吸感', 须有主体锚点",
            "alternatives": ["extreme_wide(更广义渺小)", "frame_within_frame(更困局)"],
            "cross_refs": {"genre": "文艺/孤独叙事标配", "narrative": "失去后空虚标配", "vertical": "竖屏留白可用上下空间"},
            "masters": "《迷失东京》孤独负空间, 《荒野猎人》",
        },
        "depth_layering": {
            "cn": "纵深分层",
            "trigger": "信息层次丰富/空间感/叙事深度/场面调度/前景遮挡偷窥",
            "rationale": "前景+中景+背景三层清晰=画面有Z轴, 信息密度高。深焦让所有层清晰=民主化画面。",
            "execution": {
                "foreground": "前景元素(虚化肩/门框/物件)增加层次",
                "midground": "中景=主要叙事区, 角色动作",
                "background": "背景=环境信息/隐藏细节/暗示",
                "focus": "深焦=全清晰; 浅景深=只中景清晰",
            },
            "failure_modes": ["三层无信息=浪费层次, 须每层有叙事价值", "前景挡主体=失焦点", "深焦但背景杂=失信息"],
            "measurement": "画面有Z轴纵深+每层有叙事信息+空间感强",
            "alternatives": ["leading_lines(更聚焦引导)", "frame_within_frame(更困局)"],
            "cross_refs": {"genre": "场面调度/史诗标配", "lens": "深焦配广角+小光圈", "spielberg": "前景遮挡是Spielberg标志"},
            "masters": "Orson Welles深焦《公民凯恩》, Spielberg前景遮挡",
        },
        "diagonal": {
            "cn": "对角线构图",
            "trigger": "动感/不稳定/冲突/运动方向/紧张对峙/失衡",
            "rationale": "主体沿对角线=打破水平垂直的稳定, 制造动感与失衡。对角线=视觉的'动词'。",
            "execution": {
                "line": "主体/动作沿画面左上到右下(或反向)对角",
                "tilt": "可配荷兰角强化失衡",
                "motion": "运动方向沿对角=动势强",
            },
            "failure_modes": ["对角无动势=失动感, 须配运动/冲突", "对角滥用=失稳定基准", "对角与情绪冲突=违和"],
            "measurement": "观众应读出'动感/失衡/冲突', 须配运动或对峙",
            "alternatives": ["claustrophobic(更压迫)", "center_frame(更稳定)"],
            "cross_refs": {"genre": "动作/紧张对峙标配", "narrative": "失衡=危机前夕/世界观崩塌", "dutch_angle": "对角+荷兰角=极致失衡"},
            "masters": "动作片通用, 《七宗罪》对角失衡",
        },
        "golden_ratio": {
            "cn": "黄金比例",
            "trigger": "和谐美感/自然舒适/古典美学/需要比三分法更优雅的构图",
            "rationale": "1:1.618是自然界的和谐比例, 潜意识读为'美'。比三分法更优雅但更难精确。",
            "execution": {
                "ratio": "主体置于黄金分割点(约画面的0.618)",
                "spiral": "黄金螺旋引导视线, 主体在螺旋终点",
                "precision": "比三分法更难精确, 须经验",
            },
            "failure_modes": ["黄金比例与三分法差异小=观众难辨, 须靠螺旋", "精确过度=炫技, 失自然"],
            "measurement": "和谐美感达成, 比三分法更优雅",
            "alternatives": ["rule_of_thirds(更通用易行)", "center_frame(更庄重)"],
            "cross_refs": {"genre": "古典美学/文艺标配", "composition": "黄金螺旋是进阶引导线"},
            "masters": "古典绘画传统, 部分文艺片",
        },
        "claustrophobic": {
            "cn": "压迫构图(挤压)",
            "trigger": "窒息/被困/精神压力/幽闭/密室/心理崩溃",
            "rationale": "角色被画面边缘/物体挤压=视觉化的窒息感。压迫构图让画面本身成为施压者。",
            "execution": {
                "squeeze": "角色被画面边缘/天花板/墙壁挤压",
                "tight": "近景+拥挤构图, 无呼吸空间",
                "low_ceiling": "低天花板/窄通道强化压迫",
            },
            "failure_modes": ["压迫拍开放场景=违和, 须密闭", "压迫无情绪理由=炫技", "压迫过久=观众也窒息疲劳"],
            "measurement": "观众应读出'窒息/被困/精神压力', 须密闭环境",
            "alternatives": ["frame_within_frame(更被观察)", "negative_space(相反,留白)"],
            "cross_refs": {"genre": "恐怖/幽闭/心理标配", "narrative": "压迫=心理崩溃的视觉化", "lighting": "常配low_key+暗部"},
            "masters": "《房间》狭小空间, 《活埋》棺材构图",
        },
    },

    "color_psychology": {
        # ─── 深度决策: 每种色彩 = 触发→原理→量化执行→失败模式→验收→替代→交叉 ───
        "red": {
            "cn": "红",
            "trigger": "激情/危险/爱情/暴力/愤怒/警告/血脉/欲望",
            "rationale": "红色是最高视觉唤醒色, 生理上加速心跳。指向欲望与危险的双重性, 是最强的色彩情绪锚点。",
            "execution": {
                "saturation": "高饱和红=危险/暴力; 低饱和暗红=权力/血脉",
                "use": "点缀红(《辛德勒》红衣)=焦点锚点; 段落红(《英雄》)=主题色块",
                "mix": "红+黑=暴力/权力; 红+金=欲望/奢华; 红+白=警示/纯真",
            },
            "failure_modes": ["红色过多=视觉过载, 须点缀或段落使用", "红与场景色调冲突=须统一色彩方案", "红肤色=失真, 须肤色保护"],
            "measurement": "观众应被红色锚定到焦点/情绪, 须有节制使用",
            "alternatives": ["orange(更温暖少危险)", "purple(更神秘少暴力)"],
            "cross_refs": {"genre": "暴力/爱情/警示标配", "foreshadow": "红常作伏笔锚点(契诃夫之枪)", "color_grading": "红在二级调色局部强化"},
            "examples": "《辛德勒的名单》红衣女孩, 《英雄》红色段落, 《第六感》红锚点",
        },
        "blue": {
            "cn": "蓝",
            "trigger": "忧郁/冷静/科技/孤独/纯净/疏离/记忆",
            "rationale": "蓝色生理上降低体温感, 指向冷静与忧郁的双重性。是现代摄影的默认冷调。",
            "execution": {
                "shade": "深蓝=忧郁/科技; 浅蓝=纯净/希望; 钴蓝=孤独",
                "use": "蓝调时段(蓝时刻)自然蓝; 赛博蓝=霓虹",
                "mix": "蓝+橙=赛博对比; 蓝+白=纯净科技; 蓝+黑=深邃孤独",
            },
            "failure_modes": ["蓝色过多=冷感疲劳, 须暖点缀", "蓝肤色=失真, 须肤色保护", "蓝拍温暖场景=违和"],
            "measurement": "观众应读出'冷静/忧郁/孤独/科技'之一, 须有暖色平衡",
            "alternatives": ["cold_palette(更广义冷)", "green(更不安少忧郁)"],
            "cross_refs": {"genre": "科幻/悬疑/都市标配", "time": "蓝时刻标配", "lighting": "蓝常配practical/霓虹"},
            "examples": "《银翼杀手》蓝色城市, 《蓝色大门》, 《消失的爱人》冷蓝",
        },
        "green": {
            "cn": "绿",
            "trigger": "自然/嫉妒/腐败/生机/不安/诡异/疾病",
            "rationale": "绿色双重性最强: 自然生机vs嫉妒腐败。诡异绿(荧光/暗绿)=不安与超自然。",
            "execution": {
                "shade": "自然绿=生机; 暗绿=腐败; 荧光绿=诡异/超自然/疾病",
                "use": "《黑客帝国》代码绿=虚拟/数字世界",
                "mix": "绿+黑=腐败/恐怖; 绿+蓝=不安科技; 绿+金=自然奢华",
            },
            "failure_modes": ["绿色肤色=失真, 须肤色保护", "荧光绿过多=廉价恐怖", "绿拍日常=违和(除非田园)"],
            "measurement": "观众应读出'自然/嫉妒/腐败/不安'之一, 诡异绿须谨慎",
            "alternatives": ["blue(更冷更忧郁)", "yellow(更温暖警告)"],
            "cross_refs": {"genre": "恐怖(诡异绿)/田园(自然绿)标配", "matrix": "《黑客帝国》代码绿是数字世界标志", "color_grading": "绿肤色保护须二级调色"},
            "examples": "《黑客帝国》绿色代码雨, 《迷失东京》, 《僵尸肖恩》诡异绿",
        },
        "yellow": {
            "cn": "黄",
            "trigger": "温暖/疯狂/警告/希望/炎热/怀旧/童真",
            "rationale": "黄色最亮最暖, 指向希望与童真, 但也指疯狂(高温)与警告。是双面色。",
            "execution": {
                "shade": "暖黄=怀旧/温暖; 亮黄=警告/疯狂; 金黄=希望/神圣",
                "use": "黄金时刻金光=温暖希望; 沙漠黄=炎热末世",
                "mix": "黄+橙=炎热温暖; 黄+黑=警告危险; 黄+绿=疾病不安",
            },
            "failure_modes": ["黄色过多=刺眼疲劳", "黄肤色=失真(亚洲肤色尤其)", "黄拍悬疑=违和(除非警示)"],
            "measurement": "观众应读出'温暖/希望/疯狂/警告'之一",
            "alternatives": ["orange(更成熟温暖)", "golden_hour(更诗意)"],
            "cross_refs": {"genre": "末世/喜剧/童年标配", "time": "黄金时刻金光", "lighting": "黄常配golden_hour"},
            "examples": "《疯狂的麦克斯》沙漠金黄, 《触不可及》暖黄, 《辛德勒》暖黄童年",
        },
        "orange": {
            "cn": "橙",
            "trigger": "温暖/能量/青春/热情/怀旧/夕阳/家庭",
            "rationale": "橙色是暖色的成熟版, 比黄更稳重, 指向温暖与怀旧。是家庭/怀旧片的默认暖调。",
            "execution": {
                "shade": "暖橙=家庭/怀旧; 亮橙=青春能量; 暗橙=复古",
                "use": "夕阳橙=怀旧温暖; 灯光橙=家庭温馨",
                "mix": "橙+蓝=商业大片青橙对比; 橙+红=热情能量; 橙+棕=复古怀旧",
            },
            "failure_modes": ["橙色过多=甜腻", "橙拍冷酷场景=违和", "teal_orange滥用=商业大片廉价感"],
            "measurement": "观众应读出'温暖/怀旧/青春'之一",
            "alternatives": ["yellow(更亮更疯狂)", "warm_palette(更广义暖)"],
            "cross_refs": {"genre": "家庭/怀旧/青春标配", "teal_orange": "橙+青是商业大片标配", "lighting": "橙常配golden_hour/暖灯"},
            "examples": "《布达佩斯大饭店》暖橙基调, 《教父》暖橙权力",
        },
        "purple": {
            "cn": "紫",
            "trigger": "神秘/权力/梦幻/超自然/魔法/高贵/堕落",
            "rationale": "紫色=红+蓝的混合, 兼有激情与冷静, 指向神秘与超自然。是魔法/玄幻的标志色。",
            "execution": {
                "shade": "暗紫=权力/高贵; 亮紫=梦幻/魔法; 紫红=堕落",
                "use": "仙侠紫=法力/魔道; 紫色光=超自然",
                "mix": "紫+金=高贵权力; 紫+黑=神秘魔道; 紫+蓝=梦幻超自然",
            },
            "failure_modes": ["紫色过多=廉价魔幻", "紫肤色=失真", "紫拍现实=违和(除非超自然)"],
            "measurement": "观众应读出'神秘/权力/梦幻/超自然'之一",
            "alternatives": ["blue(更冷更科技)", "red(更激情少神秘)"],
            "cross_refs": {"genre": "仙侠/玄幻/魔法标配", "xianxia": "紫=魔道/法力标志", "lighting": "紫色色片/霓虹"},
            "examples": "仙侠紫色法力, 《沉睡魔咒》紫色魔法",
        },
        "black": {
            "cn": "黑",
            "trigger": "死亡/未知/权力/优雅/绝望/神秘/极简",
            "rationale": "黑色是缺席, 也是最强框架。指向死亡与权力的双重性, 也是极简的背景。",
            "execution": {
                "use": "大面积黑=低调/恐怖; 黑色服饰=权力/优雅; 黑色背景=极简",
                "shadow": "暗部占画面60%+=低调光",
                "mix": "黑+红=暴力权力; 黑+金=奢华权力; 黑+白=极简对比",
            },
            "failure_modes": ["黑色过多=看不清, 须留细节", "黑色拍欢快=违和", "黑无层次=死黑, 须暗部细节"],
            "measurement": "观众应读出'死亡/权力/优雅/神秘'之一, 须有暗部层次",
            "alternatives": ["desaturated(更广义褪色)", "low_key(更广义暗)"],
            "cross_refs": {"genre": "黑色电影/权力/恐怖标配", "lighting": "黑常配low_key/chiaroscuro", "color_grading": "黑须保暗部细节(LIFT)"},
            "examples": "黑色电影基调, 《黑暗骑士》",
        },
        "white": {
            "cn": "白",
            "trigger": "纯净/空虚/死亡(东方)/新开始/神圣/超现实/医院",
            "rationale": "白色双重性: 西方=纯净神圣; 东方=死亡丧服。也是空虚与超现实的背景。",
            "execution": {
                "use": "大面积白=高调/纯净; 白色空间=超现实/医院; 白雾=未知/灵界",
                "overexpose": "过曝白=顿悟/死亡(东方)",
                "mix": "白+黑=极简对比; 白+蓝=冷纯净; 白+金=神圣",
            },
            "failure_modes": ["白色过多=过曝失信息", "白拍悲剧=违和(西方), 但东方白=死亡", "白无层次=死白, 须高光细节"],
            "measurement": "观众应读出'纯净/空虚/死亡/神圣'之一(注意东西方差异)",
            "alternatives": ["high_key(更广义亮)", "desaturated(更广义褪色)"],
            "cross_refs": {"genre": "科幻/神圣/医院标配", "cultural": "东方白=死亡, 西方白=纯净", "color_grading": "白须保高光细节(GAIN)"},
            "examples": "《2001太空漫游》白色空间, 《雪国》白雾",
        },
        "desaturated": {
            "cn": "去饱和",
            "trigger": "荒凉/记忆/创伤/末日/纪实/历史/战争残酷",
            "rationale": "去饱和=褪去色彩活力, 指向记忆/创伤/荒凉。是战争与末世的视觉编码。",
            "execution": {
                "level": "轻度去饱和=纪实/历史; 重度近黑白=创伤/末日",
                "use": "《拯救大兵瑞恩》去饱和战场=纪实残酷",
                "spot_color": "去饱和中点缀一抹彩色=焦点(《辛德勒》红衣)",
            },
            "failure_modes": ["去饱和过度=失情绪色彩, 须留主色", "去饱和拍欢快=违和", "去饱和无spot color=单调"],
            "measurement": "观众应读出'荒凉/记忆/创伤/纪实'之一, 须有主色或spot color",
            "alternatives": ["black_white(更极端)", "cold_palette(更冷但有色)"],
            "cross_refs": {"genre": "战争/末世/纪实标配", "color_grading": "去饱和是调色风格LUT", "spot_color": "去饱和+spot color是经典手法"},
            "examples": "《拯救大兵瑞恩》去饱和战场, 《罪恶之城》去饱和+spot color",
        },
        "warm_palette": {
            "cn": "暖色调",
            "trigger": "温馨/怀旧/安全/亲密/家庭/童年/日常美好",
            "rationale": "整体暖调=视觉的拥抱, 指向安全与温暖。是家庭/怀旧/童年段的默认调。",
            "execution": {
                "base": "橙/黄/金为主色",
                "temp": "色温偏暖(3200K以下感觉)",
                "use": "《美丽人生》暖色童年段=温暖记忆",
            },
            "failure_modes": ["暖调拍冷酷场景=违和", "暖调过甜=失真实, 须冷点缀", "暖调连戏困难(时段变)"],
            "measurement": "观众应读出'温馨/怀旧/安全'之一",
            "alternatives": ["golden_hour(更诗意自然)", "cold_palette(相反)"],
            "cross_refs": {"genre": "家庭/怀旧/童年标配", "narrative": "回忆段常用暖调与现在区分", "lighting": "暖调常配golden_hour/暖灯"},
            "examples": "《美丽人生》暖色童年, 《天堂电影院》怀旧暖调",
        },
        "cold_palette": {
            "cn": "冷色调",
            "trigger": "疏离/危险/科技/清冷/孤独/现代/异化",
            "rationale": "整体冷调=视觉的距离, 指向疏离与现代异化。是科技/都市/悬疑的默认调。",
            "execution": {
                "base": "蓝/青/灰为主色",
                "temp": "色温偏冷(5600K以上感觉)",
                "use": "《社交网络》冷蓝=现代疏离",
            },
            "failure_modes": ["冷调拍温暖场景=违和", "冷调过冷=失人情, 须暖点缀", "冷调连戏困难"],
            "measurement": "观众应读出'疏离/危险/科技/清冷'之一",
            "alternatives": ["blue(更具体蓝)", "warm_palette(相反)"],
            "cross_refs": {"genre": "科幻/都市/悬疑标配", "narrative": "现代疏离/异化的视觉化", "lighting": "冷调常配practical冷光/蓝时刻"},
            "examples": "《社交网络》冷蓝, 《银翼杀手》冷调疏离",
        },
        "teal_orange": {
            "cn": "青橙对比",
            "trigger": "商业大片/角色与环境分离/视觉冲击/好莱坞动作大片",
            "rationale": "青(冷)环境+橙(暖)肤色/光源=角色与环境色彩分离, 主体跳出。是商业大片的视觉糖衣。",
            "execution": {
                "shadows": "暗部偏青/蓝",
                "highlights": "亮部偏橙/暖(肤色保护)",
                "contrast": "冷暖对比最大化主体分离",
            },
            "failure_modes": ["teal_orange滥用=商业大片廉价感, 艺术片慎用", "肤色橙过=失真", "对比过强=失自然"],
            "measurement": "角色与环境色彩分离+视觉冲击, 但不可过假",
            "alternatives": ["warm_palette(更纯暖)", "cold_palette(更纯冷)"],
            "cross_refs": {"genre": "商业大片/动作标配", "color_grading": "是调色LUT的商业默认", "skin": "须肤色橙保护"},
            "examples": "《变形金刚》, Marvel电影",
        },
    },

    # ========================================================
    # 镜头语言(焦段心理学)
    # ========================================================
    "lens_language": {
        # ─── 深度决策: 每个焦段 = 触发→原理→量化执行→失败模式→验收→替代→交叉 ───
        "wide_lens": {
            "cn": "广角(24-35mm)",
            "trigger": "建立镜头/室内空间/英雄仰拍/恐怖变形/环境包裹感",
            "rationale": "广角近距=前景夸张变形+背景退后=空间包裹感。是空间压迫与英雄化的核心工具。",
            "execution": {
                "focal": "24-35mm, 越广变形越大",
                "distance": "须近距(1-3m), 否则失变形张力",
                "distortion": "近距边缘变形=人物扭曲, 远距=环境退后",
            },
            "failure_modes": ["近距人物面部变形=失真, 须控制距离或换中焦", "广角拍肖像=鼻孔变形, 慎用", "广角连戏困难(透视与中焦不一致)"],
            "measurement": "空间包裹感达成, 须有变形理由(压迫/英雄/恐怖)",
            "alternatives": ["normal_lens(更自然)", "telephoto(压缩相反)"],
            "cross_refs": {"angle": "广角+仰拍=英雄化", "genre": "恐怖(变形)/史诗(广阔)标配", "composition": "广角强化纵深"},
            "masters": "《公民凯恩》广角仰拍, 《闪灵》走廊广角",
        },
        "normal_lens": {
            "cn": "标准(50mm)",
            "trigger": "对话/日常/纪录片质感/客观中立/最接近人眼",
            "rationale": "50mm=人眼透视, 最自然无变形。是客观叙事与日常亲密的默认焦段。",
            "execution": {
                "focal": "50mm(全画幅), APS-C约35mm",
                "distance": "中距2-5m, 自然对话距离",
                "perspective": "无变形, 透视真实",
            },
            "failure_modes": ["全程50mm=单调, 须焦段变化", "50mm拍史诗=失规模, 须广角"],
            "measurement": "自然真实+无变形+客观中立",
            "alternatives": ["wide_lens(更广阔变形)", "telephoto(更压缩)"],
            "cross_refs": {"genre": "日常/对话/纪实标配", "realism": "纪实感来源", "dialogue": "对话戏默认焦段"},
            "masters": "小津安二郎, 纪实摄影",
        },
        "telephoto": {
            "cn": "长焦(85-200mm)",
            "trigger": "偷窥/凝视/压缩人群/孤立主体/距离感/野生动物",
            "rationale": "长焦=压缩空间(前后景贴近)+窄视角=偷窥感与距离感。是疏离与凝视的工具。",
            "execution": {
                "focal": "85-200mm, 越长压缩越强",
                "distance": "须远距(5-50m), 否则失主体",
                "compression": "前后景压缩=空间扁平化, 孤立主体",
            },
            "failure_modes": ["长焦远距=收音困难(须长枪麦)", "长焦压缩失空间感=须有偷窥/距离理由", "长焦手持抖=须三脚架/稳定器"],
            "measurement": "压缩空间+偷窥感/距离感达成",
            "alternatives": ["normal_lens(更自然)", "wide_lens(更广阔相反)"],
            "cross_refs": {"genre": "悬疑/偷窥/疏离标配", "composition": "长焦压缩常配negative_space孤立", "sound": "长焦远距须配长枪麦"},
            "masters": "《荒野猎人》追逐长焦压缩, 王家卫长焦偷拍",
        },
        "macro": {
            "cn": "微距",
            "trigger": "微观宇宙/极致细节/超越人眼发现感/微观恐惧(皮肤/瞳孔)",
            "rationale": "微距=放大到超越人眼, 发现肉眼不可见的细节。是发现感与微观恐惧的工具。",
            "execution": {
                "focal": "微距镜头(1:1或更大放大率)",
                "distance": "极近(几厘米-几十厘米)",
                "dof": "极浅景深, 须小光圈(f/16+)保清晰",
            },
            "failure_modes": ["微距景深极浅=须小光圈+稳定", "微距布光难=须环闪/柔光", "微距无叙事=炫技"],
            "measurement": "微观发现感达成, 须有叙事理由(伏笔/恐怖/发现)",
            "alternatives": ["extreme_close_up(更广义极特写)", "insert(物件细节)"],
            "cross_refs": {"genre": "科幻/恐怖/纪实标配", "foreshadow": "微距物件可埋伏笔", "lighting": "微距须环闪/柔光"},
            "masters": "《微观世界》, 科幻微观段落",
        },
        "anamorphic": {
            "cn": "变形宽银幕",
            "trigger": "好莱坞大片/电影感/横向拉伸光斑/复古好莱坞/夜景霓虹",
            "rationale": "变形宽银幕=横向压缩记录+展开放映=2.39:1宽画幅+横向椭圆光斑=电影感的核心视觉标志。",
            "execution": {
                "format": "2x变形镜头(常见2.39:1)",
                "flare": "横向拉伸光斑(蓝/橙)=电影感标志",
                "bokeh": "椭圆形焦外, 横向拉伸",
            },
            "failure_modes": ["变形镜头昂贵=预算考量", "变形光斑滥用=廉价电影感", "变形畸变(边缘拉伸)=须控制人物位置"],
            "measurement": "电影感达成(宽画幅+横向光斑+椭圆焦外)",
            "alternatives": ["spherical(球面, 更自然但失电影感)", "crop_wide(裁切宽但失变形特性)"],
            "cross_refs": {"genre": "好莱坞大片/夜景标配", "lighting": "变形光斑配霓虹/逆光最佳", "format": "2.39:1宽画幅"},
            "masters": "《银翼杀手》变形光斑, 《敦刻尔克》",
        },
        "tilt_shift": {
            "cn": "移轴",
            "trigger": "微缩模型感/玩具化世界/上帝俯瞰/超现实段落",
            "rationale": "移轴偏移焦平面=只一条带清晰, 城市鸟瞰微缩化=玩具感。是超现实的工具。",
            "execution": {
                "shift": "移轴镜头偏移, 制造窄焦带",
                "use": "俯拍城市=微缩模型; 俯拍人群=玩具",
                "distance": "须高处俯拍",
            },
            "failure_modes": ["移轴无俯拍=失微缩感", "移轴滥用=炫技", "移轴拍人物=失工具价值"],
            "measurement": "微缩模型感达成, 须俯拍",
            "alternatives": ["macro(更微观但失模型感)", "birds_eye(更全知但无微缩)"],
            "cross_refs": {"genre": "超现实/创意段落", "composition": "移轴须配俯拍", "vfx": "也可后期模拟"},
            "masters": "城市鸟瞰微缩, 《布达佩斯》风格化",
        },
    },

    # ========================================================
    # 景深控制
    # ========================================================
    "depth_of_field": {
        # ─── 深度决策: 每种景深 = 触发→原理→量化执行→失败模式→验收→替代→交叉 ───
        "shallow": {
            "cn": "浅景深",
            "trigger": "肖像/情感特写/隔绝背景/浪漫/悬疑/孤独/梦幻聚焦",
            "rationale": "浅景深=主体清晰背景虚化=视觉隔离, 把主体从环境抽出, 制造亲密或孤独。",
            "execution": {
                "aperture": "大光圈(f/1.4-f/2.8)",
                "focal": "长焦(85mm+)强化浅景深",
                "distance": "近距强化虚化",
                "bokeh": "焦外光斑是美学元素(圆形/变形椭圆)",
            },
            "failure_modes": ["浅景深连戏困难(焦点漂移)", "虚化过度=失环境信息", "浅景深拍群戏=只一人清晰, 须深焦"],
            "measurement": "主体隔离+背景虚化+亲密/孤独达成",
            "alternatives": ["deep_focus(全清晰相反)", "rack_focus(转移焦点)"],
            "cross_refs": {"genre": "肖像/言情/悬疑标配", "romance": "浅景深=只有彼此", "close_up": "特写浅景深强化情绪"},
            "masters": "王家卫极浅景深, 《私情》",
        },
        "deep_focus": {
            "cn": "深焦(全景深)",
            "trigger": "场面调度/信息密度高/民主化画面/命运全景/多层叙事",
            "rationale": "深焦=前景中景背景全清晰=所有层次平等呈现, 观众自选焦点。是民主化画面。",
            "execution": {
                "aperture": "小光圈(f/8-f/16)",
                "focal": "广角(24-35mm)强化深焦",
                "light": "须强光(小光圈进光少)",
            },
            "failure_modes": ["深焦信息过载=须引导线/构图引导", "深焦须强光=布光成本高", "深焦失主体隔离=须构图锚定主体"],
            "measurement": "所有层次清晰+信息密度高+民主化画面",
            "alternatives": ["shallow(隔离相反)", "split_diopter(双焦点折中)"],
            "cross_refs": {"genre": "场面调度/史诗标配", "composition": "深焦须配depth_layering+引导线", "lighting": "深焦须强光"},
            "masters": "《公民凯恩》深焦革命, Orson Welles",
        },
        "rack_focus": {
            "cn": "焦点转移",
            "trigger": "对话中谁重要谁清晰/揭示反应/无切镜头内的视角转换",
            "rationale": "焦点从A转B=无切镜头内的注意力转移, 揭示关系与反应, 是经济的'剪辑'。",
            "execution": {
                "transition": "焦点从前景转背景(或反之), 1-3秒",
                "timing": "须卡在台词/情绪转折点",
                "two_subjects": "须两人/两物在不同景深",
            },
            "failure_modes": ["焦点转移过慢=观众察觉机心", "焦点转移无叙事理由=炫技", "转移中两主体都半虚=失焦"],
            "measurement": "无切镜头内的注意力转移+揭示关系",
            "alternatives": ["cut(更快但失连续)", "shallow固定(更简单但失转移)"],
            "cross_refs": {"dialogue": "对话谁重要谁清晰", "performance": "焦点转移须配表演转折", "pacing": "焦点转移是节奏重音"},
            "masters": "《社交网络》对话焦点转移, 《猎物》",
        },
        "split_diopter": {
            "cn": "分光镜(双焦点)",
            "trigger": "同时呈现前景动作与背景反应/两个叙事重点/不愿深焦但须双清晰",
            "rationale": "分光镜=前景与背景同时清晰(两个焦点)=两个叙事重点并列, 是深焦的替代但失民主(选择性)。",
            "execution": {
                "lens": "分光镜附件, 两个焦点平面",
                "use": "前景动作+背景反应同时清晰",
                "line": "画面有一道分割线(须用构图隐藏)",
            },
            "failure_modes": ["分光镜分割线穿帮=须构图隐藏", "分光镜昂贵=预算考量", "双焦点无对照意义=失双叙事价值"],
            "measurement": "前景+背景双清晰+两个叙事重点并列",
            "alternatives": ["deep_focus(全清晰但失选择性)", "rack_focus(转移但失同时)"],
            "cross_refs": {"genre": "悬疑/对话标配", "composition": "分割线须隐藏", "narrative": "双焦点=两个叙事重点"},
            "masters": "《星际穿越》《总统班底》",
        },
    },

    # ========================================================
    # 高级布光技法
    # ========================================================
    "lighting_advanced": {
        # ─── 深度决策: 进阶布光技法 ───
        "color_gels": {
            "cn": "彩色灯光纸(色片)",
            "trigger": "赛博朋克/霓虹迷离/情感隐喻/色彩段落/非自然情绪化布光",
            "rationale": "在灯具前加彩色滤纸=人为改变光色, 用色彩做情绪与身份隐喻。是王家卫/维伦纽瓦的色彩工具。",
            "execution": {
                "gel_type": "CTO(暖橙)/CTB(冷蓝)+彩色片(红/绿/紫/粉)",
                "combine": "多色对撞(蓝+橙=赛博, 红+绿=诡异)",
                "skin_protection": "肤色须保护, 避免染绿/紫失真",
            },
            "failure_modes": ["色片色过杂=混乱, 须主色+点缀", "肤色被染失真=须二级调色保护", "色片与场景色调冲突=须统一色彩方案"],
            "measurement": "色彩情绪化达成+肤色可辨+色彩方案统一",
            "alternatives": ["neon(实景霓虹)", "color_grading(后期调色但失布光质感)"],
            "cross_refs": {"color_psychology": "色片色彩即情绪", "genre": "赛博/迷离标配", "color_grading": "后期须与色片方案一致"},
            "masters": "《银翼杀手2049》蓝橙对撞, 王家卫霓虹色片",
        },
        "bounce_light": {
            "cn": "反射光(柔光)",
            "trigger": "自然柔和人像/日常真实感/无硬阴影/纪实风格/补光",
            "rationale": "光源打在反光板/墙/天花板后反射=散射柔光, 模仿自然漫射, 无硬阴影最真实。",
            "execution": {
                "surface": "白反光板/泡沫板/墙壁/天花板",
                "distance": "反射面越近越柔, 越远越弱",
                "color_cast": "彩色墙面会染色, 须白色或校正",
            },
            "failure_modes": ["反射光不足=补不够, 须增大反光面/加LED", "彩色墙面染色=失真, 须白板校正", "反射方向不对=补错位置"],
            "measurement": "柔光无硬阴影+自然真实+补光到位",
            "alternatives": ["柔光箱(更可控但失自然)", "practical窗光(更自然但不可控)"],
            "cross_refs": {"genre": "纪实/日常标配", "close_up": "特写柔光减瑕疵", "continuity": "反射光随环境变, 连戏须注意"},
            "masters": "Roger Deakins自然柔光",
        },
        "edge_light": {
            "cn": "轮廓光/边缘光(rim light)",
            "trigger": "主体与暗背景分离/英雄出场/专业人像/神秘立体感/发丝光",
            "rationale": "从背后侧方打光勾边=主体轮廓从背景跳出, 既分离又立体。英雄化/专业感的核心工具。",
            "execution": {
                "position": "背后侧逆45-135度, 勾勒头部/肩膀/发丝",
                "intensity": "强于主光1-2档, 形成明显发边",
                "fringe": "发丝光须细而亮, 不喧宾夺主",
            },
            "failure_modes": ["轮廓光过强=不自然发边, 须控制强度", "轮廓光位置错=勾不到边, 须精确调位", "无轮廓光主体融于暗背景=失分离"],
            "measurement": "主体轮廓清晰跳出背景+立体感/英雄化达成",
            "alternatives": ["silhouette(更极端只留轮廓)", "three_point的rim(更通用)"],
            "cross_refs": {"genre": "英雄/专业人像标配", "silhouette": "边缘光的极端版", "golden_hour": "逆光发丝光是天然边缘光"},
            "masters": "好莱坞英雄出场, 《角斗士》",
        },
        "under_lighting": {
            "cn": "底光(下方光源)",
            "trigger": "恐怖/超自然/邪恶/篝火讲故事/鬼怪/心理扭曲",
            "rationale": "光从下方=违反自然(自然光从上), 颠覆光源逻辑=潜意识不安。是恐怖与邪恶的视觉编码。",
            "execution": {
                "position": "光源从下方45-90度, 仰射面部",
                "shadow": "阴影向上投射, 鼻影/眼窝阴影反转",
                "source_motivation": "篝火/手电/手机/灯笼等下方源",
            },
            "failure_modes": ["底光无动机=穿帮, 须有下方源(篝火/手电)", "底光滥用=廉价恐怖, 须慎用", "底光拍正常对话=违和诡异"],
            "measurement": "光源下方+阴影反转+恐怖/邪恶氛围达成",
            "alternatives": ["low_key(更广义暗)", "chiaroscuro(更戏剧但失恐怖编码)"],
            "cross_refs": {"genre": "恐怖/超自然标配", "performance": "底光下面部表情扭曲变形", "motivated": "须有下方源动机"},
            "masters": "《驱魔人》底光, 营火讲故事场景",
        },
        "motivated_light": {
            "cn": "情境动机光(进阶)",
            "trigger": "任何现代摄影/沉浸感/叙事合理性/连戏一致性",
            "rationale": "光源必须来自场景中合理可见的来源=不违和。是现代摄影底线原则, 区别于'打亮就行'的旧式布光。",
            "execution": {
                "source_visibility": "光源须在画面内或暗示存在(窗/灯/烛/月/屏幕)",
                "direction_match": "光线方向须与可见源一致",
                "color_temp_match": "色温须与源一致(烛光暖/窗光冷)",
                "augment_hidden": "可用隐藏灯增强但保持动机假象",
            },
            "failure_modes": ["动机不合理(光来自不可能方向)=穿帮", "动机光不足=曝光不够, 须隐藏增强但保动机", "连戏动机光方向变了=穿帮"],
            "measurement": "光线有合理动机+不显布灯+连戏一致+沉浸感",
            "alternatives": ["practical(实景动机)", "three_point(可控但失动机)"],
            "cross_refs": {"continuity": "动机光连戏铁律", "modern_cinematography": "现代摄影底线", "lighting.motivated": "基础版"},
            "masters": "Roger Deakins《银翼杀手2049》全场景动机光",
        },
        "negative_fill": {
            "cn": "负补光(黑旗吸光)",
            "trigger": "低调人像/黑色电影/面部雕塑感/强化对比/加深暗部",
            "rationale": "用黑旗/黑布吸收光线=加深阴影侧, 增加对比与造型。是'减法布光', 比加光更精准控制暗部。",
            "execution": {
                "tool": "黑旗/黑布/吸光板",
                "position": "放在补光侧吸光, 加深阴影",
                "effect": "暗部更深, 对比更强, 面部雕塑感",
            },
            "failure_modes": ["负补过强=暗部死黑无细节, 须留可辨细节", "无负补=暗部灰平, 失立体感"],
            "measurement": "暗部加深但有细节+对比增强+造型立体",
            "alternatives": ["low_key(更广义暗)", "chiaroscuro(更极端对比)"],
            "cross_refs": {"genre": "黑色电影/低调人像标配", "close_up": "特写负补强化面部雕塑", "continuity": "负补位置连戏一致"},
            "masters": "《社交网络》低调人像, Fincher摄影",
        },
    },

    # ========================================================
    # 视觉节奏(剪辑与镜头时长的音乐性)
    # ========================================================
    "visual_rhythm": {
        "shot_duration_theory": {
            "fast_cutting": "短镜快切(<2s):紧张、动作、信息爆炸、现代焦虑",
            "medium": "中镜(3-5s):叙事主力、对话节奏、日常推进",
            "long_take": "长镜头(>15s):沉浸、真实时间、场面调度、导演炫技",
            "extreme_long": "极长镜头(>60s):仪式感、时间凝固、史诗段落",
        },
        "emotional_breathing": {
            "principle": "剪辑节奏应模仿观众的情绪呼吸——紧张时短促,抒情时绵长",
            "build_up": "蓄势段落用中长镜头,缓慢收束注意力",
            "release": "高潮段落快切释放积蓄的能量",
            "aftermath": "高潮后必须给一个长镜头让情绪沉淀(否则观众消化不了)",
        },
        "music_sync": {
            "on_beat_cut": "在音乐节拍点剪辑=流畅、MV感、律动感",
            "off_beat_cut": "故意错开节拍=不安、颠覆预期、爵士感",
            "sound_silence": "音乐戛然而止比音乐高潮更有冲击力",
            "ambient_layering": "环境音层层叠加=压力上升;一层层消失=聚焦内心",
        },
        "rhythm_patterns": {
            "accelerando": "5s→4s→3s→2s→1s 冲向高潮(渐快)",
            "ritardando": "1s→2s→3s→5s→8s 高潮后沉淀(渐慢)",
            "staccato": "0.5s极短切连击=混乱、暴力、失控",
            "legato": "长镜头连贯=流畅、抒情、史诗",
            "syncopation": "长短交替(2s-5s-2s-5s)=对话呼吸、对比张力",
        },
    },
}
